/* Generated By:JavaCC: Do not edit this line. JclConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JclConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int OPEN_PARAN = 3;
  /** RegularExpression Id. */
  int CLOSE_PARAN = 4;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 5;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 6;
  /** RegularExpression Id. */
  int OPEN_BRACE = 7;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 8;
  /** RegularExpression Id. */
  int PAIR_SEP = 9;
  /** RegularExpression Id. */
  int END_STMT = 10;
  /** RegularExpression Id. */
  int CONCAT = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int DOT = 13;
  /** RegularExpression Id. */
  int CONS = 14;
  /** RegularExpression Id. */
  int CAR = 15;
  /** RegularExpression Id. */
  int CDR = 16;
  /** RegularExpression Id. */
  int DIS = 17;
  /** RegularExpression Id. */
  int CONNECT = 18;
  /** RegularExpression Id. */
  int WRITE = 19;
  /** RegularExpression Id. */
  int READ = 20;
  /** RegularExpression Id. */
  int TAKE = 21;
  /** RegularExpression Id. */
  int COMMIT = 22;
  /** RegularExpression Id. */
  int CANCEL = 23;
  /** RegularExpression Id. */
  int RESPONSE = 24;
  /** RegularExpression Id. */
  int ERROR = 25;
  /** RegularExpression Id. */
  int EXTENTNAME = 26;
  /** RegularExpression Id. */
  int MSG = 27;
  /** RegularExpression Id. */
  int CMD = 28;
  /** RegularExpression Id. */
  int TXN = 29;
  /** RegularExpression Id. */
  int USERNAME = 30;
  /** RegularExpression Id. */
  int PASSWORD = 31;
  /** RegularExpression Id. */
  int DURATION = 32;
  /** RegularExpression Id. */
  int TIMEOUT = 33;
  /** RegularExpression Id. */
  int CID = 34;
  /** RegularExpression Id. */
  int TXN_ID = 35;
  /** RegularExpression Id. */
  int LEASE_ID = 36;
  /** RegularExpression Id. */
  int SESSION_ID = 37;
  /** RegularExpression Id. */
  int NRESULTS = 38;
  /** RegularExpression Id. */
  int NENLISTED = 39;
  /** RegularExpression Id. */
  int NUMBER = 40;
  /** RegularExpression Id. */
  int DIGITS = 41;
  /** RegularExpression Id. */
  int NAME = 42;
  /** RegularExpression Id. */
  int STRING = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
    "\"+\"",
    "\"=\"",
    "\".\"",
    "\"cons\"",
    "\"car\"",
    "\"cdr\"",
    "\"dis\"",
    "\"connect\"",
    "\"write\"",
    "\"read\"",
    "\"take\"",
    "\"commit\"",
    "\"cancel\"",
    "\"response\"",
    "\"error\"",
    "\"extentname\"",
    "\"msg\"",
    "\"cmd\"",
    "\"txn\"",
    "\"username\"",
    "\"password\"",
    "\"dur\"",
    "\"timeout\"",
    "\"cid\"",
    "\"tid\"",
    "\"lid\"",
    "\"sid\"",
    "\"nresults\"",
    "\"enlisted\"",
    "<NUMBER>",
    "<DIGITS>",
    "<NAME>",
    "<STRING>",
  };

}
