/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <config.h>
#include <assert.h>
#include <string.h>
#include "json_msg_factory.h"
#include "DataObject.h"
#include "DataObjectList.h"
#include "SignalHandler.h"
#include "Oed_Dispatcher.h"
#include "Oe_Thread_Dispatcher.h"
#include "OeNet.h"
#include "OeNetDefaultFactory.h"
#include "OeStore.h"
#include "OeStoreDefaultFactory.h"
#include "OEKI.h"
#include "OEK.h"
#include "OepFactory.h"
#include "OepServer.h"
#include "OepClient.h"
#include "mem.h"
#include "arena.h"
#include "oe_common.h"
#include "Oec_Future.h"
#include "LoginModule.h"
#include "BuiltInLoginModule.h"
//#ifdef OE_USE_PAM
#include "PamLoginModule.h"
//#endif
#include "OeScript.h"

SWIGINTERN OesDataObject *new_OesDataObject(){
            Arena_T arena;
            arena = Arena_new();
            DataObject slist;
            slist = DataObject_new(arena);
            OesDataObject *holder;
            holder = Mem_calloc(1, sizeof(OesDataObject), "../OeScript.i", 96);
            holder->obj = slist;
            holder->arena = arena;
            holder->free_arena = true;
            return holder;
        }
SWIGINTERN void delete_OesDataObject(OesDataObject *self){
            if (self->arena && self->free_arena) {
                Arena_dispose(&self->arena);
            }
            Mem_free(self, "../OeScript.i", 106);
        }
SWIGINTERN int OesDataObject_get_nattrs(OesDataObject *self){
            return DataObject_get_nattrs(self->obj);
        }
SWIGINTERN void OesDataObject_add_attr(OesDataObject *self,char *entry){
            Arena_T arena;
            arena = self->arena;
            assert(arena);
            int len = strlen(entry);
            char *new_oejcl_str;
            new_oejcl_str = Arena_alloc(arena, len + 1, "../OeScript.i", 117);
            new_oejcl_str[len] = NULL;
            strncpy(new_oejcl_str, entry, len);
            DataObject_add_attr(self->obj, (oe_scalar) new_oejcl_str);
        }
SWIGINTERN void OesDataObject_set_nbytes(OesDataObject *self,size_t nbytes){
            DataObject_set_nbytes(self->obj, nbytes);
        }
SWIGINTERN int OesDataObject_get_nbytes(OesDataObject *self){
            return DataObject_get_nbytes(self->obj);
        }
SWIGINTERN OesIterator *OesDataObject_iter(OesDataObject *self){
            assert(self->obj);
            OesIterator *holder;
            holder = Mem_alloc(sizeof *holder, "../OeScript.i", 131);
            holder->obj = DataObject_iterator(self->obj, false);
            return holder;
        }
SWIGINTERN void OesDataObject_set_bytes(OesDataObject *self,char *bytes){
            int len =  DataObject_get_nbytes(self->obj);
            assert(len);
            Arena_T arena;
            arena = self->arena;
            char *new_oejcl_str;
            new_oejcl_str = Arena_alloc(arena, len + 1, "../OeScript.i", 141);
            new_oejcl_str[len] = NULL;
            memcpy(new_oejcl_str, bytes, len);
            DataObject_set_bytes(self->obj, new_oejcl_str);
        }
SWIGINTERN char *OesDataObject_get_bytes(OesDataObject *self){
            //use this for target langs that don't impl cstrings.i but
            //can marshall to a null terminated char* string 
            int len = DataObject_get_nbytes(self->obj);
            char *new_oejcl_str = Mem_alloc(len + 1, "../OeScript.i", 168);
            if (len) {
                char *entry = DataObject_get_bytes(self->obj);
                memcpy(new_oejcl_str, entry, len);
            }
            new_oejcl_str[len] = NULL;
            return new_oejcl_str;
        }
SWIGINTERN OesSigHandler *new_OesSigHandler(char const *filename,char const *appname,char const *loglvl){
            SignalHandler h;
            char *lfilename = Mem_alloc(strlen(filename) + 1, "../OeScript.i", 187);
            memcpy(lfilename, filename, strlen(filename) + 1);
            char *lloglvl = Mem_alloc(strlen(loglvl) + 1, "../OeScript.i", 189);
            memcpy(lloglvl, loglvl, strlen(loglvl) + 1);
            char *lappname = Mem_alloc(strlen(appname) + 1, "../OeScript.i", 191);
            memcpy(lappname, appname, strlen(appname) + 1);
            h = SignalHandler_new(lfilename, lappname, lloglvl);
            OesSigHandler *holder;
            holder = Mem_alloc(sizeof(OesSigHandler), "../OeScript.i", 195);
            holder->obj = h;
            return holder;
        }
SWIGINTERN void delete_OesSigHandler(OesSigHandler *self){
            SignalHandler_shutdown(self->obj);
            SignalHandler_free(&self->obj);
            Mem_free(self, "../OeScript.i", 202);
        }
SWIGINTERN void OesSigHandler_add__SWIG_0(OesSigHandler *self,OesDispatcher *manageme){
            SignalHandler_manage(self->obj, 
                                 Oed_Dispatcher_stop, 
                                 Oed_Dispatcher_free, 
                                 Oed_Dispatcher_stats, 
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_1(OesSigHandler *self,OesThreadDispatcher *manageme){
            SignalHandler_manage(self->obj, 
                                 Oe_Thread_Dispatcher_stop,
                                 Oe_Thread_Dispatcher_free,
                                 Oe_Thread_Dispatcher_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_2(OesSigHandler *self,OesStore *manageme){
            SignalHandler_manage(self->obj, 
                                 OeStore_stop,
                                 OeStore_free,
                                 OeStore_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_3(OesSigHandler *self,OesServer *manageme){
            SignalHandler_manage(self->obj, 
                                 NULL,
                                 OepServer_free,
                                 OepServer_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_4(OesSigHandler *self,OesKernel *manageme){
            SignalHandler_manage(self->obj, 
                                 OEK_stop, 
                                 OEK_free, 
                                 OEK_stats, 
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_5(OesSigHandler *self,OesNet *manageme){
            SignalHandler_manage(self->obj, 
                                 OeNet_stop,
                                 OeNet_free,
                                 OeNet_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN OesDispatcher *new_OesDispatcher(size_t nthreads,char const *name){
            OesDispatcher *holder;
            holder = Mem_calloc(1, sizeof(OesDispatcher), "../OeScript.i", 264);
            holder->obj = Oed_Dispatcher_new(nthreads, name);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesDispatcher(OesDispatcher *self){
            if (!self->managed) {
                Oed_Dispatcher_stop(self->obj);
                Oed_Dispatcher_free(&self->obj);
            }
            Mem_free(self, "../OeScript.i", 274);
        }
SWIGINTERN void OesDispatcher_start(OesDispatcher *self){
            Oed_Dispatcher_start(self->obj);
        }
SWIGINTERN OesThreadDispatcher *new_OesThreadDispatcher(size_t nthreads){
            OesThreadDispatcher *holder;
            holder = Mem_calloc(1, sizeof(OesThreadDispatcher), "../OeScript.i", 286);
            holder->obj = Oe_Thread_Dispatcher_new(nthreads);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesThreadDispatcher(OesThreadDispatcher *self){
            if (!self->managed) {
                Oe_Thread_Dispatcher_stop(self->obj);
                Oe_Thread_Dispatcher_free(&self->obj);
            }
            Mem_free(self, "../OeScript.i", 296);
        }
SWIGINTERN void OesThreadDispatcher_start(OesThreadDispatcher *self){
            Oe_Thread_Dispatcher_start(self->obj);
        }
SWIGINTERN OesStore *new_OesStore(int persist_level,char const *homedir,bool threaded){
            OesStore *holder;
            holder = Mem_calloc(1, sizeof(OesStore), "../OeScript.i", 308);
            holder->obj = OeStoreDefaultFactory_create(persist_level,
                                                       homedir, threaded);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesStore(OesStore *self){
            if (!self->managed) {
                OeStore_stop(self->obj);
                OeStore_free(&self->obj);
            }
            Mem_free(self, "../OeScript.i", 319);
        }
SWIGINTERN OesNet *new_OesNet(OesDispatcher *d,bool use_ssl,char *cert,char *pkey){
            OesNet *holder;
            holder = Mem_calloc(1, sizeof(OesNet), "../OeScript.i", 328);
            if (use_ssl) {
                holder->obj = OeNetDefaultSslFactory_create(d->obj, cert, pkey);
            } else {
                holder->obj = OeNetDefaultFactory_create(d->obj);
            }
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesNet(OesNet *self){
            if (!self->managed) {
                OeNet_stop(self->obj);
                OeNet_free(&self->obj);
            }
            Mem_free(self, "../OeScript.i", 342);
        }
SWIGINTERN void OesNet_setName(OesNet *self,char *name){
            OeNet_set_name(self->obj, (oe_scalar) name);
        }
SWIGINTERN char *OesNet_getName(OesNet *self){
            return (char *) OeNet_get_name(self->obj);
        }
SWIGINTERN void delete_OesLoginModule(OesLoginModule *self){
            if (!self->managed) {
                LoginModule_free(&self->obj);
            }
            Mem_free(self, "../OeScript.i", 359);
        }
SWIGINTERN OesBuiltInLoginModule *new_OesBuiltInLoginModule(){
            OesBuiltInLoginModule *holder;
            holder = Mem_calloc(1, sizeof(OesBuiltInLoginModule), "../OeScript.i", 368);
            holder->obj = BuiltInLoginModule_new();
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesBuiltInLoginModule(OesBuiltInLoginModule *self){
            //impl'll get cleaned up by LoginModule
            Mem_free(self, "../OeScript.i", 375);
        }
SWIGINTERN int OesBuiltInLoginModule_addAccount(OesBuiltInLoginModule *self,char *groupname,char *username,char *pwd){
            BuiltInLoginModule_add_account(self->obj, groupname, username, pwd);
            return 0;
        }
SWIGINTERN int OesBuiltInLoginModule_addPrivilege(OesBuiltInLoginModule *self,char *extentname,char *groupname,char *mtemplate){
            OekMsg msg = 0;
            int rc = json_msg_create(&msg, mtemplate,
                                     BuiltInLoginModule_get_arena(self->obj));
            if (rc) {
                //throw_exception(PARSE_PRIV_ERR);
                char *big_em = oec_str_concat(NULL, 2, PARSE_PRIV_ERR, mtemplate); //leaks
                throw_exception(big_em);
                return 1;
            }
            BuiltInLoginModule_add_privilege(self->obj, extentname, groupname, msg);
            return 0;
        }
SWIGINTERN OesLoginModule *OesBuiltInLoginModule_getModule(OesBuiltInLoginModule *self){
            OesLoginModule *holder;
            holder = Mem_alloc(sizeof *holder, "../OeScript.i", 396);
            holder->obj = BuiltInLoginModule_new_module(self->obj);
            return holder;
        }
SWIGINTERN OesPamLoginModule *new_OesPamLoginModule(char *pamdomain,char *defgroup){
            OesPamLoginModule *holder;
            holder = Mem_calloc(1, sizeof(OesPamLoginModule), "../OeScript.i", 408);
            holder->obj = PamLoginModule_new((oe_scalar) pamdomain, (oe_scalar) defgroup);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesPamLoginModule(OesPamLoginModule *self){
            //impl'll get cleaned up by LoginModule
            Mem_free(self, "../OeScript.i", 415);
        }
SWIGINTERN int OesPamLoginModule_addPrivilege(OesPamLoginModule *self,char *extentname,char *groupname,char *mtemplate){
            OekMsg msg = 0;
            int rc = json_msg_create(&msg, mtemplate,
                                     PamLoginModule_get_arena(self->obj));
            if (rc) {
                //throw_exception(PARSE_PRIV_PAM_ERR);
                char *big_em = oec_str_concat(NULL, 2, PARSE_PRIV_PAM_ERR, mtemplate); //leaks
                throw_exception(big_em);
                return 1;
            }
            PamLoginModule_add_privilege(self->obj, extentname, groupname, msg);
            return 0;
        }
SWIGINTERN OesLoginModule *OesPamLoginModule_getModule(OesPamLoginModule *self){
            OesLoginModule *holder;
            holder = Mem_alloc(sizeof *holder, "../OeScript.i", 438);
            holder->obj = PamLoginModule_new_module(self->obj);
            return holder;
        }
SWIGINTERN OesServer *new_OesServer(OesDispatcher *dispatcher,char *spec,OesNet *net,OesStore *store){
            OesServer *holder;
            holder = Mem_calloc(1, sizeof(OesServer), "../OeScript.i", 451);
            holder->obj = OepFactory_new_server(dispatcher->obj, spec, net->obj, store->obj);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesServer(OesServer *self){
            if (!self->managed) {
                OepServer_free(&self->obj);
            }
            Mem_free(self, "../OeScript.i", 460);
        }
SWIGINTERN void OesServer_addLoginModule(OesServer *self,OesLoginModule *m){
            OepServer_add_login_module(self->obj, m->obj);
        }
SWIGINTERN void OesServer_addKernel(OesServer *self,char *extentname,OesKernel *kernel){
            OepServer_add_kernel(self->obj, extentname, kernel->obj);
        }
SWIGINTERN OesDataObjectList *new_OesDataObjectList(){
            return OesKernel_impl_createOesDataObjectList(Arena_new(), NULL, NULL);
        }
SWIGINTERN void delete_OesDataObjectList(OesDataObjectList *self){
            if (self->f) {
                Oec_Future_free(&self->f);
            }
            if (self->arena) {
                Arena_dispose(&self->arena);
            }
            Mem_free(self, "../OeScript.i", 486);
        }
SWIGINTERN int OesDataObjectList_length(OesDataObjectList *self){
            if (self->f) {
                Oec_Future_get(self->f, OEC_FOREVER); //just to make sure it is done
            }
            return DataObjectList_length(self->obj);
        }
SWIGINTERN OesListIterator *OesDataObjectList_iter(OesDataObjectList *self){
            OesListIterator *holder;
            holder = Mem_alloc(sizeof *holder, "../OeScript.i", 496);
            holder->l = self->obj;
            holder->f = self->f;
            holder->obj = NULL;
            return holder;
        }
SWIGINTERN OesDataObject *OesDataObjectList_newDataObject(OesDataObjectList *self){
            if (self->f) {
                Oec_Future_get(self->f, OEC_FOREVER); //just to make sure it is done
            }
            OesDataObject *holder;
            holder = Mem_calloc(1, sizeof *holder, "../OeScript.i", 507);
            holder->obj = DataObjectList_new_data_object(self->obj);
            holder->arena = self->arena;
            return holder;
        }
SWIGINTERN void delete_OesIterator(OesIterator *self){
            Iterator_free(self->obj);
            Mem_free(self, "../OeScript.i", 519);
        }
SWIGINTERN char *OesIterator_nextItem(OesIterator *self){
            assert(self->obj);
            char *nl = Iterator_next(self->obj);
            if (nl == NULL) {
                return NULL;
            }
            int len = strlen(nl);
            char *newattr = Mem_alloc(len + 1, "../OeScript.i", 528);
            strncpy(newattr, nl, len);
            newattr[len] = NULL;
            return newattr;
        }
SWIGINTERN bool OesIterator_hasMore(OesIterator *self){
            assert(self->obj);
            return Iterator_hasMore(self->obj);
        }
SWIGINTERN void delete_OesListIterator(OesListIterator *self){
            if (self->obj) Iterator_free(self->obj);
            Mem_free(self, "../OeScript.i", 544);
        }
SWIGINTERN OesDataObject *OesListIterator_nextItem(OesListIterator *self){
            assert(self->l);
            if (self->f) Oec_Future_get(self->f, OEC_FOREVER);
            if (!self->obj) self->obj = DataObjectList_iterator(self->l, false);
            DataObject nl = Iterator_next(self->obj);
            if (nl == NULL) {
                return NULL;
            }
            OesDataObject *holder;
            holder = Mem_calloc(1, sizeof(OesDataObject), "../OeScript.i", 555);
            holder->obj = nl;
            return holder;
        }
SWIGINTERN bool OesListIterator_hasMore(OesListIterator *self){
            assert(self->l);
            if (self->f) Oec_Future_get(self->f, OEC_FOREVER);
            if (!self->obj) self->obj = DataObjectList_iterator(self->l, false);
            return Iterator_hasMore(self->obj);
        }
SWIGINTERN void delete_OesLease(OesLease *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            Oec_Future_free(&self->f);
            Mem_free(self, "../OeScript.i", 573);
        }
SWIGINTERN long OesLease_lid(OesLease *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            return self->lid;
        }
SWIGINTERN void OesLease_cancel(OesLease *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            OesKernel_impl_upl_cancel(self);
        }
SWIGINTERN void delete_OesTxn(OesTxn *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            Oec_CountdownLatch_free(self->enlisted);
            Oec_CountdownLatch_free(self->enlisted_counter);
            Oec_Future_free(&self->f);
            Mem_free(self, "../OeScript.i", 599);
        }
SWIGINTERN long OesTxn_tid(OesTxn *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            return self->tid;
        }
SWIGINTERN enum OES_TXN_STATUS OesTxn_status(OesTxn *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            return self->status;
        }
SWIGINTERN void OesTxn_commit(OesTxn *self){
            OesKernel_impl_commit(self);
        }
SWIGINTERN void OesTxn_rollback(OesTxn *self){
            OesKernel_impl_rollback(self);
        }
SWIGINTERN OesKernel *new_OesKernel(OesDispatcher *dispatcher,OesThreadDispatcher *tdispatcher,OesStore *store,char *netspec,OesNet *net,char *username,char *pwd){

            OesKernel *holder;
            holder = Mem_calloc(1, sizeof(OesKernel), "../OeScript.i", 631);
            if (!netspec || strlen(netspec) == 0) {
                assert(dispatcher);
                assert(tdispatcher);
                assert(store);
                holder->obj = OEK_default_factory_new(dispatcher->obj,
                                                      tdispatcher->obj, store->obj);
            } else {
                assert(dispatcher); assert(net); assert(username); assert(pwd); assert(netspec);
                OE_DLOG( NULL, "OeScript:OesKernel remote connect user %s to %s\n",
                         username, netspec); // i18n
                OepClient cl = OepFactory_new_client(netspec, 
                                                     dispatcher->obj, net->obj,
                                                     username, pwd);
                if (cl == NULL) {
                    throw_exception("can not connect"); //i18n
                    return NULL;
                }
                holder->obj = OepClient_new_kernel(cl);
            }
            return holder;
        }
SWIGINTERN void delete_OesKernel(OesKernel *self){
            if (!self->managed) {
                OEK_stop(self->obj);
                OEK_free(&self->obj);
            }
            /*
            OEK_stop(self->obj);
            if (self->shutdown_cb) {
                //the shutdown is done externally because the kernel isn't smart
                // enough to know the sequence of stopping itself and its own parts.
                // this is usually a ref to SignalHandler shutdown cmd.
                self->shutdown_cb(self->shutdown_cb_arg);
            } else {
                OEK_free(&self->obj);
            }
            */
            Mem_free(self, "../OeScript.i", 669);
        }
SWIGINTERN OesLease *OesKernel_write(OesKernel *self,OesDataObject *slist,long dur,bool is_tuple){
            return OesKernel_impl_write(self, slist, (oe_time) dur, is_tuple);
        }
SWIGINTERN OesTxn *OesKernel_begin(OesKernel *self,long dur){
            return OesKernel_impl_begin(self, (oe_time) dur);
        }
SWIGINTERN void OesKernel_setCurrent(OesKernel *self,OesTxn *txn_holder){
            self->currentTxn = txn_holder;
        }
SWIGINTERN OesDataObjectList *OesKernel_read(OesKernel *self,OesDataObjectList *data,long timeout,bool is_tuple,int max_responses,bool return_attrs,bool return_bytes){
            return OesKernel_impl_read(self, data, (oe_time) timeout,
                                       is_tuple, max_responses,
                                       return_attrs, return_bytes);
        }
SWIGINTERN OesDataObjectList *OesKernel_take(OesKernel *self,OesDataObjectList *data,long timeout,bool is_tuple,int max_responses,bool return_attrs,bool return_bytes){
            return OesKernel_impl_take(self, data, (oe_time) timeout,
                                       is_tuple, max_responses,
                                       return_attrs, return_bytes);
        }
SWIGINTERN OesJsonKernel *new_OesJsonKernel(OesKernel *kernel){

            OesJsonKernel *holder;
            holder = Mem_calloc(1, sizeof(OesJsonKernel), "../OeScript.i", 715);
            holder->obj = JsonKernel_new(kernel->obj);
            return holder;
        }
SWIGINTERN void delete_OesJsonKernel(OesJsonKernel *self){
            if (!self->managed) {
                JsonKernel_free(&self->obj);
            }
            Mem_free(self, "../OeScript.i", 723);
        }
SWIGINTERN OesFuture *OesJsonKernel_exec(OesJsonKernel *self,char *json){

            Oec_Future f = Oec_Future_new();

            JsonKernel_exec(self->obj, json, OesKernel_impl_json_promise, f);

            OesFuture *folder;
            folder = Mem_calloc(1, sizeof(OesFuture), "../OeScript.i", 733);
            folder->obj = f;
            return folder;
        }
SWIGINTERN void delete_OesFuture(OesFuture *self){
            Oec_Future_free(&self->obj);
            Mem_free(self, "../OeScript.i", 744);
        }
SWIGINTERN char *OesFuture_getString(OesFuture *self,long timeout){

            Oec_Future f = self->obj;

            return (char *) Oec_Future_get(f, timeout);
        }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesDataObject(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesDataObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObject *)new_OesDataObject();
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesDataObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesDataObject **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesDataObject(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObject_1get_1nattrs(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObject **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesDataObject_get_nattrs(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObject_1add_1attr(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObject **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    oe_scalar err;
    clear_exception();
    OesDataObject_add_attr(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObject_1set_1nbytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObject **)&jarg1; 
  arg2 = (size_t)jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesDataObject_set_nbytes(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObject_1get_1nbytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObject **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesDataObject_get_nbytes(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObject_1iter(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  OesIterator *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObject **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesIterator *)OesDataObject_iter(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesIterator **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObject_1set_1bytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObject **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    oe_scalar err;
    clear_exception();
    OesDataObject_set_bytes(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObject_1get_1bytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObject **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesDataObject_get_bytes(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesSigHandler(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  OesSigHandler *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (OesSigHandler *)new_OesSigHandler((char const *)arg1,(char const *)arg2,(char const *)arg3);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesSigHandler **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesSigHandler(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesSigHandler **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesSigHandler(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesSigHandler_1add_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesDispatcher *arg2 = (OesDispatcher *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesSigHandler **)&jarg1; 
  arg2 = *(OesDispatcher **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_0(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesSigHandler_1add_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesThreadDispatcher *arg2 = (OesThreadDispatcher *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesSigHandler **)&jarg1; 
  arg2 = *(OesThreadDispatcher **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_1(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesSigHandler_1add_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesStore *arg2 = (OesStore *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesSigHandler **)&jarg1; 
  arg2 = *(OesStore **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_2(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesSigHandler_1add_1_1SWIG_13(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesServer *arg2 = (OesServer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesSigHandler **)&jarg1; 
  arg2 = *(OesServer **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_3(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesSigHandler_1add_1_1SWIG_14(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesKernel *arg2 = (OesKernel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesSigHandler **)&jarg1; 
  arg2 = *(OesKernel **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_4(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesSigHandler_1add_1_1SWIG_15(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesNet *arg2 = (OesNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesSigHandler **)&jarg1; 
  arg2 = *(OesNet **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_5(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesDispatcher(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  size_t arg1 ;
  char *arg2 = (char *) 0 ;
  OesDispatcher *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (OesDispatcher *)new_OesDispatcher(arg1,(char const *)arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDispatcher **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesDispatcher(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesDispatcher **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesDispatcher(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDispatcher_1start(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDispatcher **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    OesDispatcher_start(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesThreadDispatcher(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  OesThreadDispatcher *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesThreadDispatcher *)new_OesThreadDispatcher(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesThreadDispatcher **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesThreadDispatcher(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesThreadDispatcher *arg1 = (OesThreadDispatcher *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesThreadDispatcher **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesThreadDispatcher(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesThreadDispatcher_1start(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  OesThreadDispatcher *arg1 = (OesThreadDispatcher *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesThreadDispatcher **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    OesThreadDispatcher_start(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesStore(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2, jboolean jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  OesStore *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = jarg3 ? true : false; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesStore *)new_OesStore(arg1,(char const *)arg2,arg3);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesStore **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesStore(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesStore *arg1 = (OesStore *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesStore **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesStore(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesNet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2, jstring jarg3, jstring jarg4) {
  jlong jresult = 0 ;
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  bool arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  OesNet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDispatcher **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (OesNet *)new_OesNet(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesNet **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesNet(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesNet *arg1 = (OesNet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesNet **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesNet(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesNet_1setName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OesNet *arg1 = (OesNet *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesNet **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    oe_scalar err;
    clear_exception();
    OesNet_setName(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesNet_1getName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OesNet *arg1 = (OesNet *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesNet **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesNet_getName(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesLoginModule(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesLoginModule *arg1 = (OesLoginModule *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesLoginModule **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesLoginModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesLoginModule(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesLoginModule *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesLoginModule *)calloc(1, sizeof(OesLoginModule));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLoginModule **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesBuiltInLoginModule(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesBuiltInLoginModule *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesBuiltInLoginModule *)new_OesBuiltInLoginModule();
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesBuiltInLoginModule **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesBuiltInLoginModule(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesBuiltInLoginModule **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesBuiltInLoginModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesBuiltInLoginModule_1addAccount(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4) {
  jint jresult = 0 ;
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesBuiltInLoginModule **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesBuiltInLoginModule_addAccount(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesBuiltInLoginModule_1addPrivilege(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4) {
  jint jresult = 0 ;
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesBuiltInLoginModule **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesBuiltInLoginModule_addPrivilege(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesBuiltInLoginModule_1getModule(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  OesLoginModule *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesBuiltInLoginModule **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesLoginModule *)OesBuiltInLoginModule_getModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLoginModule **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesPamLoginModule(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  OesPamLoginModule *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (OesPamLoginModule *)new_OesPamLoginModule(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesPamLoginModule **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesPamLoginModule(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesPamLoginModule *arg1 = (OesPamLoginModule *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesPamLoginModule **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesPamLoginModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesPamLoginModule_1addPrivilege(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4) {
  jint jresult = 0 ;
  OesPamLoginModule *arg1 = (OesPamLoginModule *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesPamLoginModule **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesPamLoginModule_addPrivilege(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesPamLoginModule_1getModule(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  OesPamLoginModule *arg1 = (OesPamLoginModule *) 0 ;
  OesLoginModule *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesPamLoginModule **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesLoginModule *)OesPamLoginModule_getModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLoginModule **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesServer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jobject jarg3_, jlong jarg4, jobject jarg4_) {
  jlong jresult = 0 ;
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  char *arg2 = (char *) 0 ;
  OesNet *arg3 = (OesNet *) 0 ;
  OesStore *arg4 = (OesStore *) 0 ;
  OesServer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  (void)jarg4_;
  arg1 = *(OesDispatcher **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(OesNet **)&jarg3; 
  arg4 = *(OesStore **)&jarg4; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesServer *)new_OesServer(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesServer **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesServer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesServer *arg1 = (OesServer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesServer **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesServer(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesServer_1addLoginModule(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesServer *arg1 = (OesServer *) 0 ;
  OesLoginModule *arg2 = (OesLoginModule *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesServer **)&jarg1; 
  arg2 = *(OesLoginModule **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesServer_addLoginModule(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesServer_1addKernel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jobject jarg3_) {
  OesServer *arg1 = (OesServer *) 0 ;
  char *arg2 = (char *) 0 ;
  OesKernel *arg3 = (OesKernel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(OesServer **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = *(OesKernel **)&jarg3; 
  {
    oe_scalar err;
    clear_exception();
    OesServer_addKernel(arg1,arg2,arg3);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesDataObjectList(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesDataObjectList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObjectList *)new_OesDataObjectList();
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObjectList **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesDataObjectList(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesDataObjectList **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesDataObjectList(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObjectList_1length(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObjectList **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesDataObjectList_length(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObjectList_1iter(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  OesListIterator *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObjectList **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesListIterator *)OesDataObjectList_iter(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesListIterator **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesDataObjectList_1newDataObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  OesDataObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesDataObjectList **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObject *)OesDataObjectList_newDataObject(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesIterator(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesIterator *arg1 = (OesIterator *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesIterator **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesIterator(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jstring JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesIterator_1nextItem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OesIterator *arg1 = (OesIterator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesIterator **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesIterator_nextItem(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesIterator_1hasMore(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  OesIterator *arg1 = (OesIterator *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesIterator **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (bool)OesIterator_hasMore(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesIterator(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesIterator *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesIterator *)calloc(1, sizeof(OesIterator));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesIterator **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesListIterator(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesListIterator *arg1 = (OesListIterator *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesListIterator **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesListIterator(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesListIterator_1nextItem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  OesListIterator *arg1 = (OesListIterator *) 0 ;
  OesDataObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesListIterator **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObject *)OesListIterator_nextItem(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesListIterator_1hasMore(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  OesListIterator *arg1 = (OesListIterator *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesListIterator **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (bool)OesListIterator_hasMore(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesListIterator(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesListIterator *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesListIterator *)calloc(1, sizeof(OesListIterator));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesListIterator **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesLease(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesLease *arg1 = (OesLease *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesLease **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesLease(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesLease_1lid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  OesLease *arg1 = (OesLease *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesLease **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (long)OesLease_lid(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesLease_1cancel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  OesLease *arg1 = (OesLease *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesLease **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    OesLease_cancel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesLease(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesLease *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesLease *)calloc(1, sizeof(OesLease));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLease **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesTxn(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesTxn *arg1 = (OesTxn *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesTxn **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesTxn(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesTxn_1tid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  OesTxn *arg1 = (OesTxn *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesTxn **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (long)OesTxn_tid(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesTxn_1status(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  OesTxn *arg1 = (OesTxn *) 0 ;
  enum OES_TXN_STATUS result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesTxn **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (enum OES_TXN_STATUS)OesTxn_status(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesTxn_1commit(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  OesTxn *arg1 = (OesTxn *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesTxn **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    OesTxn_commit(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesTxn_1rollback(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  OesTxn *arg1 = (OesTxn *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesTxn **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    OesTxn_rollback(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesTxn(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesTxn *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesTxn *)calloc(1, sizeof(OesTxn));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesTxn **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesKernel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jobject jarg3_, jstring jarg4, jlong jarg5, jobject jarg5_, jstring jarg6, jstring jarg7) {
  jlong jresult = 0 ;
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  OesThreadDispatcher *arg2 = (OesThreadDispatcher *) 0 ;
  OesStore *arg3 = (OesStore *) 0 ;
  char *arg4 = (char *) 0 ;
  OesNet *arg5 = (OesNet *) 0 ;
  char *arg6 = (char *) 0 ;
  char *arg7 = (char *) 0 ;
  OesKernel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg3_;
  (void)jarg5_;
  arg1 = *(OesDispatcher **)&jarg1; 
  arg2 = *(OesThreadDispatcher **)&jarg2; 
  arg3 = *(OesStore **)&jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = *(OesNet **)&jarg5; 
  arg6 = 0;
  if (jarg6) {
    arg6 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0);
    if (!arg6) return 0;
  }
  arg7 = 0;
  if (jarg7) {
    arg7 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg7, 0);
    if (!arg7) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (OesKernel *)new_OesKernel(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesKernel **)&jresult = result; 
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  if (arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, (const char *)arg6);
  if (arg7) (*jenv)->ReleaseStringUTFChars(jenv, jarg7, (const char *)arg7);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesKernel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesKernel *arg1 = (OesKernel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesKernel **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesKernel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesKernel_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jboolean jarg4) {
  jlong jresult = 0 ;
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesDataObject *arg2 = (OesDataObject *) 0 ;
  long arg3 ;
  bool arg4 ;
  OesLease *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesKernel **)&jarg1; 
  arg2 = *(OesDataObject **)&jarg2; 
  arg3 = (long)jarg3; 
  arg4 = jarg4 ? true : false; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesLease *)OesKernel_write(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLease **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesKernel_1begin(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  OesKernel *arg1 = (OesKernel *) 0 ;
  long arg2 ;
  OesTxn *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesKernel **)&jarg1; 
  arg2 = (long)jarg2; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesTxn *)OesKernel_begin(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesTxn **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesKernel_1setCurrent(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesTxn *arg2 = (OesTxn *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesKernel **)&jarg1; 
  arg2 = *(OesTxn **)&jarg2; 
  {
    oe_scalar err;
    clear_exception();
    OesKernel_setCurrent(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesKernel_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jboolean jarg4, jint jarg5, jboolean jarg6, jboolean jarg7) {
  jlong jresult = 0 ;
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesDataObjectList *arg2 = (OesDataObjectList *) 0 ;
  long arg3 ;
  bool arg4 ;
  int arg5 ;
  bool arg6 ;
  bool arg7 ;
  OesDataObjectList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesKernel **)&jarg1; 
  arg2 = *(OesDataObjectList **)&jarg2; 
  arg3 = (long)jarg3; 
  arg4 = jarg4 ? true : false; 
  arg5 = (int)jarg5; 
  arg6 = jarg6 ? true : false; 
  arg7 = jarg7 ? true : false; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObjectList *)OesKernel_read(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObjectList **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesKernel_1take(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jboolean jarg4, jint jarg5, jboolean jarg6, jboolean jarg7) {
  jlong jresult = 0 ;
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesDataObjectList *arg2 = (OesDataObjectList *) 0 ;
  long arg3 ;
  bool arg4 ;
  int arg5 ;
  bool arg6 ;
  bool arg7 ;
  OesDataObjectList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OesKernel **)&jarg1; 
  arg2 = *(OesDataObjectList **)&jarg2; 
  arg3 = (long)jarg3; 
  arg4 = jarg4 ? true : false; 
  arg5 = (int)jarg5; 
  arg6 = jarg6 ? true : false; 
  arg7 = jarg7 ? true : false; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObjectList *)OesKernel_take(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObjectList **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesJsonKernel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesJsonKernel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesKernel **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    result = (OesJsonKernel *)new_OesJsonKernel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesJsonKernel **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesJsonKernel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesJsonKernel *arg1 = (OesJsonKernel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesJsonKernel **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesJsonKernel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesJsonKernel_1exec(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  OesJsonKernel *arg1 = (OesJsonKernel *) 0 ;
  char *arg2 = (char *) 0 ;
  OesFuture *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesJsonKernel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  {
    oe_scalar err;
    clear_exception();
    result = (OesFuture *)OesJsonKernel_exec(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesFuture **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_oescript_java_swig_oescriptimplJNI_delete_1OesFuture(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OesFuture *arg1 = (OesFuture *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OesFuture **)&jarg1; 
  {
    oe_scalar err;
    clear_exception();
    delete_OesFuture(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
}


SWIGEXPORT jstring JNICALL Java_org_oescript_java_swig_oescriptimplJNI_OesFuture_1getString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jstring jresult = 0 ;
  OesFuture *arg1 = (OesFuture *) 0 ;
  long arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OesFuture **)&jarg1; 
  arg2 = (long)jarg2; 
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesFuture_getString(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_oescript_java_swig_oescriptimplJNI_new_1OesFuture(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OesFuture *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    oe_scalar err;
    clear_exception();
    result = (OesFuture *)calloc(1, sizeof(OesFuture));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesFuture **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

