/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_OESCRIPTIMPL_H
#define PHP_OESCRIPTIMPL_H

extern zend_module_entry oescriptimpl_module_entry;
#define phpext_oescriptimpl_ptr &oescriptimpl_module_entry

#ifdef PHP_WIN32
# define PHP_OESCRIPTIMPL_API __declspec(dllexport)
#else
# define PHP_OESCRIPTIMPL_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(oescriptimpl);
PHP_MSHUTDOWN_FUNCTION(oescriptimpl);
PHP_RINIT_FUNCTION(oescriptimpl);
PHP_RSHUTDOWN_FUNCTION(oescriptimpl);
PHP_MINFO_FUNCTION(oescriptimpl);

ZEND_NAMED_FUNCTION(_wrap_new_OesDataObject);
ZEND_NAMED_FUNCTION(_wrap_OesDataObject_get_nattrs);
ZEND_NAMED_FUNCTION(_wrap_OesDataObject_add_attr);
ZEND_NAMED_FUNCTION(_wrap_OesDataObject_set_nbytes);
ZEND_NAMED_FUNCTION(_wrap_OesDataObject_get_nbytes);
ZEND_NAMED_FUNCTION(_wrap_OesDataObject_iter);
ZEND_NAMED_FUNCTION(_wrap_OesDataObject_set_bytes);
ZEND_NAMED_FUNCTION(_wrap_OesDataObject_get_bytes);
ZEND_NAMED_FUNCTION(_wrap_new_OesSigHandler);
ZEND_NAMED_FUNCTION(_wrap_OesSigHandler_add);
ZEND_NAMED_FUNCTION(_wrap_new_OesDispatcher);
ZEND_NAMED_FUNCTION(_wrap_OesDispatcher_start);
ZEND_NAMED_FUNCTION(_wrap_new_OesThreadDispatcher);
ZEND_NAMED_FUNCTION(_wrap_OesThreadDispatcher_start);
ZEND_NAMED_FUNCTION(_wrap_new_OesStore);
ZEND_NAMED_FUNCTION(_wrap_new_OesNet);
ZEND_NAMED_FUNCTION(_wrap_OesNet_setName);
ZEND_NAMED_FUNCTION(_wrap_OesNet_getName);
ZEND_NAMED_FUNCTION(_wrap_new_OesLoginModule);
ZEND_NAMED_FUNCTION(_wrap_new_OesBuiltInLoginModule);
ZEND_NAMED_FUNCTION(_wrap_OesBuiltInLoginModule_addAccount);
ZEND_NAMED_FUNCTION(_wrap_OesBuiltInLoginModule_addPrivilege);
ZEND_NAMED_FUNCTION(_wrap_OesBuiltInLoginModule_getModule);
ZEND_NAMED_FUNCTION(_wrap_new_OesPamLoginModule);
ZEND_NAMED_FUNCTION(_wrap_OesPamLoginModule_addPrivilege);
ZEND_NAMED_FUNCTION(_wrap_OesPamLoginModule_getModule);
ZEND_NAMED_FUNCTION(_wrap_new_OesServer);
ZEND_NAMED_FUNCTION(_wrap_OesServer_addLoginModule);
ZEND_NAMED_FUNCTION(_wrap_OesServer_addKernel);
ZEND_NAMED_FUNCTION(_wrap_new_OesDataObjectList);
ZEND_NAMED_FUNCTION(_wrap_OesDataObjectList_length);
ZEND_NAMED_FUNCTION(_wrap_OesDataObjectList_iter);
ZEND_NAMED_FUNCTION(_wrap_OesDataObjectList_newDataObject);
ZEND_NAMED_FUNCTION(_wrap_OesIterator_nextItem);
ZEND_NAMED_FUNCTION(_wrap_OesIterator_hasMore);
ZEND_NAMED_FUNCTION(_wrap_new_OesIterator);
ZEND_NAMED_FUNCTION(_wrap_OesListIterator_nextItem);
ZEND_NAMED_FUNCTION(_wrap_OesListIterator_hasMore);
ZEND_NAMED_FUNCTION(_wrap_new_OesListIterator);
ZEND_NAMED_FUNCTION(_wrap_OesLease_lid);
ZEND_NAMED_FUNCTION(_wrap_OesLease_cancel);
ZEND_NAMED_FUNCTION(_wrap_new_OesLease);
ZEND_NAMED_FUNCTION(_wrap_OesTxn_tid);
ZEND_NAMED_FUNCTION(_wrap_OesTxn_status);
ZEND_NAMED_FUNCTION(_wrap_OesTxn_commit);
ZEND_NAMED_FUNCTION(_wrap_OesTxn_rollback);
ZEND_NAMED_FUNCTION(_wrap_new_OesTxn);
ZEND_NAMED_FUNCTION(_wrap_new_OesKernel);
ZEND_NAMED_FUNCTION(_wrap_OesKernel_write);
ZEND_NAMED_FUNCTION(_wrap_OesKernel_begin);
ZEND_NAMED_FUNCTION(_wrap_OesKernel_setCurrent);
ZEND_NAMED_FUNCTION(_wrap_OesKernel_read);
ZEND_NAMED_FUNCTION(_wrap_OesKernel_take);
ZEND_NAMED_FUNCTION(_wrap_new_OesJsonKernel);
ZEND_NAMED_FUNCTION(_wrap_OesJsonKernel_exec);
ZEND_NAMED_FUNCTION(_wrap_OesFuture_getString);
ZEND_NAMED_FUNCTION(_wrap_new_OesFuture);
#endif /* PHP_OESCRIPTIMPL_H */
