# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -I../../../../../corelib -Wall -r -o ./OeScript_R_wrap.c ../../OeScript.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = RSWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  assign(defName,  .values,  envir = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################


setClass('_p_OesDataObject', contains = 'ExternalReference')
setClass("OesDataObject",
    representation(
),
        contains = "RSWIGStruct")


# End class OesDataObject

setClass('_p_OesSigHandler', contains = 'ExternalReference')
setClass("OesSigHandler",
    representation(
),
        contains = "RSWIGStruct")


# End class OesSigHandler

setClass('_p_OesDispatcher', contains = 'ExternalReference')
setClass("OesDispatcher",
    representation(
),
        contains = "RSWIGStruct")


# End class OesDispatcher

setClass('_p_OesThreadDispatcher', contains = 'ExternalReference')
setClass("OesThreadDispatcher",
    representation(
),
        contains = "RSWIGStruct")


# End class OesThreadDispatcher

setClass('_p_OesStore', contains = 'ExternalReference')
setClass("OesStore",
    representation(
),
        contains = "RSWIGStruct")


# End class OesStore

setClass('_p_OesNet', contains = 'ExternalReference')
setClass("OesNet",
    representation(
),
        contains = "RSWIGStruct")


# End class OesNet

setClass('_p_OesLoginModule', contains = 'ExternalReference')
setClass("OesLoginModule",
    representation(
),
        contains = "RSWIGStruct")


# End class OesLoginModule

setClass('_p_OesBuiltInLoginModule', contains = 'ExternalReference')
setClass("OesBuiltInLoginModule",
    representation(
),
        contains = "RSWIGStruct")


# End class OesBuiltInLoginModule

setClass('_p_OesPamLoginModule', contains = 'ExternalReference')
setClass("OesPamLoginModule",
    representation(
),
        contains = "RSWIGStruct")


# End class OesPamLoginModule

setClass('_p_OesServer', contains = 'ExternalReference')
setClass("OesServer",
    representation(
),
        contains = "RSWIGStruct")


# End class OesServer

setClass('_p_OesDataObjectList', contains = 'ExternalReference')
setClass("OesDataObjectList",
    representation(
),
        contains = "RSWIGStruct")


# End class OesDataObjectList

setClass('_p_OesIterator', contains = 'ExternalReference')
setClass("OesIterator",
    representation(
),
        contains = "RSWIGStruct")


# End class OesIterator

setClass('_p_OesListIterator', contains = 'ExternalReference')
setClass("OesListIterator",
    representation(
),
        contains = "RSWIGStruct")


# End class OesListIterator

setClass('_p_OesLease', contains = 'ExternalReference')
setClass("OesLease",
    representation(
),
        contains = "RSWIGStruct")


# End class OesLease

setClass('_p_OesTxn', contains = 'ExternalReference')
setClass("OesTxn",
    representation(
),
        contains = "RSWIGStruct")


# End class OesTxn

setClass('_p_OesKernel', contains = 'ExternalReference')
setClass("OesKernel",
    representation(
),
        contains = "RSWIGStruct")


# End class OesKernel

setClass('_p_OesJsonKernel', contains = 'ExternalReference')
setClass("OesJsonKernel",
    representation(
),
        contains = "RSWIGStruct")


# End class OesJsonKernel

setClass('_p_OesFuture', contains = 'ExternalReference')
setClass("OesFuture",
    representation(
),
        contains = "RSWIGStruct")


# End class OesFuture




setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})

defineEnumeration('_OES_TXN_STATUS',
                    .values = c(
                        'ACTIVE' = 0, 
                        'ROLLEDBACK' = 1, 
                        'COMMITTED' = 2
))
# Start of new_OesDataObject

`OesDataObject` = function()
{
  ;ans = .Call('R_swig_new_OesDataObject', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesDataObject";
  
  reg.finalizer(ans, delete_OesDataObject)
  ans
  
}

attr(`OesDataObject`, 'returnType') = '_p_OesDataObject'
class(`OesDataObject`) = c("SWIGFunction", class('OesDataObject'))

# Start of delete_OesDataObject

`delete_OesDataObject` = function(self)
{
  ;.Call('R_swig_delete_OesDataObject', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesDataObject`, 'returnType') = 'void'
attr(`delete_OesDataObject`, "inputTypes") = c('_p_OesDataObject')
class(`delete_OesDataObject`) = c("SWIGFunction", class('delete_OesDataObject'))

# Start of OesDataObject_get_nattrs

`OesDataObject_get_nattrs` = function(self, .copy = FALSE)
{
  ;.Call('R_swig_OesDataObject_get_nattrs', self, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesDataObject_get_nattrs`, 'returnType') = 'integer'
attr(`OesDataObject_get_nattrs`, "inputTypes") = c('_p_OesDataObject')
class(`OesDataObject_get_nattrs`) = c("SWIGFunction", class('OesDataObject_get_nattrs'))

# Start of OesDataObject_add_attr

`OesDataObject_add_attr` = function(self, entry)
{
  entry = as(entry, "character"); 
  ;.Call('R_swig_OesDataObject_add_attr', self, entry, PACKAGE='oescriptimpl');
  
}

attr(`OesDataObject_add_attr`, 'returnType') = 'void'
attr(`OesDataObject_add_attr`, "inputTypes") = c('_p_OesDataObject', 'character')
class(`OesDataObject_add_attr`) = c("SWIGFunction", class('OesDataObject_add_attr'))

# Start of OesDataObject_set_nbytes

`OesDataObject_set_nbytes` = function(self, nbytes)
{
  if(length(nbytes) > 1) {
    warning("using only the first element of nbytes");
  };
  
  ;.Call('R_swig_OesDataObject_set_nbytes', self, nbytes, PACKAGE='oescriptimpl');
  
}

attr(`OesDataObject_set_nbytes`, 'returnType') = 'void'
attr(`OesDataObject_set_nbytes`, "inputTypes") = c('_p_OesDataObject', 'integer')
class(`OesDataObject_set_nbytes`) = c("SWIGFunction", class('OesDataObject_set_nbytes'))

# Start of OesDataObject_get_nbytes

`OesDataObject_get_nbytes` = function(self, .copy = FALSE)
{
  ;.Call('R_swig_OesDataObject_get_nbytes', self, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesDataObject_get_nbytes`, 'returnType') = 'integer'
attr(`OesDataObject_get_nbytes`, "inputTypes") = c('_p_OesDataObject')
class(`OesDataObject_get_nbytes`) = c("SWIGFunction", class('OesDataObject_get_nbytes'))

# Start of OesDataObject_iter

`OesDataObject_iter` = function(self)
{
  ;ans = .Call('R_swig_OesDataObject_iter', self, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesIterator";
  
  ans
  
}

attr(`OesDataObject_iter`, 'returnType') = '_p_OesIterator'
attr(`OesDataObject_iter`, "inputTypes") = c('_p_OesDataObject')
class(`OesDataObject_iter`) = c("SWIGFunction", class('OesDataObject_iter'))

# Start of OesDataObject_set_bytes

`OesDataObject_set_bytes` = function(self, bytes)
{
  bytes = as(bytes, "character"); 
  ;.Call('R_swig_OesDataObject_set_bytes', self, bytes, PACKAGE='oescriptimpl');
  
}

attr(`OesDataObject_set_bytes`, 'returnType') = 'void'
attr(`OesDataObject_set_bytes`, "inputTypes") = c('_p_OesDataObject', 'character')
class(`OesDataObject_set_bytes`) = c("SWIGFunction", class('OesDataObject_set_bytes'))

# Start of OesDataObject_get_bytes

`OesDataObject_get_bytes` = function(self)
{
  ;.Call('R_swig_OesDataObject_get_bytes', self, PACKAGE='oescriptimpl');
  
}

attr(`OesDataObject_get_bytes`, 'returnType') = 'character'
attr(`OesDataObject_get_bytes`, "inputTypes") = c('_p_OesDataObject')
class(`OesDataObject_get_bytes`) = c("SWIGFunction", class('OesDataObject_get_bytes'))

# Start of accessor method for OesDataObject
setMethod('$', '_p_OesDataObject', function(x, name)

{
  accessorFuns = list('get_nattrs' = OesDataObject_get_nattrs, 'add_attr' = OesDataObject_add_attr, 'set_nbytes' = OesDataObject_set_nbytes, 'get_nbytes' = OesDataObject_get_nbytes, 'iter' = OesDataObject_iter, 'set_bytes' = OesDataObject_set_bytes, 'get_bytes' = OesDataObject_get_bytes);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesDataObject
setMethod('delete', '_p_OesDataObject', function(obj) {delete_OesDataObject(obj)})
# Start definition of copy functions & methods for OesDataObject
CopyToR_OesDataObject = function(value, obj = new("OesDataObject"))
{
  obj;
}



CopyToC_OesDataObject = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesDataObject
setMethod('copyToR', '_p_OesDataObject', CopyToR_OesDataObject);
setMethod('copyToC', 'OesDataObject', CopyToC_OesDataObject);

# End definition of copy methods for OesDataObject
# End definition of copy functions & methods for OesDataObject
# Start of new_OesSigHandler

`OesSigHandler` = function(filename, appname, loglvl)
{
  filename = as(filename, "character"); 
  appname = as(appname, "character"); 
  loglvl = as(loglvl, "character"); 
  ;ans = .Call('R_swig_new_OesSigHandler', filename, appname, loglvl, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesSigHandler";
  
  reg.finalizer(ans, delete_OesSigHandler)
  ans
  
}

attr(`OesSigHandler`, 'returnType') = '_p_OesSigHandler'
attr(`OesSigHandler`, "inputTypes") = c('character', 'character', 'character')
class(`OesSigHandler`) = c("SWIGFunction", class('OesSigHandler'))

# Start of delete_OesSigHandler

`delete_OesSigHandler` = function(self)
{
  ;.Call('R_swig_delete_OesSigHandler', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesSigHandler`, 'returnType') = 'void'
attr(`delete_OesSigHandler`, "inputTypes") = c('_p_OesSigHandler')
class(`delete_OesSigHandler`) = c("SWIGFunction", class('delete_OesSigHandler'))

# Start of OesSigHandler_add

`OesSigHandler_add__SWIG_0` = function(self, manageme)
{
  ;.Call('R_swig_OesSigHandler_add__SWIG_0', self, manageme, PACKAGE='oescriptimpl');
  
}

attr(`OesSigHandler_add__SWIG_0`, 'returnType') = 'void'
attr(`OesSigHandler_add__SWIG_0`, "inputTypes") = c('_p_OesSigHandler', '_p_OesDispatcher')
class(`OesSigHandler_add__SWIG_0`) = c("SWIGFunction", class('OesSigHandler_add__SWIG_0'))

# Start of OesSigHandler_add

`OesSigHandler_add__SWIG_1` = function(self, manageme)
{
  ;.Call('R_swig_OesSigHandler_add__SWIG_1', self, manageme, PACKAGE='oescriptimpl');
  
}

attr(`OesSigHandler_add__SWIG_1`, 'returnType') = 'void'
attr(`OesSigHandler_add__SWIG_1`, "inputTypes") = c('_p_OesSigHandler', '_p_OesThreadDispatcher')
class(`OesSigHandler_add__SWIG_1`) = c("SWIGFunction", class('OesSigHandler_add__SWIG_1'))

# Start of OesSigHandler_add

`OesSigHandler_add__SWIG_2` = function(self, manageme)
{
  ;.Call('R_swig_OesSigHandler_add__SWIG_2', self, manageme, PACKAGE='oescriptimpl');
  
}

attr(`OesSigHandler_add__SWIG_2`, 'returnType') = 'void'
attr(`OesSigHandler_add__SWIG_2`, "inputTypes") = c('_p_OesSigHandler', '_p_OesStore')
class(`OesSigHandler_add__SWIG_2`) = c("SWIGFunction", class('OesSigHandler_add__SWIG_2'))

# Start of OesSigHandler_add

`OesSigHandler_add__SWIG_3` = function(self, manageme)
{
  ;.Call('R_swig_OesSigHandler_add__SWIG_3', self, manageme, PACKAGE='oescriptimpl');
  
}

attr(`OesSigHandler_add__SWIG_3`, 'returnType') = 'void'
attr(`OesSigHandler_add__SWIG_3`, "inputTypes") = c('_p_OesSigHandler', '_p_OesServer')
class(`OesSigHandler_add__SWIG_3`) = c("SWIGFunction", class('OesSigHandler_add__SWIG_3'))

# Start of OesSigHandler_add

`OesSigHandler_add__SWIG_4` = function(self, manageme)
{
  ;.Call('R_swig_OesSigHandler_add__SWIG_4', self, manageme, PACKAGE='oescriptimpl');
  
}

attr(`OesSigHandler_add__SWIG_4`, 'returnType') = 'void'
attr(`OesSigHandler_add__SWIG_4`, "inputTypes") = c('_p_OesSigHandler', '_p_OesKernel')
class(`OesSigHandler_add__SWIG_4`) = c("SWIGFunction", class('OesSigHandler_add__SWIG_4'))

# Start of OesSigHandler_add

`OesSigHandler_add__SWIG_5` = function(self, manageme)
{
  ;.Call('R_swig_OesSigHandler_add__SWIG_5', self, manageme, PACKAGE='oescriptimpl');
  
}

attr(`OesSigHandler_add__SWIG_5`, 'returnType') = 'void'
attr(`OesSigHandler_add__SWIG_5`, "inputTypes") = c('_p_OesSigHandler', '_p_OesNet')
class(`OesSigHandler_add__SWIG_5`) = c("SWIGFunction", class('OesSigHandler_add__SWIG_5'))

`OesSigHandler_add` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
# dispatch functions 6
  if (argc == 2) {
    if (extends(argtypes[1], '_p_OesSigHandler') && extends(argtypes[2], '_p_OesDispatcher')) {
      f <- OesSigHandler_add__SWIG_0; 
    }
    else if (extends(argtypes[1], '_p_OesSigHandler') && extends(argtypes[2], '_p_OesThreadDispatcher')) {
      f <- OesSigHandler_add__SWIG_1; 
    }
    else if (extends(argtypes[1], '_p_OesSigHandler') && extends(argtypes[2], '_p_OesStore')) {
      f <- OesSigHandler_add__SWIG_2; 
    }
    else if (extends(argtypes[1], '_p_OesSigHandler') && extends(argtypes[2], '_p_OesServer')) {
      f <- OesSigHandler_add__SWIG_3; 
    }
    else if (extends(argtypes[1], '_p_OesSigHandler') && extends(argtypes[2], '_p_OesKernel')) {
      f <- OesSigHandler_add__SWIG_4; 
    }
    else if (extends(argtypes[1], '_p_OesSigHandler') && extends(argtypes[2], '_p_OesNet')) {
      f <- OesSigHandler_add__SWIG_5; 
    }
  } else {
    stop("cannot find overloaded function for OesSigHandler_add with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of accessor method for OesSigHandler
setMethod('$', '_p_OesSigHandler', function(x, name)

{
  accessorFuns = list('add' = OesSigHandler_add);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesSigHandler
setMethod('delete', '_p_OesSigHandler', function(obj) {delete_OesSigHandler(obj)})
# Start definition of copy functions & methods for OesSigHandler
CopyToR_OesSigHandler = function(value, obj = new("OesSigHandler"))
{
  obj;
}



CopyToC_OesSigHandler = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesSigHandler
setMethod('copyToR', '_p_OesSigHandler', CopyToR_OesSigHandler);
setMethod('copyToC', 'OesSigHandler', CopyToC_OesSigHandler);

# End definition of copy methods for OesSigHandler
# End definition of copy functions & methods for OesSigHandler
# Start of new_OesDispatcher

`OesDispatcher` = function(nthreads, name)
{
  if(length(nthreads) > 1) {
    warning("using only the first element of nthreads");
  };
  
  name = as(name, "character"); 
  ;ans = .Call('R_swig_new_OesDispatcher', nthreads, name, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesDispatcher";
  
  reg.finalizer(ans, delete_OesDispatcher)
  ans
  
}

attr(`OesDispatcher`, 'returnType') = '_p_OesDispatcher'
attr(`OesDispatcher`, "inputTypes") = c('integer', 'character')
class(`OesDispatcher`) = c("SWIGFunction", class('OesDispatcher'))

# Start of delete_OesDispatcher

`delete_OesDispatcher` = function(self)
{
  ;.Call('R_swig_delete_OesDispatcher', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesDispatcher`, 'returnType') = 'void'
attr(`delete_OesDispatcher`, "inputTypes") = c('_p_OesDispatcher')
class(`delete_OesDispatcher`) = c("SWIGFunction", class('delete_OesDispatcher'))

# Start of OesDispatcher_start

`OesDispatcher_start` = function(self)
{
  ;.Call('R_swig_OesDispatcher_start', self, PACKAGE='oescriptimpl');
  
}

attr(`OesDispatcher_start`, 'returnType') = 'void'
attr(`OesDispatcher_start`, "inputTypes") = c('_p_OesDispatcher')
class(`OesDispatcher_start`) = c("SWIGFunction", class('OesDispatcher_start'))

# Start of accessor method for OesDispatcher
setMethod('$', '_p_OesDispatcher', function(x, name)

{
  accessorFuns = list('start' = OesDispatcher_start);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesDispatcher
setMethod('delete', '_p_OesDispatcher', function(obj) {delete_OesDispatcher(obj)})
# Start definition of copy functions & methods for OesDispatcher
CopyToR_OesDispatcher = function(value, obj = new("OesDispatcher"))
{
  obj;
}



CopyToC_OesDispatcher = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesDispatcher
setMethod('copyToR', '_p_OesDispatcher', CopyToR_OesDispatcher);
setMethod('copyToC', 'OesDispatcher', CopyToC_OesDispatcher);

# End definition of copy methods for OesDispatcher
# End definition of copy functions & methods for OesDispatcher
# Start of new_OesThreadDispatcher

`OesThreadDispatcher` = function(nthreads)
{
  if(length(nthreads) > 1) {
    warning("using only the first element of nthreads");
  };
  
  ;ans = .Call('R_swig_new_OesThreadDispatcher', nthreads, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesThreadDispatcher";
  
  reg.finalizer(ans, delete_OesThreadDispatcher)
  ans
  
}

attr(`OesThreadDispatcher`, 'returnType') = '_p_OesThreadDispatcher'
attr(`OesThreadDispatcher`, "inputTypes") = c('integer')
class(`OesThreadDispatcher`) = c("SWIGFunction", class('OesThreadDispatcher'))

# Start of delete_OesThreadDispatcher

`delete_OesThreadDispatcher` = function(self)
{
  ;.Call('R_swig_delete_OesThreadDispatcher', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesThreadDispatcher`, 'returnType') = 'void'
attr(`delete_OesThreadDispatcher`, "inputTypes") = c('_p_OesThreadDispatcher')
class(`delete_OesThreadDispatcher`) = c("SWIGFunction", class('delete_OesThreadDispatcher'))

# Start of OesThreadDispatcher_start

`OesThreadDispatcher_start` = function(self)
{
  ;.Call('R_swig_OesThreadDispatcher_start', self, PACKAGE='oescriptimpl');
  
}

attr(`OesThreadDispatcher_start`, 'returnType') = 'void'
attr(`OesThreadDispatcher_start`, "inputTypes") = c('_p_OesThreadDispatcher')
class(`OesThreadDispatcher_start`) = c("SWIGFunction", class('OesThreadDispatcher_start'))

# Start of accessor method for OesThreadDispatcher
setMethod('$', '_p_OesThreadDispatcher', function(x, name)

{
  accessorFuns = list('start' = OesThreadDispatcher_start);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesThreadDispatcher
setMethod('delete', '_p_OesThreadDispatcher', function(obj) {delete_OesThreadDispatcher(obj)})
# Start definition of copy functions & methods for OesThreadDispatcher
CopyToR_OesThreadDispatcher = function(value, obj = new("OesThreadDispatcher"))
{
  obj;
}



CopyToC_OesThreadDispatcher = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesThreadDispatcher
setMethod('copyToR', '_p_OesThreadDispatcher', CopyToR_OesThreadDispatcher);
setMethod('copyToC', 'OesThreadDispatcher', CopyToC_OesThreadDispatcher);

# End definition of copy methods for OesThreadDispatcher
# End definition of copy functions & methods for OesThreadDispatcher
# Start of new_OesStore

`OesStore` = function(persist_level, homedir, threaded)
{
  persist_level = as.integer(persist_level); 
  
  if(length(persist_level) > 1) {
    warning("using only the first element of persist_level");
  };
  
  homedir = as(homedir, "character"); 
  threaded = as.logical(threaded);
  ;ans = .Call('R_swig_new_OesStore', persist_level, homedir, threaded, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesStore";
  
  reg.finalizer(ans, delete_OesStore)
  ans
  
}

attr(`OesStore`, 'returnType') = '_p_OesStore'
attr(`OesStore`, "inputTypes") = c('integer', 'character', 'logical')
class(`OesStore`) = c("SWIGFunction", class('OesStore'))

# Start of delete_OesStore

`delete_OesStore` = function(self)
{
  ;.Call('R_swig_delete_OesStore', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesStore`, 'returnType') = 'void'
attr(`delete_OesStore`, "inputTypes") = c('_p_OesStore')
class(`delete_OesStore`) = c("SWIGFunction", class('delete_OesStore'))

setMethod('delete', '_p_OesStore', function(obj) {delete_OesStore(obj)})
# Start definition of copy functions & methods for OesStore
CopyToR_OesStore = function(value, obj = new("OesStore"))
{
  obj;
}



CopyToC_OesStore = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesStore
setMethod('copyToR', '_p_OesStore', CopyToR_OesStore);
setMethod('copyToC', 'OesStore', CopyToC_OesStore);

# End definition of copy methods for OesStore
# End definition of copy functions & methods for OesStore
# Start of new_OesNet

`OesNet` = function(d, use_ssl, cert, pkey)
{
  use_ssl = as.logical(use_ssl);
  cert = as(cert, "character"); 
  pkey = as(pkey, "character"); 
  ;ans = .Call('R_swig_new_OesNet', d, use_ssl, cert, pkey, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesNet";
  
  reg.finalizer(ans, delete_OesNet)
  ans
  
}

attr(`OesNet`, 'returnType') = '_p_OesNet'
attr(`OesNet`, "inputTypes") = c('_p_OesDispatcher', 'logical', 'character', 'character')
class(`OesNet`) = c("SWIGFunction", class('OesNet'))

# Start of delete_OesNet

`delete_OesNet` = function(self)
{
  ;.Call('R_swig_delete_OesNet', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesNet`, 'returnType') = 'void'
attr(`delete_OesNet`, "inputTypes") = c('_p_OesNet')
class(`delete_OesNet`) = c("SWIGFunction", class('delete_OesNet'))

# Start of OesNet_setName

`OesNet_setName` = function(self, name)
{
  name = as(name, "character"); 
  ;.Call('R_swig_OesNet_setName', self, name, PACKAGE='oescriptimpl');
  
}

attr(`OesNet_setName`, 'returnType') = 'void'
attr(`OesNet_setName`, "inputTypes") = c('_p_OesNet', 'character')
class(`OesNet_setName`) = c("SWIGFunction", class('OesNet_setName'))

# Start of OesNet_getName

`OesNet_getName` = function(self)
{
  ;.Call('R_swig_OesNet_getName', self, PACKAGE='oescriptimpl');
  
}

attr(`OesNet_getName`, 'returnType') = 'character'
attr(`OesNet_getName`, "inputTypes") = c('_p_OesNet')
class(`OesNet_getName`) = c("SWIGFunction", class('OesNet_getName'))

# Start of accessor method for OesNet
setMethod('$', '_p_OesNet', function(x, name)

{
  accessorFuns = list('setName' = OesNet_setName, 'getName' = OesNet_getName);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesNet
setMethod('delete', '_p_OesNet', function(obj) {delete_OesNet(obj)})
# Start definition of copy functions & methods for OesNet
CopyToR_OesNet = function(value, obj = new("OesNet"))
{
  obj;
}



CopyToC_OesNet = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesNet
setMethod('copyToR', '_p_OesNet', CopyToR_OesNet);
setMethod('copyToC', 'OesNet', CopyToC_OesNet);

# End definition of copy methods for OesNet
# End definition of copy functions & methods for OesNet
# Start of delete_OesLoginModule

`delete_OesLoginModule` = function(self)
{
  ;.Call('R_swig_delete_OesLoginModule', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesLoginModule`, 'returnType') = 'void'
attr(`delete_OesLoginModule`, "inputTypes") = c('_p_OesLoginModule')
class(`delete_OesLoginModule`) = c("SWIGFunction", class('delete_OesLoginModule'))

# Start of new_OesLoginModule

`OesLoginModule` = function()
{
  ;ans = .Call('R_swig_new_OesLoginModule', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesLoginModule";
  
  reg.finalizer(ans, delete_OesLoginModule)
  ans
  
}

attr(`OesLoginModule`, 'returnType') = '_p_OesLoginModule'
class(`OesLoginModule`) = c("SWIGFunction", class('OesLoginModule'))

setMethod('delete', '_p_OesLoginModule', function(obj) {delete_OesLoginModule(obj)})
# Start definition of copy functions & methods for OesLoginModule
CopyToR_OesLoginModule = function(value, obj = new("OesLoginModule"))
{
  obj;
}



CopyToC_OesLoginModule = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesLoginModule
setMethod('copyToR', '_p_OesLoginModule', CopyToR_OesLoginModule);
setMethod('copyToC', 'OesLoginModule', CopyToC_OesLoginModule);

# End definition of copy methods for OesLoginModule
# End definition of copy functions & methods for OesLoginModule
# Start of new_OesBuiltInLoginModule

`OesBuiltInLoginModule` = function()
{
  ;ans = .Call('R_swig_new_OesBuiltInLoginModule', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesBuiltInLoginModule";
  
  reg.finalizer(ans, delete_OesBuiltInLoginModule)
  ans
  
}

attr(`OesBuiltInLoginModule`, 'returnType') = '_p_OesBuiltInLoginModule'
class(`OesBuiltInLoginModule`) = c("SWIGFunction", class('OesBuiltInLoginModule'))

# Start of delete_OesBuiltInLoginModule

`delete_OesBuiltInLoginModule` = function(self)
{
  ;.Call('R_swig_delete_OesBuiltInLoginModule', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesBuiltInLoginModule`, 'returnType') = 'void'
attr(`delete_OesBuiltInLoginModule`, "inputTypes") = c('_p_OesBuiltInLoginModule')
class(`delete_OesBuiltInLoginModule`) = c("SWIGFunction", class('delete_OesBuiltInLoginModule'))

# Start of OesBuiltInLoginModule_addAccount

`OesBuiltInLoginModule_addAccount` = function(self, groupname, username, pwd, .copy = FALSE)
{
  groupname = as(groupname, "character"); 
  username = as(username, "character"); 
  pwd = as(pwd, "character"); 
  ;.Call('R_swig_OesBuiltInLoginModule_addAccount', self, groupname, username, pwd, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesBuiltInLoginModule_addAccount`, 'returnType') = 'integer'
attr(`OesBuiltInLoginModule_addAccount`, "inputTypes") = c('_p_OesBuiltInLoginModule', 'character', 'character', 'character')
class(`OesBuiltInLoginModule_addAccount`) = c("SWIGFunction", class('OesBuiltInLoginModule_addAccount'))

# Start of OesBuiltInLoginModule_addPrivilege

`OesBuiltInLoginModule_addPrivilege` = function(self, extentname, groupname, mtemplate, .copy = FALSE)
{
  extentname = as(extentname, "character"); 
  groupname = as(groupname, "character"); 
  mtemplate = as(mtemplate, "character"); 
  ;.Call('R_swig_OesBuiltInLoginModule_addPrivilege', self, extentname, groupname, mtemplate, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesBuiltInLoginModule_addPrivilege`, 'returnType') = 'integer'
attr(`OesBuiltInLoginModule_addPrivilege`, "inputTypes") = c('_p_OesBuiltInLoginModule', 'character', 'character', 'character')
class(`OesBuiltInLoginModule_addPrivilege`) = c("SWIGFunction", class('OesBuiltInLoginModule_addPrivilege'))

# Start of OesBuiltInLoginModule_getModule

`OesBuiltInLoginModule_getModule` = function(self)
{
  ;ans = .Call('R_swig_OesBuiltInLoginModule_getModule', self, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesLoginModule";
  
  ans
  
}

attr(`OesBuiltInLoginModule_getModule`, 'returnType') = '_p_OesLoginModule'
attr(`OesBuiltInLoginModule_getModule`, "inputTypes") = c('_p_OesBuiltInLoginModule')
class(`OesBuiltInLoginModule_getModule`) = c("SWIGFunction", class('OesBuiltInLoginModule_getModule'))

# Start of accessor method for OesBuiltInLoginModule
setMethod('$', '_p_OesBuiltInLoginModule', function(x, name)

{
  accessorFuns = list('addAccount' = OesBuiltInLoginModule_addAccount, 'addPrivilege' = OesBuiltInLoginModule_addPrivilege, 'getModule' = OesBuiltInLoginModule_getModule);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesBuiltInLoginModule
setMethod('delete', '_p_OesBuiltInLoginModule', function(obj) {delete_OesBuiltInLoginModule(obj)})
# Start definition of copy functions & methods for OesBuiltInLoginModule
CopyToR_OesBuiltInLoginModule = function(value, obj = new("OesBuiltInLoginModule"))
{
  obj;
}



CopyToC_OesBuiltInLoginModule = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesBuiltInLoginModule
setMethod('copyToR', '_p_OesBuiltInLoginModule', CopyToR_OesBuiltInLoginModule);
setMethod('copyToC', 'OesBuiltInLoginModule', CopyToC_OesBuiltInLoginModule);

# End definition of copy methods for OesBuiltInLoginModule
# End definition of copy functions & methods for OesBuiltInLoginModule
# Start of new_OesPamLoginModule

`OesPamLoginModule` = function(pamdomain, defgroup)
{
  pamdomain = as(pamdomain, "character"); 
  defgroup = as(defgroup, "character"); 
  ;ans = .Call('R_swig_new_OesPamLoginModule', pamdomain, defgroup, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesPamLoginModule";
  
  reg.finalizer(ans, delete_OesPamLoginModule)
  ans
  
}

attr(`OesPamLoginModule`, 'returnType') = '_p_OesPamLoginModule'
attr(`OesPamLoginModule`, "inputTypes") = c('character', 'character')
class(`OesPamLoginModule`) = c("SWIGFunction", class('OesPamLoginModule'))

# Start of delete_OesPamLoginModule

`delete_OesPamLoginModule` = function(self)
{
  ;.Call('R_swig_delete_OesPamLoginModule', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesPamLoginModule`, 'returnType') = 'void'
attr(`delete_OesPamLoginModule`, "inputTypes") = c('_p_OesPamLoginModule')
class(`delete_OesPamLoginModule`) = c("SWIGFunction", class('delete_OesPamLoginModule'))

# Start of OesPamLoginModule_addPrivilege

`OesPamLoginModule_addPrivilege` = function(self, extentname, groupname, mtemplate, .copy = FALSE)
{
  extentname = as(extentname, "character"); 
  groupname = as(groupname, "character"); 
  mtemplate = as(mtemplate, "character"); 
  ;.Call('R_swig_OesPamLoginModule_addPrivilege', self, extentname, groupname, mtemplate, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesPamLoginModule_addPrivilege`, 'returnType') = 'integer'
attr(`OesPamLoginModule_addPrivilege`, "inputTypes") = c('_p_OesPamLoginModule', 'character', 'character', 'character')
class(`OesPamLoginModule_addPrivilege`) = c("SWIGFunction", class('OesPamLoginModule_addPrivilege'))

# Start of OesPamLoginModule_getModule

`OesPamLoginModule_getModule` = function(self)
{
  ;ans = .Call('R_swig_OesPamLoginModule_getModule', self, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesLoginModule";
  
  ans
  
}

attr(`OesPamLoginModule_getModule`, 'returnType') = '_p_OesLoginModule'
attr(`OesPamLoginModule_getModule`, "inputTypes") = c('_p_OesPamLoginModule')
class(`OesPamLoginModule_getModule`) = c("SWIGFunction", class('OesPamLoginModule_getModule'))

# Start of accessor method for OesPamLoginModule
setMethod('$', '_p_OesPamLoginModule', function(x, name)

{
  accessorFuns = list('addPrivilege' = OesPamLoginModule_addPrivilege, 'getModule' = OesPamLoginModule_getModule);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesPamLoginModule
setMethod('delete', '_p_OesPamLoginModule', function(obj) {delete_OesPamLoginModule(obj)})
# Start definition of copy functions & methods for OesPamLoginModule
CopyToR_OesPamLoginModule = function(value, obj = new("OesPamLoginModule"))
{
  obj;
}



CopyToC_OesPamLoginModule = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesPamLoginModule
setMethod('copyToR', '_p_OesPamLoginModule', CopyToR_OesPamLoginModule);
setMethod('copyToC', 'OesPamLoginModule', CopyToC_OesPamLoginModule);

# End definition of copy methods for OesPamLoginModule
# End definition of copy functions & methods for OesPamLoginModule
# Start of new_OesServer

`OesServer` = function(dispatcher, spec, net, store)
{
  spec = as(spec, "character"); 
  
  
  ;ans = .Call('R_swig_new_OesServer', dispatcher, spec, net, store, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesServer";
  
  reg.finalizer(ans, delete_OesServer)
  ans
  
}

attr(`OesServer`, 'returnType') = '_p_OesServer'
attr(`OesServer`, "inputTypes") = c('_p_OesDispatcher', 'character', '_p_OesNet', '_p_OesStore')
class(`OesServer`) = c("SWIGFunction", class('OesServer'))

# Start of delete_OesServer

`delete_OesServer` = function(self)
{
  ;.Call('R_swig_delete_OesServer', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesServer`, 'returnType') = 'void'
attr(`delete_OesServer`, "inputTypes") = c('_p_OesServer')
class(`delete_OesServer`) = c("SWIGFunction", class('delete_OesServer'))

# Start of OesServer_addLoginModule

`OesServer_addLoginModule` = function(self, m)
{
  ;.Call('R_swig_OesServer_addLoginModule', self, m, PACKAGE='oescriptimpl');
  
}

attr(`OesServer_addLoginModule`, 'returnType') = 'void'
attr(`OesServer_addLoginModule`, "inputTypes") = c('_p_OesServer', '_p_OesLoginModule')
class(`OesServer_addLoginModule`) = c("SWIGFunction", class('OesServer_addLoginModule'))

# Start of OesServer_addKernel

`OesServer_addKernel` = function(self, extentname, kernel)
{
  extentname = as(extentname, "character"); 
  
  ;.Call('R_swig_OesServer_addKernel', self, extentname, kernel, PACKAGE='oescriptimpl');
  
}

attr(`OesServer_addKernel`, 'returnType') = 'void'
attr(`OesServer_addKernel`, "inputTypes") = c('_p_OesServer', 'character', '_p_OesKernel')
class(`OesServer_addKernel`) = c("SWIGFunction", class('OesServer_addKernel'))

# Start of accessor method for OesServer
setMethod('$', '_p_OesServer', function(x, name)

{
  accessorFuns = list('addLoginModule' = OesServer_addLoginModule, 'addKernel' = OesServer_addKernel);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesServer
setMethod('delete', '_p_OesServer', function(obj) {delete_OesServer(obj)})
# Start definition of copy functions & methods for OesServer
CopyToR_OesServer = function(value, obj = new("OesServer"))
{
  obj;
}



CopyToC_OesServer = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesServer
setMethod('copyToR', '_p_OesServer', CopyToR_OesServer);
setMethod('copyToC', 'OesServer', CopyToC_OesServer);

# End definition of copy methods for OesServer
# End definition of copy functions & methods for OesServer
# Start of new_OesDataObjectList

`OesDataObjectList` = function()
{
  ;ans = .Call('R_swig_new_OesDataObjectList', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesDataObjectList";
  
  reg.finalizer(ans, delete_OesDataObjectList)
  ans
  
}

attr(`OesDataObjectList`, 'returnType') = '_p_OesDataObjectList'
class(`OesDataObjectList`) = c("SWIGFunction", class('OesDataObjectList'))

# Start of delete_OesDataObjectList

`delete_OesDataObjectList` = function(self)
{
  ;.Call('R_swig_delete_OesDataObjectList', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesDataObjectList`, 'returnType') = 'void'
attr(`delete_OesDataObjectList`, "inputTypes") = c('_p_OesDataObjectList')
class(`delete_OesDataObjectList`) = c("SWIGFunction", class('delete_OesDataObjectList'))

# Start of OesDataObjectList_length

`OesDataObjectList_length` = function(self, .copy = FALSE)
{
  ;.Call('R_swig_OesDataObjectList_length', self, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesDataObjectList_length`, 'returnType') = 'integer'
attr(`OesDataObjectList_length`, "inputTypes") = c('_p_OesDataObjectList')
class(`OesDataObjectList_length`) = c("SWIGFunction", class('OesDataObjectList_length'))

# Start of OesDataObjectList_iter

`OesDataObjectList_iter` = function(self)
{
  ;ans = .Call('R_swig_OesDataObjectList_iter', self, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesListIterator";
  
  ans
  
}

attr(`OesDataObjectList_iter`, 'returnType') = '_p_OesListIterator'
attr(`OesDataObjectList_iter`, "inputTypes") = c('_p_OesDataObjectList')
class(`OesDataObjectList_iter`) = c("SWIGFunction", class('OesDataObjectList_iter'))

# Start of OesDataObjectList_newDataObject

`OesDataObjectList_newDataObject` = function(self)
{
  ;ans = .Call('R_swig_OesDataObjectList_newDataObject', self, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesDataObject";
  
  ans
  
}

attr(`OesDataObjectList_newDataObject`, 'returnType') = '_p_OesDataObject'
attr(`OesDataObjectList_newDataObject`, "inputTypes") = c('_p_OesDataObjectList')
class(`OesDataObjectList_newDataObject`) = c("SWIGFunction", class('OesDataObjectList_newDataObject'))

# Start of accessor method for OesDataObjectList
setMethod('$', '_p_OesDataObjectList', function(x, name)

{
  accessorFuns = list('length' = OesDataObjectList_length, 'iter' = OesDataObjectList_iter, 'newDataObject' = OesDataObjectList_newDataObject);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesDataObjectList
setMethod('delete', '_p_OesDataObjectList', function(obj) {delete_OesDataObjectList(obj)})
# Start definition of copy functions & methods for OesDataObjectList
CopyToR_OesDataObjectList = function(value, obj = new("OesDataObjectList"))
{
  obj;
}



CopyToC_OesDataObjectList = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesDataObjectList
setMethod('copyToR', '_p_OesDataObjectList', CopyToR_OesDataObjectList);
setMethod('copyToC', 'OesDataObjectList', CopyToC_OesDataObjectList);

# End definition of copy methods for OesDataObjectList
# End definition of copy functions & methods for OesDataObjectList
# Start of delete_OesIterator

`delete_OesIterator` = function(self)
{
  ;.Call('R_swig_delete_OesIterator', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesIterator`, 'returnType') = 'void'
attr(`delete_OesIterator`, "inputTypes") = c('_p_OesIterator')
class(`delete_OesIterator`) = c("SWIGFunction", class('delete_OesIterator'))

# Start of OesIterator_nextItem

`OesIterator_nextItem` = function(self)
{
  ;.Call('R_swig_OesIterator_nextItem', self, PACKAGE='oescriptimpl');
  
}

attr(`OesIterator_nextItem`, 'returnType') = 'character'
attr(`OesIterator_nextItem`, "inputTypes") = c('_p_OesIterator')
class(`OesIterator_nextItem`) = c("SWIGFunction", class('OesIterator_nextItem'))

# Start of OesIterator_hasMore

`OesIterator_hasMore` = function(self, .copy = FALSE)
{
  ;.Call('R_swig_OesIterator_hasMore', self, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesIterator_hasMore`, 'returnType') = 'logical'
attr(`OesIterator_hasMore`, "inputTypes") = c('_p_OesIterator')
class(`OesIterator_hasMore`) = c("SWIGFunction", class('OesIterator_hasMore'))

# Start of new_OesIterator

`OesIterator` = function()
{
  ;ans = .Call('R_swig_new_OesIterator', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesIterator";
  
  reg.finalizer(ans, delete_OesIterator)
  ans
  
}

attr(`OesIterator`, 'returnType') = '_p_OesIterator'
class(`OesIterator`) = c("SWIGFunction", class('OesIterator'))

# Start of accessor method for OesIterator
setMethod('$', '_p_OesIterator', function(x, name)

{
  accessorFuns = list('nextItem' = OesIterator_nextItem, 'hasMore' = OesIterator_hasMore);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesIterator
setMethod('delete', '_p_OesIterator', function(obj) {delete_OesIterator(obj)})
# Start definition of copy functions & methods for OesIterator
CopyToR_OesIterator = function(value, obj = new("OesIterator"))
{
  obj;
}



CopyToC_OesIterator = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesIterator
setMethod('copyToR', '_p_OesIterator', CopyToR_OesIterator);
setMethod('copyToC', 'OesIterator', CopyToC_OesIterator);

# End definition of copy methods for OesIterator
# End definition of copy functions & methods for OesIterator
# Start of delete_OesListIterator

`delete_OesListIterator` = function(self)
{
  ;.Call('R_swig_delete_OesListIterator', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesListIterator`, 'returnType') = 'void'
attr(`delete_OesListIterator`, "inputTypes") = c('_p_OesListIterator')
class(`delete_OesListIterator`) = c("SWIGFunction", class('delete_OesListIterator'))

# Start of OesListIterator_nextItem

`OesListIterator_nextItem` = function(self)
{
  ;ans = .Call('R_swig_OesListIterator_nextItem', self, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesDataObject";
  
  ans
  
}

attr(`OesListIterator_nextItem`, 'returnType') = '_p_OesDataObject'
attr(`OesListIterator_nextItem`, "inputTypes") = c('_p_OesListIterator')
class(`OesListIterator_nextItem`) = c("SWIGFunction", class('OesListIterator_nextItem'))

# Start of OesListIterator_hasMore

`OesListIterator_hasMore` = function(self, .copy = FALSE)
{
  ;.Call('R_swig_OesListIterator_hasMore', self, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesListIterator_hasMore`, 'returnType') = 'logical'
attr(`OesListIterator_hasMore`, "inputTypes") = c('_p_OesListIterator')
class(`OesListIterator_hasMore`) = c("SWIGFunction", class('OesListIterator_hasMore'))

# Start of new_OesListIterator

`OesListIterator` = function()
{
  ;ans = .Call('R_swig_new_OesListIterator', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesListIterator";
  
  reg.finalizer(ans, delete_OesListIterator)
  ans
  
}

attr(`OesListIterator`, 'returnType') = '_p_OesListIterator'
class(`OesListIterator`) = c("SWIGFunction", class('OesListIterator'))

# Start of accessor method for OesListIterator
setMethod('$', '_p_OesListIterator', function(x, name)

{
  accessorFuns = list('nextItem' = OesListIterator_nextItem, 'hasMore' = OesListIterator_hasMore);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesListIterator
setMethod('delete', '_p_OesListIterator', function(obj) {delete_OesListIterator(obj)})
# Start definition of copy functions & methods for OesListIterator
CopyToR_OesListIterator = function(value, obj = new("OesListIterator"))
{
  obj;
}



CopyToC_OesListIterator = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesListIterator
setMethod('copyToR', '_p_OesListIterator', CopyToR_OesListIterator);
setMethod('copyToC', 'OesListIterator', CopyToC_OesListIterator);

# End definition of copy methods for OesListIterator
# End definition of copy functions & methods for OesListIterator
# Start of delete_OesLease

`delete_OesLease` = function(self)
{
  ;.Call('R_swig_delete_OesLease', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesLease`, 'returnType') = 'void'
attr(`delete_OesLease`, "inputTypes") = c('_p_OesLease')
class(`delete_OesLease`) = c("SWIGFunction", class('delete_OesLease'))

# Start of OesLease_lid

`OesLease_lid` = function(self, .copy = FALSE)
{
  ;.Call('R_swig_OesLease_lid', self, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesLease_lid`, 'returnType') = 'integer'
attr(`OesLease_lid`, "inputTypes") = c('_p_OesLease')
class(`OesLease_lid`) = c("SWIGFunction", class('OesLease_lid'))

# Start of OesLease_cancel

`OesLease_cancel` = function(self)
{
  ;.Call('R_swig_OesLease_cancel', self, PACKAGE='oescriptimpl');
  
}

attr(`OesLease_cancel`, 'returnType') = 'void'
attr(`OesLease_cancel`, "inputTypes") = c('_p_OesLease')
class(`OesLease_cancel`) = c("SWIGFunction", class('OesLease_cancel'))

# Start of new_OesLease

`OesLease` = function()
{
  ;ans = .Call('R_swig_new_OesLease', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesLease";
  
  reg.finalizer(ans, delete_OesLease)
  ans
  
}

attr(`OesLease`, 'returnType') = '_p_OesLease'
class(`OesLease`) = c("SWIGFunction", class('OesLease'))

# Start of accessor method for OesLease
setMethod('$', '_p_OesLease', function(x, name)

{
  accessorFuns = list('lid' = OesLease_lid, 'cancel' = OesLease_cancel);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesLease
setMethod('delete', '_p_OesLease', function(obj) {delete_OesLease(obj)})
# Start definition of copy functions & methods for OesLease
CopyToR_OesLease = function(value, obj = new("OesLease"))
{
  obj;
}



CopyToC_OesLease = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesLease
setMethod('copyToR', '_p_OesLease', CopyToR_OesLease);
setMethod('copyToC', 'OesLease', CopyToC_OesLease);

# End definition of copy methods for OesLease
# End definition of copy functions & methods for OesLease
# Start of delete_OesTxn

`delete_OesTxn` = function(self)
{
  ;.Call('R_swig_delete_OesTxn', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesTxn`, 'returnType') = 'void'
attr(`delete_OesTxn`, "inputTypes") = c('_p_OesTxn')
class(`delete_OesTxn`) = c("SWIGFunction", class('delete_OesTxn'))

# Start of OesTxn_tid

`OesTxn_tid` = function(self, .copy = FALSE)
{
  ;.Call('R_swig_OesTxn_tid', self, as.logical(.copy), PACKAGE='oescriptimpl');
  
}

attr(`OesTxn_tid`, 'returnType') = 'integer'
attr(`OesTxn_tid`, "inputTypes") = c('_p_OesTxn')
class(`OesTxn_tid`) = c("SWIGFunction", class('OesTxn_tid'))

# Start of OesTxn_status

`OesTxn_status` = function(self, .copy = FALSE)
{
  ;ans = .Call('R_swig_OesTxn_status', self, as.logical(.copy), PACKAGE='oescriptimpl');
  ans = enumFromInteger(ans, "_OES_TXN_STATUS");
  
  ans
  
}

attr(`OesTxn_status`, 'returnType') = 'character'
attr(`OesTxn_status`, "inputTypes") = c('_p_OesTxn')
class(`OesTxn_status`) = c("SWIGFunction", class('OesTxn_status'))

# Start of OesTxn_commit

`OesTxn_commit` = function(self)
{
  ;.Call('R_swig_OesTxn_commit', self, PACKAGE='oescriptimpl');
  
}

attr(`OesTxn_commit`, 'returnType') = 'void'
attr(`OesTxn_commit`, "inputTypes") = c('_p_OesTxn')
class(`OesTxn_commit`) = c("SWIGFunction", class('OesTxn_commit'))

# Start of OesTxn_rollback

`OesTxn_rollback` = function(self)
{
  ;.Call('R_swig_OesTxn_rollback', self, PACKAGE='oescriptimpl');
  
}

attr(`OesTxn_rollback`, 'returnType') = 'void'
attr(`OesTxn_rollback`, "inputTypes") = c('_p_OesTxn')
class(`OesTxn_rollback`) = c("SWIGFunction", class('OesTxn_rollback'))

# Start of new_OesTxn

`OesTxn` = function()
{
  ;ans = .Call('R_swig_new_OesTxn', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesTxn";
  
  reg.finalizer(ans, delete_OesTxn)
  ans
  
}

attr(`OesTxn`, 'returnType') = '_p_OesTxn'
class(`OesTxn`) = c("SWIGFunction", class('OesTxn'))

# Start of accessor method for OesTxn
setMethod('$', '_p_OesTxn', function(x, name)

{
  accessorFuns = list('tid' = OesTxn_tid, 'status' = OesTxn_status, 'commit' = OesTxn_commit, 'rollback' = OesTxn_rollback);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesTxn
setMethod('delete', '_p_OesTxn', function(obj) {delete_OesTxn(obj)})
# Start definition of copy functions & methods for OesTxn
CopyToR_OesTxn = function(value, obj = new("OesTxn"))
{
  obj;
}



CopyToC_OesTxn = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesTxn
setMethod('copyToR', '_p_OesTxn', CopyToR_OesTxn);
setMethod('copyToC', 'OesTxn', CopyToC_OesTxn);

# End definition of copy methods for OesTxn
# End definition of copy functions & methods for OesTxn
# Start of new_OesKernel

`OesKernel` = function(dispatcher, tdispatcher, store, netspec, net, username, pwd)
{
  netspec = as(netspec, "character"); 
  
  username = as(username, "character"); 
  pwd = as(pwd, "character"); 
  ;ans = .Call('R_swig_new_OesKernel', dispatcher, tdispatcher, store, netspec, net, username, pwd, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesKernel";
  
  reg.finalizer(ans, delete_OesKernel)
  ans
  
}

attr(`OesKernel`, 'returnType') = '_p_OesKernel'
attr(`OesKernel`, "inputTypes") = c('_p_OesDispatcher', '_p_OesThreadDispatcher', '_p_OesStore', 'character', '_p_OesNet', 'character', 'character')
class(`OesKernel`) = c("SWIGFunction", class('OesKernel'))

# Start of delete_OesKernel

`delete_OesKernel` = function(self)
{
  ;.Call('R_swig_delete_OesKernel', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesKernel`, 'returnType') = 'void'
attr(`delete_OesKernel`, "inputTypes") = c('_p_OesKernel')
class(`delete_OesKernel`) = c("SWIGFunction", class('delete_OesKernel'))

# Start of OesKernel_write

`OesKernel_write` = function(self, slist, dur, is_tuple)
{
  dur = as.integer(dur); 
  
  if(length(dur) > 1) {
    warning("using only the first element of dur");
  };
  
  is_tuple = as.logical(is_tuple);
  ;ans = .Call('R_swig_OesKernel_write', self, slist, dur, is_tuple, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesLease";
  
  ans
  
}

attr(`OesKernel_write`, 'returnType') = '_p_OesLease'
attr(`OesKernel_write`, "inputTypes") = c('_p_OesKernel', '_p_OesDataObject', 'integer', 'logical')
class(`OesKernel_write`) = c("SWIGFunction", class('OesKernel_write'))

# Start of OesKernel_begin

`OesKernel_begin` = function(self, dur)
{
  dur = as.integer(dur); 
  
  if(length(dur) > 1) {
    warning("using only the first element of dur");
  };
  
  ;ans = .Call('R_swig_OesKernel_begin', self, dur, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesTxn";
  
  ans
  
}

attr(`OesKernel_begin`, 'returnType') = '_p_OesTxn'
attr(`OesKernel_begin`, "inputTypes") = c('_p_OesKernel', 'integer')
class(`OesKernel_begin`) = c("SWIGFunction", class('OesKernel_begin'))

# Start of OesKernel_setCurrent

`OesKernel_setCurrent` = function(self, txn_holder)
{
  ;.Call('R_swig_OesKernel_setCurrent', self, txn_holder, PACKAGE='oescriptimpl');
  
}

attr(`OesKernel_setCurrent`, 'returnType') = 'void'
attr(`OesKernel_setCurrent`, "inputTypes") = c('_p_OesKernel', '_p_OesTxn')
class(`OesKernel_setCurrent`) = c("SWIGFunction", class('OesKernel_setCurrent'))

# Start of OesKernel_read

`OesKernel_read` = function(self, data, timeout, is_tuple, max_responses, return_attrs, return_bytes)
{
  timeout = as.integer(timeout); 
  
  if(length(timeout) > 1) {
    warning("using only the first element of timeout");
  };
  
  is_tuple = as.logical(is_tuple);
  max_responses = as.integer(max_responses); 
  
  if(length(max_responses) > 1) {
    warning("using only the first element of max_responses");
  };
  
  return_attrs = as.logical(return_attrs);
  return_bytes = as.logical(return_bytes);
  ;ans = .Call('R_swig_OesKernel_read', self, data, timeout, is_tuple, max_responses, return_attrs, return_bytes, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesDataObjectList";
  
  ans
  
}

attr(`OesKernel_read`, 'returnType') = '_p_OesDataObjectList'
attr(`OesKernel_read`, "inputTypes") = c('_p_OesKernel', '_p_OesDataObjectList', 'integer', 'logical', 'integer', 'logical', 'logical')
class(`OesKernel_read`) = c("SWIGFunction", class('OesKernel_read'))

# Start of OesKernel_take

`OesKernel_take` = function(self, data, timeout, is_tuple, max_responses, return_attrs, return_bytes)
{
  timeout = as.integer(timeout); 
  
  if(length(timeout) > 1) {
    warning("using only the first element of timeout");
  };
  
  is_tuple = as.logical(is_tuple);
  max_responses = as.integer(max_responses); 
  
  if(length(max_responses) > 1) {
    warning("using only the first element of max_responses");
  };
  
  return_attrs = as.logical(return_attrs);
  return_bytes = as.logical(return_bytes);
  ;ans = .Call('R_swig_OesKernel_take', self, data, timeout, is_tuple, max_responses, return_attrs, return_bytes, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesDataObjectList";
  
  ans
  
}

attr(`OesKernel_take`, 'returnType') = '_p_OesDataObjectList'
attr(`OesKernel_take`, "inputTypes") = c('_p_OesKernel', '_p_OesDataObjectList', 'integer', 'logical', 'integer', 'logical', 'logical')
class(`OesKernel_take`) = c("SWIGFunction", class('OesKernel_take'))

# Start of accessor method for OesKernel
setMethod('$', '_p_OesKernel', function(x, name)

{
  accessorFuns = list('write' = OesKernel_write, 'begin' = OesKernel_begin, 'setCurrent' = OesKernel_setCurrent, 'read' = OesKernel_read, 'take' = OesKernel_take);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesKernel
setMethod('delete', '_p_OesKernel', function(obj) {delete_OesKernel(obj)})
# Start definition of copy functions & methods for OesKernel
CopyToR_OesKernel = function(value, obj = new("OesKernel"))
{
  obj;
}



CopyToC_OesKernel = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesKernel
setMethod('copyToR', '_p_OesKernel', CopyToR_OesKernel);
setMethod('copyToC', 'OesKernel', CopyToC_OesKernel);

# End definition of copy methods for OesKernel
# End definition of copy functions & methods for OesKernel
# Start of new_OesJsonKernel

`OesJsonKernel` = function(kernel)
{
  ;ans = .Call('R_swig_new_OesJsonKernel', kernel, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesJsonKernel";
  
  reg.finalizer(ans, delete_OesJsonKernel)
  ans
  
}

attr(`OesJsonKernel`, 'returnType') = '_p_OesJsonKernel'
attr(`OesJsonKernel`, "inputTypes") = c('_p_OesKernel')
class(`OesJsonKernel`) = c("SWIGFunction", class('OesJsonKernel'))

# Start of delete_OesJsonKernel

`delete_OesJsonKernel` = function(self)
{
  ;.Call('R_swig_delete_OesJsonKernel', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesJsonKernel`, 'returnType') = 'void'
attr(`delete_OesJsonKernel`, "inputTypes") = c('_p_OesJsonKernel')
class(`delete_OesJsonKernel`) = c("SWIGFunction", class('delete_OesJsonKernel'))

# Start of OesJsonKernel_exec

`OesJsonKernel_exec` = function(self, json)
{
  json = as(json, "character"); 
  ;ans = .Call('R_swig_OesJsonKernel_exec', self, json, PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesFuture";
  
  ans
  
}

attr(`OesJsonKernel_exec`, 'returnType') = '_p_OesFuture'
attr(`OesJsonKernel_exec`, "inputTypes") = c('_p_OesJsonKernel', 'character')
class(`OesJsonKernel_exec`) = c("SWIGFunction", class('OesJsonKernel_exec'))

# Start of accessor method for OesJsonKernel
setMethod('$', '_p_OesJsonKernel', function(x, name)

{
  accessorFuns = list('exec' = OesJsonKernel_exec);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesJsonKernel
setMethod('delete', '_p_OesJsonKernel', function(obj) {delete_OesJsonKernel(obj)})
# Start definition of copy functions & methods for OesJsonKernel
CopyToR_OesJsonKernel = function(value, obj = new("OesJsonKernel"))
{
  obj;
}



CopyToC_OesJsonKernel = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesJsonKernel
setMethod('copyToR', '_p_OesJsonKernel', CopyToR_OesJsonKernel);
setMethod('copyToC', 'OesJsonKernel', CopyToC_OesJsonKernel);

# End definition of copy methods for OesJsonKernel
# End definition of copy functions & methods for OesJsonKernel
# Start of delete_OesFuture

`delete_OesFuture` = function(self)
{
  ;.Call('R_swig_delete_OesFuture', self, PACKAGE='oescriptimpl');
  
}

attr(`delete_OesFuture`, 'returnType') = 'void'
attr(`delete_OesFuture`, "inputTypes") = c('_p_OesFuture')
class(`delete_OesFuture`) = c("SWIGFunction", class('delete_OesFuture'))

# Start of OesFuture_getString

`OesFuture_getString` = function(self, timeout)
{
  timeout = as.integer(timeout); 
  
  if(length(timeout) > 1) {
    warning("using only the first element of timeout");
  };
  
  ;.Call('R_swig_OesFuture_getString', self, timeout, PACKAGE='oescriptimpl');
  
}

attr(`OesFuture_getString`, 'returnType') = 'character'
attr(`OesFuture_getString`, "inputTypes") = c('_p_OesFuture', 'integer')
class(`OesFuture_getString`) = c("SWIGFunction", class('OesFuture_getString'))

# Start of new_OesFuture

`OesFuture` = function()
{
  ;ans = .Call('R_swig_new_OesFuture', PACKAGE='oescriptimpl');
  class(ans) <- "_p_OesFuture";
  
  reg.finalizer(ans, delete_OesFuture)
  ans
  
}

attr(`OesFuture`, 'returnType') = '_p_OesFuture'
class(`OesFuture`) = c("SWIGFunction", class('OesFuture'))

# Start of accessor method for OesFuture
setMethod('$', '_p_OesFuture', function(x, name)

{
  accessorFuns = list('getString' = OesFuture_getString);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  formals(f)[[1]] = x;
  f;
}


);
# end of accessor method for OesFuture
setMethod('delete', '_p_OesFuture', function(obj) {delete_OesFuture(obj)})
# Start definition of copy functions & methods for OesFuture
CopyToR_OesFuture = function(value, obj = new("OesFuture"))
{
  obj;
}



CopyToC_OesFuture = function(value, obj)
{
  obj
}



# Start definition of copy methods for OesFuture
setMethod('copyToR', '_p_OesFuture', CopyToR_OesFuture);
setMethod('copyToC', 'OesFuture', CopyToC_OesFuture);

# End definition of copy methods for OesFuture
# End definition of copy functions & methods for OesFuture

