/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "oescriptimpl.so"

#include "runtime.h"
#include "cgocall.h"

#ifdef _64BIT
#define SWIG_PARM_SIZE 8
#else
#define SWIG_PARM_SIZE 4
#endif

#pragma dynimport _wrap_ACTIVE _wrap_ACTIVE ""
extern void (*_wrap_ACTIVE)(void*);
static void (*x_wrap_ACTIVE)(void*) = _wrap_ACTIVE;

void
·_swig_getACTIVE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ACTIVE, &p);
}



#pragma dynimport _wrap_ROLLEDBACK _wrap_ROLLEDBACK ""
extern void (*_wrap_ROLLEDBACK)(void*);
static void (*x_wrap_ROLLEDBACK)(void*) = _wrap_ROLLEDBACK;

void
·_swig_getROLLEDBACK(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ROLLEDBACK, &p);
}



#pragma dynimport _wrap_COMMITTED _wrap_COMMITTED ""
extern void (*_wrap_COMMITTED)(void*);
static void (*x_wrap_COMMITTED)(void*) = _wrap_COMMITTED;

void
·_swig_getCOMMITTED(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_COMMITTED, &p);
}



#pragma dynimport _wrap_new_OesDataObject _wrap_new_OesDataObject ""
extern void (*_wrap_new_OesDataObject)(void*);
static void (*x_wrap_new_OesDataObject)(void*) = _wrap_new_OesDataObject;

void
·_swig_wrap_new_OesDataObject(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesDataObject, &p);
}



#pragma dynimport _wrap_delete_OesDataObject _wrap_delete_OesDataObject ""
extern void (*_wrap_delete_OesDataObject)(void*);
static void (*x_wrap_delete_OesDataObject)(void*) = _wrap_delete_OesDataObject;

void
·_swig_wrap_delete_OesDataObject(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesDataObject, &p);
}



#pragma dynimport _wrap_OesDataObject_get_nattrs _wrap_OesDataObject_get_nattrs ""
extern void (*_wrap_OesDataObject_get_nattrs)(void*);
static void (*x_wrap_OesDataObject_get_nattrs)(void*) = _wrap_OesDataObject_get_nattrs;

void
·_swig_wrap_OesDataObject_get_nattrs(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDataObject_get_nattrs, &p);
}



#pragma dynimport _wrap_OesDataObject_add_attr _wrap_OesDataObject_add_attr ""
extern void (*_wrap_OesDataObject_add_attr)(void*);
static void (*x_wrap_OesDataObject_add_attr)(void*) = _wrap_OesDataObject_add_attr;

void
·_swig_wrap_OesDataObject_add_attr(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_OesDataObject_add_attr, &p);
}



#pragma dynimport _wrap_OesDataObject_set_nbytes _wrap_OesDataObject_set_nbytes ""
extern void (*_wrap_OesDataObject_set_nbytes)(void*);
static void (*x_wrap_OesDataObject_set_nbytes)(void*) = _wrap_OesDataObject_set_nbytes;

void
·_swig_wrap_OesDataObject_set_nbytes(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDataObject_set_nbytes, &p);
}



#pragma dynimport _wrap_OesDataObject_get_nbytes _wrap_OesDataObject_get_nbytes ""
extern void (*_wrap_OesDataObject_get_nbytes)(void*);
static void (*x_wrap_OesDataObject_get_nbytes)(void*) = _wrap_OesDataObject_get_nbytes;

void
·_swig_wrap_OesDataObject_get_nbytes(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDataObject_get_nbytes, &p);
}



#pragma dynimport _wrap_OesDataObject_iter _wrap_OesDataObject_iter ""
extern void (*_wrap_OesDataObject_iter)(void*);
static void (*x_wrap_OesDataObject_iter)(void*) = _wrap_OesDataObject_iter;

void
·_swig_wrap_OesDataObject_iter(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDataObject_iter, &p);
}



#pragma dynimport _wrap_OesDataObject_set_bytes _wrap_OesDataObject_set_bytes ""
extern void (*_wrap_OesDataObject_set_bytes)(void*);
static void (*x_wrap_OesDataObject_set_bytes)(void*) = _wrap_OesDataObject_set_bytes;

void
·_swig_wrap_OesDataObject_set_bytes(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_OesDataObject_set_bytes, &p);
}



#pragma dynimport _wrap_OesDataObject_get_bytes _wrap_OesDataObject_get_bytes ""
extern void (*_wrap_OesDataObject_get_bytes)(void*);
static void (*x_wrap_OesDataObject_get_bytes)(void*) = _wrap_OesDataObject_get_bytes;

void
·_swig_wrap_OesDataObject_get_bytes(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_OesDataObject_get_bytes, &p);
}



#pragma dynimport _wrap_new_OesSigHandler _wrap_new_OesSigHandler ""
extern void (*_wrap_new_OesSigHandler)(void*);
static void (*x_wrap_new_OesSigHandler)(void*) = _wrap_new_OesSigHandler;

void
·_swig_wrap_new_OesSigHandler(struct {
  uint8 x[SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesSigHandler, &p);
}



#pragma dynimport _wrap_delete_OesSigHandler _wrap_delete_OesSigHandler ""
extern void (*_wrap_delete_OesSigHandler)(void*);
static void (*x_wrap_delete_OesSigHandler)(void*) = _wrap_delete_OesSigHandler;

void
·_swig_wrap_delete_OesSigHandler(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesSigHandler, &p);
}



#pragma dynimport _wrap_OesSigHandler_add__SWIG_0 _wrap_OesSigHandler_add__SWIG_0 ""
extern void (*_wrap_OesSigHandler_add__SWIG_0)(void*);
static void (*x_wrap_OesSigHandler_add__SWIG_0)(void*) = _wrap_OesSigHandler_add__SWIG_0;

void
·_swig_wrap_OesSigHandler_add__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesSigHandler_add__SWIG_0, &p);
}



#pragma dynimport _wrap_OesSigHandler_add__SWIG_1 _wrap_OesSigHandler_add__SWIG_1 ""
extern void (*_wrap_OesSigHandler_add__SWIG_1)(void*);
static void (*x_wrap_OesSigHandler_add__SWIG_1)(void*) = _wrap_OesSigHandler_add__SWIG_1;

void
·_swig_wrap_OesSigHandler_add__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesSigHandler_add__SWIG_1, &p);
}



#pragma dynimport _wrap_OesSigHandler_add__SWIG_2 _wrap_OesSigHandler_add__SWIG_2 ""
extern void (*_wrap_OesSigHandler_add__SWIG_2)(void*);
static void (*x_wrap_OesSigHandler_add__SWIG_2)(void*) = _wrap_OesSigHandler_add__SWIG_2;

void
·_swig_wrap_OesSigHandler_add__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesSigHandler_add__SWIG_2, &p);
}



#pragma dynimport _wrap_OesSigHandler_add__SWIG_3 _wrap_OesSigHandler_add__SWIG_3 ""
extern void (*_wrap_OesSigHandler_add__SWIG_3)(void*);
static void (*x_wrap_OesSigHandler_add__SWIG_3)(void*) = _wrap_OesSigHandler_add__SWIG_3;

void
·_swig_wrap_OesSigHandler_add__SWIG_3(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesSigHandler_add__SWIG_3, &p);
}



#pragma dynimport _wrap_OesSigHandler_add__SWIG_4 _wrap_OesSigHandler_add__SWIG_4 ""
extern void (*_wrap_OesSigHandler_add__SWIG_4)(void*);
static void (*x_wrap_OesSigHandler_add__SWIG_4)(void*) = _wrap_OesSigHandler_add__SWIG_4;

void
·_swig_wrap_OesSigHandler_add__SWIG_4(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesSigHandler_add__SWIG_4, &p);
}



#pragma dynimport _wrap_OesSigHandler_add__SWIG_5 _wrap_OesSigHandler_add__SWIG_5 ""
extern void (*_wrap_OesSigHandler_add__SWIG_5)(void*);
static void (*x_wrap_OesSigHandler_add__SWIG_5)(void*) = _wrap_OesSigHandler_add__SWIG_5;

void
·_swig_wrap_OesSigHandler_add__SWIG_5(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesSigHandler_add__SWIG_5, &p);
}



#pragma dynimport _wrap_new_OesDispatcher _wrap_new_OesDispatcher ""
extern void (*_wrap_new_OesDispatcher)(void*);
static void (*x_wrap_new_OesDispatcher)(void*) = _wrap_new_OesDispatcher;

void
·_swig_wrap_new_OesDispatcher(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesDispatcher, &p);
}



#pragma dynimport _wrap_delete_OesDispatcher _wrap_delete_OesDispatcher ""
extern void (*_wrap_delete_OesDispatcher)(void*);
static void (*x_wrap_delete_OesDispatcher)(void*) = _wrap_delete_OesDispatcher;

void
·_swig_wrap_delete_OesDispatcher(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesDispatcher, &p);
}



#pragma dynimport _wrap_OesDispatcher_start _wrap_OesDispatcher_start ""
extern void (*_wrap_OesDispatcher_start)(void*);
static void (*x_wrap_OesDispatcher_start)(void*) = _wrap_OesDispatcher_start;

void
·_swig_wrap_OesDispatcher_start(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDispatcher_start, &p);
}



#pragma dynimport _wrap_new_OesThreadDispatcher _wrap_new_OesThreadDispatcher ""
extern void (*_wrap_new_OesThreadDispatcher)(void*);
static void (*x_wrap_new_OesThreadDispatcher)(void*) = _wrap_new_OesThreadDispatcher;

void
·_swig_wrap_new_OesThreadDispatcher(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesThreadDispatcher, &p);
}



#pragma dynimport _wrap_delete_OesThreadDispatcher _wrap_delete_OesThreadDispatcher ""
extern void (*_wrap_delete_OesThreadDispatcher)(void*);
static void (*x_wrap_delete_OesThreadDispatcher)(void*) = _wrap_delete_OesThreadDispatcher;

void
·_swig_wrap_delete_OesThreadDispatcher(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesThreadDispatcher, &p);
}



#pragma dynimport _wrap_OesThreadDispatcher_start _wrap_OesThreadDispatcher_start ""
extern void (*_wrap_OesThreadDispatcher_start)(void*);
static void (*x_wrap_OesThreadDispatcher_start)(void*) = _wrap_OesThreadDispatcher_start;

void
·_swig_wrap_OesThreadDispatcher_start(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesThreadDispatcher_start, &p);
}



#pragma dynimport _wrap_new_OesStore _wrap_new_OesStore ""
extern void (*_wrap_new_OesStore)(void*);
static void (*x_wrap_new_OesStore)(void*) = _wrap_new_OesStore;

void
·_swig_wrap_new_OesStore(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesStore, &p);
}



#pragma dynimport _wrap_delete_OesStore _wrap_delete_OesStore ""
extern void (*_wrap_delete_OesStore)(void*);
static void (*x_wrap_delete_OesStore)(void*) = _wrap_delete_OesStore;

void
·_swig_wrap_delete_OesStore(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesStore, &p);
}



#pragma dynimport _wrap_new_OesNet _wrap_new_OesNet ""
extern void (*_wrap_new_OesNet)(void*);
static void (*x_wrap_new_OesNet)(void*) = _wrap_new_OesNet;

void
·_swig_wrap_new_OesNet(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesNet, &p);
}



#pragma dynimport _wrap_delete_OesNet _wrap_delete_OesNet ""
extern void (*_wrap_delete_OesNet)(void*);
static void (*x_wrap_delete_OesNet)(void*) = _wrap_delete_OesNet;

void
·_swig_wrap_delete_OesNet(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesNet, &p);
}



#pragma dynimport _wrap_OesNet_setName _wrap_OesNet_setName ""
extern void (*_wrap_OesNet_setName)(void*);
static void (*x_wrap_OesNet_setName)(void*) = _wrap_OesNet_setName;

void
·_swig_wrap_OesNet_setName(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_OesNet_setName, &p);
}



#pragma dynimport _wrap_OesNet_getName _wrap_OesNet_getName ""
extern void (*_wrap_OesNet_getName)(void*);
static void (*x_wrap_OesNet_getName)(void*) = _wrap_OesNet_getName;

void
·_swig_wrap_OesNet_getName(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_OesNet_getName, &p);
}



#pragma dynimport _wrap_delete_OesLoginModule _wrap_delete_OesLoginModule ""
extern void (*_wrap_delete_OesLoginModule)(void*);
static void (*x_wrap_delete_OesLoginModule)(void*) = _wrap_delete_OesLoginModule;

void
·_swig_wrap_delete_OesLoginModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesLoginModule, &p);
}



#pragma dynimport _wrap_new_OesLoginModule _wrap_new_OesLoginModule ""
extern void (*_wrap_new_OesLoginModule)(void*);
static void (*x_wrap_new_OesLoginModule)(void*) = _wrap_new_OesLoginModule;

void
·_swig_wrap_new_OesLoginModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesLoginModule, &p);
}



#pragma dynimport _wrap_new_OesBuiltInLoginModule _wrap_new_OesBuiltInLoginModule ""
extern void (*_wrap_new_OesBuiltInLoginModule)(void*);
static void (*x_wrap_new_OesBuiltInLoginModule)(void*) = _wrap_new_OesBuiltInLoginModule;

void
·_swig_wrap_new_OesBuiltInLoginModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesBuiltInLoginModule, &p);
}



#pragma dynimport _wrap_delete_OesBuiltInLoginModule _wrap_delete_OesBuiltInLoginModule ""
extern void (*_wrap_delete_OesBuiltInLoginModule)(void*);
static void (*x_wrap_delete_OesBuiltInLoginModule)(void*) = _wrap_delete_OesBuiltInLoginModule;

void
·_swig_wrap_delete_OesBuiltInLoginModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesBuiltInLoginModule, &p);
}



#pragma dynimport _wrap_OesBuiltInLoginModule_addAccount _wrap_OesBuiltInLoginModule_addAccount ""
extern void (*_wrap_OesBuiltInLoginModule_addAccount)(void*);
static void (*x_wrap_OesBuiltInLoginModule_addAccount)(void*) = _wrap_OesBuiltInLoginModule_addAccount;

void
·_swig_wrap_OesBuiltInLoginModule_addAccount(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesBuiltInLoginModule_addAccount, &p);
}



#pragma dynimport _wrap_OesBuiltInLoginModule_addPrivilege _wrap_OesBuiltInLoginModule_addPrivilege ""
extern void (*_wrap_OesBuiltInLoginModule_addPrivilege)(void*);
static void (*x_wrap_OesBuiltInLoginModule_addPrivilege)(void*) = _wrap_OesBuiltInLoginModule_addPrivilege;

void
·_swig_wrap_OesBuiltInLoginModule_addPrivilege(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesBuiltInLoginModule_addPrivilege, &p);
}



#pragma dynimport _wrap_OesBuiltInLoginModule_getModule _wrap_OesBuiltInLoginModule_getModule ""
extern void (*_wrap_OesBuiltInLoginModule_getModule)(void*);
static void (*x_wrap_OesBuiltInLoginModule_getModule)(void*) = _wrap_OesBuiltInLoginModule_getModule;

void
·_swig_wrap_OesBuiltInLoginModule_getModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesBuiltInLoginModule_getModule, &p);
}



#pragma dynimport _wrap_new_OesPamLoginModule _wrap_new_OesPamLoginModule ""
extern void (*_wrap_new_OesPamLoginModule)(void*);
static void (*x_wrap_new_OesPamLoginModule)(void*) = _wrap_new_OesPamLoginModule;

void
·_swig_wrap_new_OesPamLoginModule(struct {
  uint8 x[SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesPamLoginModule, &p);
}



#pragma dynimport _wrap_delete_OesPamLoginModule _wrap_delete_OesPamLoginModule ""
extern void (*_wrap_delete_OesPamLoginModule)(void*);
static void (*x_wrap_delete_OesPamLoginModule)(void*) = _wrap_delete_OesPamLoginModule;

void
·_swig_wrap_delete_OesPamLoginModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesPamLoginModule, &p);
}



#pragma dynimport _wrap_OesPamLoginModule_addPrivilege _wrap_OesPamLoginModule_addPrivilege ""
extern void (*_wrap_OesPamLoginModule_addPrivilege)(void*);
static void (*x_wrap_OesPamLoginModule_addPrivilege)(void*) = _wrap_OesPamLoginModule_addPrivilege;

void
·_swig_wrap_OesPamLoginModule_addPrivilege(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesPamLoginModule_addPrivilege, &p);
}



#pragma dynimport _wrap_OesPamLoginModule_getModule _wrap_OesPamLoginModule_getModule ""
extern void (*_wrap_OesPamLoginModule_getModule)(void*);
static void (*x_wrap_OesPamLoginModule_getModule)(void*) = _wrap_OesPamLoginModule_getModule;

void
·_swig_wrap_OesPamLoginModule_getModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesPamLoginModule_getModule, &p);
}



#pragma dynimport _wrap_new_OesServer _wrap_new_OesServer ""
extern void (*_wrap_new_OesServer)(void*);
static void (*x_wrap_new_OesServer)(void*) = _wrap_new_OesServer;

void
·_swig_wrap_new_OesServer(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesServer, &p);
}



#pragma dynimport _wrap_delete_OesServer _wrap_delete_OesServer ""
extern void (*_wrap_delete_OesServer)(void*);
static void (*x_wrap_delete_OesServer)(void*) = _wrap_delete_OesServer;

void
·_swig_wrap_delete_OesServer(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesServer, &p);
}



#pragma dynimport _wrap_OesServer_addLoginModule _wrap_OesServer_addLoginModule ""
extern void (*_wrap_OesServer_addLoginModule)(void*);
static void (*x_wrap_OesServer_addLoginModule)(void*) = _wrap_OesServer_addLoginModule;

void
·_swig_wrap_OesServer_addLoginModule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesServer_addLoginModule, &p);
}



#pragma dynimport _wrap_OesServer_addKernel _wrap_OesServer_addKernel ""
extern void (*_wrap_OesServer_addKernel)(void*);
static void (*x_wrap_OesServer_addKernel)(void*) = _wrap_OesServer_addKernel;

void
·_swig_wrap_OesServer_addKernel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesServer_addKernel, &p);
}



#pragma dynimport _wrap_new_OesDataObjectList _wrap_new_OesDataObjectList ""
extern void (*_wrap_new_OesDataObjectList)(void*);
static void (*x_wrap_new_OesDataObjectList)(void*) = _wrap_new_OesDataObjectList;

void
·_swig_wrap_new_OesDataObjectList(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesDataObjectList, &p);
}



#pragma dynimport _wrap_delete_OesDataObjectList _wrap_delete_OesDataObjectList ""
extern void (*_wrap_delete_OesDataObjectList)(void*);
static void (*x_wrap_delete_OesDataObjectList)(void*) = _wrap_delete_OesDataObjectList;

void
·_swig_wrap_delete_OesDataObjectList(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesDataObjectList, &p);
}



#pragma dynimport _wrap_OesDataObjectList_length _wrap_OesDataObjectList_length ""
extern void (*_wrap_OesDataObjectList_length)(void*);
static void (*x_wrap_OesDataObjectList_length)(void*) = _wrap_OesDataObjectList_length;

void
·_swig_wrap_OesDataObjectList_length(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDataObjectList_length, &p);
}



#pragma dynimport _wrap_OesDataObjectList_iter _wrap_OesDataObjectList_iter ""
extern void (*_wrap_OesDataObjectList_iter)(void*);
static void (*x_wrap_OesDataObjectList_iter)(void*) = _wrap_OesDataObjectList_iter;

void
·_swig_wrap_OesDataObjectList_iter(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDataObjectList_iter, &p);
}



#pragma dynimport _wrap_OesDataObjectList_newDataObject _wrap_OesDataObjectList_newDataObject ""
extern void (*_wrap_OesDataObjectList_newDataObject)(void*);
static void (*x_wrap_OesDataObjectList_newDataObject)(void*) = _wrap_OesDataObjectList_newDataObject;

void
·_swig_wrap_OesDataObjectList_newDataObject(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesDataObjectList_newDataObject, &p);
}



#pragma dynimport _wrap_delete_OesIterator _wrap_delete_OesIterator ""
extern void (*_wrap_delete_OesIterator)(void*);
static void (*x_wrap_delete_OesIterator)(void*) = _wrap_delete_OesIterator;

void
·_swig_wrap_delete_OesIterator(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesIterator, &p);
}



#pragma dynimport _wrap_OesIterator_nextItem _wrap_OesIterator_nextItem ""
extern void (*_wrap_OesIterator_nextItem)(void*);
static void (*x_wrap_OesIterator_nextItem)(void*) = _wrap_OesIterator_nextItem;

void
·_swig_wrap_OesIterator_nextItem(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_OesIterator_nextItem, &p);
}



#pragma dynimport _wrap_OesIterator_hasMore _wrap_OesIterator_hasMore ""
extern void (*_wrap_OesIterator_hasMore)(void*);
static void (*x_wrap_OesIterator_hasMore)(void*) = _wrap_OesIterator_hasMore;

void
·_swig_wrap_OesIterator_hasMore(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesIterator_hasMore, &p);
}



#pragma dynimport _wrap_new_OesIterator _wrap_new_OesIterator ""
extern void (*_wrap_new_OesIterator)(void*);
static void (*x_wrap_new_OesIterator)(void*) = _wrap_new_OesIterator;

void
·_swig_wrap_new_OesIterator(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesIterator, &p);
}



#pragma dynimport _wrap_delete_OesListIterator _wrap_delete_OesListIterator ""
extern void (*_wrap_delete_OesListIterator)(void*);
static void (*x_wrap_delete_OesListIterator)(void*) = _wrap_delete_OesListIterator;

void
·_swig_wrap_delete_OesListIterator(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesListIterator, &p);
}



#pragma dynimport _wrap_OesListIterator_nextItem _wrap_OesListIterator_nextItem ""
extern void (*_wrap_OesListIterator_nextItem)(void*);
static void (*x_wrap_OesListIterator_nextItem)(void*) = _wrap_OesListIterator_nextItem;

void
·_swig_wrap_OesListIterator_nextItem(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesListIterator_nextItem, &p);
}



#pragma dynimport _wrap_OesListIterator_hasMore _wrap_OesListIterator_hasMore ""
extern void (*_wrap_OesListIterator_hasMore)(void*);
static void (*x_wrap_OesListIterator_hasMore)(void*) = _wrap_OesListIterator_hasMore;

void
·_swig_wrap_OesListIterator_hasMore(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesListIterator_hasMore, &p);
}



#pragma dynimport _wrap_new_OesListIterator _wrap_new_OesListIterator ""
extern void (*_wrap_new_OesListIterator)(void*);
static void (*x_wrap_new_OesListIterator)(void*) = _wrap_new_OesListIterator;

void
·_swig_wrap_new_OesListIterator(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesListIterator, &p);
}



#pragma dynimport _wrap_delete_OesLease _wrap_delete_OesLease ""
extern void (*_wrap_delete_OesLease)(void*);
static void (*x_wrap_delete_OesLease)(void*) = _wrap_delete_OesLease;

void
·_swig_wrap_delete_OesLease(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesLease, &p);
}



#pragma dynimport _wrap_OesLease_lid _wrap_OesLease_lid ""
extern void (*_wrap_OesLease_lid)(void*);
static void (*x_wrap_OesLease_lid)(void*) = _wrap_OesLease_lid;

void
·_swig_wrap_OesLease_lid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesLease_lid, &p);
}



#pragma dynimport _wrap_OesLease_cancel _wrap_OesLease_cancel ""
extern void (*_wrap_OesLease_cancel)(void*);
static void (*x_wrap_OesLease_cancel)(void*) = _wrap_OesLease_cancel;

void
·_swig_wrap_OesLease_cancel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesLease_cancel, &p);
}



#pragma dynimport _wrap_new_OesLease _wrap_new_OesLease ""
extern void (*_wrap_new_OesLease)(void*);
static void (*x_wrap_new_OesLease)(void*) = _wrap_new_OesLease;

void
·_swig_wrap_new_OesLease(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesLease, &p);
}



#pragma dynimport _wrap_delete_OesTxn _wrap_delete_OesTxn ""
extern void (*_wrap_delete_OesTxn)(void*);
static void (*x_wrap_delete_OesTxn)(void*) = _wrap_delete_OesTxn;

void
·_swig_wrap_delete_OesTxn(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesTxn, &p);
}



#pragma dynimport _wrap_OesTxn_tid _wrap_OesTxn_tid ""
extern void (*_wrap_OesTxn_tid)(void*);
static void (*x_wrap_OesTxn_tid)(void*) = _wrap_OesTxn_tid;

void
·_swig_wrap_OesTxn_tid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesTxn_tid, &p);
}



#pragma dynimport _wrap_OesTxn_status _wrap_OesTxn_status ""
extern void (*_wrap_OesTxn_status)(void*);
static void (*x_wrap_OesTxn_status)(void*) = _wrap_OesTxn_status;

void
·_swig_wrap_OesTxn_status(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesTxn_status, &p);
}



#pragma dynimport _wrap_OesTxn_commit _wrap_OesTxn_commit ""
extern void (*_wrap_OesTxn_commit)(void*);
static void (*x_wrap_OesTxn_commit)(void*) = _wrap_OesTxn_commit;

void
·_swig_wrap_OesTxn_commit(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesTxn_commit, &p);
}



#pragma dynimport _wrap_OesTxn_rollback _wrap_OesTxn_rollback ""
extern void (*_wrap_OesTxn_rollback)(void*);
static void (*x_wrap_OesTxn_rollback)(void*) = _wrap_OesTxn_rollback;

void
·_swig_wrap_OesTxn_rollback(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesTxn_rollback, &p);
}



#pragma dynimport _wrap_new_OesTxn _wrap_new_OesTxn ""
extern void (*_wrap_new_OesTxn)(void*);
static void (*x_wrap_new_OesTxn)(void*) = _wrap_new_OesTxn;

void
·_swig_wrap_new_OesTxn(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesTxn, &p);
}



#pragma dynimport _wrap_new_OesKernel _wrap_new_OesKernel ""
extern void (*_wrap_new_OesKernel)(void*);
static void (*x_wrap_new_OesKernel)(void*) = _wrap_new_OesKernel;

void
·_swig_wrap_new_OesKernel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesKernel, &p);
}



#pragma dynimport _wrap_delete_OesKernel _wrap_delete_OesKernel ""
extern void (*_wrap_delete_OesKernel)(void*);
static void (*x_wrap_delete_OesKernel)(void*) = _wrap_delete_OesKernel;

void
·_swig_wrap_delete_OesKernel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesKernel, &p);
}



#pragma dynimport _wrap_OesKernel_write _wrap_OesKernel_write ""
extern void (*_wrap_OesKernel_write)(void*);
static void (*x_wrap_OesKernel_write)(void*) = _wrap_OesKernel_write;

void
·_swig_wrap_OesKernel_write(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesKernel_write, &p);
}



#pragma dynimport _wrap_OesKernel_begin _wrap_OesKernel_begin ""
extern void (*_wrap_OesKernel_begin)(void*);
static void (*x_wrap_OesKernel_begin)(void*) = _wrap_OesKernel_begin;

void
·_swig_wrap_OesKernel_begin(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesKernel_begin, &p);
}



#pragma dynimport _wrap_OesKernel_setCurrent _wrap_OesKernel_setCurrent ""
extern void (*_wrap_OesKernel_setCurrent)(void*);
static void (*x_wrap_OesKernel_setCurrent)(void*) = _wrap_OesKernel_setCurrent;

void
·_swig_wrap_OesKernel_setCurrent(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesKernel_setCurrent, &p);
}



#pragma dynimport _wrap_OesKernel_read _wrap_OesKernel_read ""
extern void (*_wrap_OesKernel_read)(void*);
static void (*x_wrap_OesKernel_read)(void*) = _wrap_OesKernel_read;

void
·_swig_wrap_OesKernel_read(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesKernel_read, &p);
}



#pragma dynimport _wrap_OesKernel_take _wrap_OesKernel_take ""
extern void (*_wrap_OesKernel_take)(void*);
static void (*x_wrap_OesKernel_take)(void*) = _wrap_OesKernel_take;

void
·_swig_wrap_OesKernel_take(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesKernel_take, &p);
}



#pragma dynimport _wrap_new_OesJsonKernel _wrap_new_OesJsonKernel ""
extern void (*_wrap_new_OesJsonKernel)(void*);
static void (*x_wrap_new_OesJsonKernel)(void*) = _wrap_new_OesJsonKernel;

void
·_swig_wrap_new_OesJsonKernel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesJsonKernel, &p);
}



#pragma dynimport _wrap_delete_OesJsonKernel _wrap_delete_OesJsonKernel ""
extern void (*_wrap_delete_OesJsonKernel)(void*);
static void (*x_wrap_delete_OesJsonKernel)(void*) = _wrap_delete_OesJsonKernel;

void
·_swig_wrap_delete_OesJsonKernel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesJsonKernel, &p);
}



#pragma dynimport _wrap_OesJsonKernel_exec _wrap_OesJsonKernel_exec ""
extern void (*_wrap_OesJsonKernel_exec)(void*);
static void (*x_wrap_OesJsonKernel_exec)(void*) = _wrap_OesJsonKernel_exec;

void
·_swig_wrap_OesJsonKernel_exec(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OesJsonKernel_exec, &p);
}



#pragma dynimport _wrap_delete_OesFuture _wrap_delete_OesFuture ""
extern void (*_wrap_delete_OesFuture)(void*);
static void (*x_wrap_delete_OesFuture)(void*) = _wrap_delete_OesFuture;

void
·_swig_wrap_delete_OesFuture(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OesFuture, &p);
}



#pragma dynimport _wrap_OesFuture_getString _wrap_OesFuture_getString ""
extern void (*_wrap_OesFuture_getString)(void*);
static void (*x_wrap_OesFuture_getString)(void*) = _wrap_OesFuture_getString;

void
·_swig_wrap_OesFuture_getString(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_OesFuture_getString, &p);
}



#pragma dynimport _wrap_new_OesFuture _wrap_new_OesFuture ""
extern void (*_wrap_new_OesFuture)(void*);
static void (*x_wrap_new_OesFuture)(void*) = _wrap_new_OesFuture;

void
·_swig_wrap_new_OesFuture(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OesFuture, &p);
}



