/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

package oescriptimpl



import _ "runtime/cgo"



type _swig_fnptr *byte
type _swig_memberptr *byte

type Enum_SS_OES_TXN_STATUS int
func _swig_getACTIVE() Enum_SS_OES_TXN_STATUS
var ACTIVE Enum_SS_OES_TXN_STATUS = _swig_getACTIVE()
func _swig_getROLLEDBACK() Enum_SS_OES_TXN_STATUS
var ROLLEDBACK Enum_SS_OES_TXN_STATUS = _swig_getROLLEDBACK()
func _swig_getCOMMITTED() Enum_SS_OES_TXN_STATUS
var COMMITTED Enum_SS_OES_TXN_STATUS = _swig_getCOMMITTED()
type SwigcptrOesDataObject uintptr

func (p SwigcptrOesDataObject) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesDataObject) SwigIsOesDataObject() {
}

func _swig_wrap_new_OesDataObject() SwigcptrOesDataObject

func NewOesDataObject() OesDataObject {
	return _swig_wrap_new_OesDataObject()
}

func _swig_wrap_delete_OesDataObject(uintptr)

func DeleteOesDataObject(arg1 OesDataObject) {
	_swig_wrap_delete_OesDataObject(arg1.Swigcptr())
}

func _swig_wrap_OesDataObject_get_nattrs(SwigcptrOesDataObject) int

func (arg1 SwigcptrOesDataObject) Get_nattrs() int {
	return _swig_wrap_OesDataObject_get_nattrs(arg1)
}

func _swig_wrap_OesDataObject_add_attr(SwigcptrOesDataObject, string)

func (arg1 SwigcptrOesDataObject) Add_attr(arg2 string) {
	_swig_wrap_OesDataObject_add_attr(arg1, arg2)
}

func _swig_wrap_OesDataObject_set_nbytes(SwigcptrOesDataObject, int)

func (arg1 SwigcptrOesDataObject) Set_nbytes(arg2 int) {
	_swig_wrap_OesDataObject_set_nbytes(arg1, arg2)
}

func _swig_wrap_OesDataObject_get_nbytes(SwigcptrOesDataObject) int

func (arg1 SwigcptrOesDataObject) Get_nbytes() int {
	return _swig_wrap_OesDataObject_get_nbytes(arg1)
}

func _swig_wrap_OesDataObject_iter(SwigcptrOesDataObject) SwigcptrOesIterator

func (arg1 SwigcptrOesDataObject) Iter() OesIterator {
	return _swig_wrap_OesDataObject_iter(arg1)
}

func _swig_wrap_OesDataObject_set_bytes(SwigcptrOesDataObject, string)

func (arg1 SwigcptrOesDataObject) Set_bytes(arg2 string) {
	_swig_wrap_OesDataObject_set_bytes(arg1, arg2)
}

func _swig_wrap_OesDataObject_get_bytes(SwigcptrOesDataObject) string

func (arg1 SwigcptrOesDataObject) Get_bytes() string {
	return _swig_wrap_OesDataObject_get_bytes(arg1)
}

type OesDataObject interface {
	Swigcptr() uintptr
	SwigIsOesDataObject()
	Get_nattrs() int
	Add_attr(arg2 string)
	Set_nbytes(arg2 int)
	Get_nbytes() int
	Iter() OesIterator
	Set_bytes(arg2 string)
	Get_bytes() string
}

type SwigcptrOesSigHandler uintptr

func (p SwigcptrOesSigHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesSigHandler) SwigIsOesSigHandler() {
}

func _swig_wrap_new_OesSigHandler(string, string, string) SwigcptrOesSigHandler

func NewOesSigHandler(arg1 string, arg2 string, arg3 string) OesSigHandler {
	return _swig_wrap_new_OesSigHandler(arg1, arg2, arg3)
}

func _swig_wrap_delete_OesSigHandler(uintptr)

func DeleteOesSigHandler(arg1 OesSigHandler) {
	_swig_wrap_delete_OesSigHandler(arg1.Swigcptr())
}

func _swig_wrap_OesSigHandler_add__SWIG_0(SwigcptrOesSigHandler, uintptr)

func (arg1 SwigcptrOesSigHandler) Add__SWIG_0(arg2 OesDispatcher) {
	_swig_wrap_OesSigHandler_add__SWIG_0(arg1, arg2.Swigcptr())
}

func _swig_wrap_OesSigHandler_add__SWIG_1(SwigcptrOesSigHandler, uintptr)

func (arg1 SwigcptrOesSigHandler) Add__SWIG_1(arg2 OesThreadDispatcher) {
	_swig_wrap_OesSigHandler_add__SWIG_1(arg1, arg2.Swigcptr())
}

func _swig_wrap_OesSigHandler_add__SWIG_2(SwigcptrOesSigHandler, uintptr)

func (arg1 SwigcptrOesSigHandler) Add__SWIG_2(arg2 OesStore) {
	_swig_wrap_OesSigHandler_add__SWIG_2(arg1, arg2.Swigcptr())
}

func _swig_wrap_OesSigHandler_add__SWIG_3(SwigcptrOesSigHandler, uintptr)

func (arg1 SwigcptrOesSigHandler) Add__SWIG_3(arg2 OesServer) {
	_swig_wrap_OesSigHandler_add__SWIG_3(arg1, arg2.Swigcptr())
}

func _swig_wrap_OesSigHandler_add__SWIG_4(SwigcptrOesSigHandler, uintptr)

func (arg1 SwigcptrOesSigHandler) Add__SWIG_4(arg2 OesKernel) {
	_swig_wrap_OesSigHandler_add__SWIG_4(arg1, arg2.Swigcptr())
}

func _swig_wrap_OesSigHandler_add__SWIG_5(SwigcptrOesSigHandler, uintptr)

func (arg1 SwigcptrOesSigHandler) Add__SWIG_5(arg2 OesNet) {
	_swig_wrap_OesSigHandler_add__SWIG_5(arg1, arg2.Swigcptr())
}

func (p SwigcptrOesSigHandler) Add(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(SwigcptrOesDispatcher); !ok {
			goto check_1
		}
		p.Add__SWIG_0(a[0].(OesDispatcher))
		return
	}
check_1:
	if argc == 1 {
		if _, ok := a[0].(SwigcptrOesThreadDispatcher); !ok {
			goto check_2
		}
		p.Add__SWIG_1(a[0].(OesThreadDispatcher))
		return
	}
check_2:
	if argc == 1 {
		if _, ok := a[0].(SwigcptrOesStore); !ok {
			goto check_3
		}
		p.Add__SWIG_2(a[0].(OesStore))
		return
	}
check_3:
	if argc == 1 {
		if _, ok := a[0].(SwigcptrOesServer); !ok {
			goto check_4
		}
		p.Add__SWIG_3(a[0].(OesServer))
		return
	}
check_4:
	if argc == 1 {
		if _, ok := a[0].(SwigcptrOesKernel); !ok {
			goto check_5
		}
		p.Add__SWIG_4(a[0].(OesKernel))
		return
	}
check_5:
	if argc == 1 {
		p.Add__SWIG_5(a[0].(OesNet))
		return
	}
	panic("No match for overloaded function call")
}

type OesSigHandler interface {
	Swigcptr() uintptr
	SwigIsOesSigHandler()
	Add(a ...interface{})
}

type SwigcptrOesDispatcher uintptr

func (p SwigcptrOesDispatcher) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesDispatcher) SwigIsOesDispatcher() {
}

func _swig_wrap_new_OesDispatcher(int, string) SwigcptrOesDispatcher

func NewOesDispatcher(arg1 int, arg2 string) OesDispatcher {
	return _swig_wrap_new_OesDispatcher(arg1, arg2)
}

func _swig_wrap_delete_OesDispatcher(uintptr)

func DeleteOesDispatcher(arg1 OesDispatcher) {
	_swig_wrap_delete_OesDispatcher(arg1.Swigcptr())
}

func _swig_wrap_OesDispatcher_start(SwigcptrOesDispatcher)

func (arg1 SwigcptrOesDispatcher) Start() {
	_swig_wrap_OesDispatcher_start(arg1)
}

type OesDispatcher interface {
	Swigcptr() uintptr
	SwigIsOesDispatcher()
	Start()
}

type SwigcptrOesThreadDispatcher uintptr

func (p SwigcptrOesThreadDispatcher) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesThreadDispatcher) SwigIsOesThreadDispatcher() {
}

func _swig_wrap_new_OesThreadDispatcher(int) SwigcptrOesThreadDispatcher

func NewOesThreadDispatcher(arg1 int) OesThreadDispatcher {
	return _swig_wrap_new_OesThreadDispatcher(arg1)
}

func _swig_wrap_delete_OesThreadDispatcher(uintptr)

func DeleteOesThreadDispatcher(arg1 OesThreadDispatcher) {
	_swig_wrap_delete_OesThreadDispatcher(arg1.Swigcptr())
}

func _swig_wrap_OesThreadDispatcher_start(SwigcptrOesThreadDispatcher)

func (arg1 SwigcptrOesThreadDispatcher) Start() {
	_swig_wrap_OesThreadDispatcher_start(arg1)
}

type OesThreadDispatcher interface {
	Swigcptr() uintptr
	SwigIsOesThreadDispatcher()
	Start()
}

type SwigcptrOesStore uintptr

func (p SwigcptrOesStore) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesStore) SwigIsOesStore() {
}

func _swig_wrap_new_OesStore(int, string, bool) SwigcptrOesStore

func NewOesStore(arg1 int, arg2 string, arg3 bool) OesStore {
	return _swig_wrap_new_OesStore(arg1, arg2, arg3)
}

func _swig_wrap_delete_OesStore(uintptr)

func DeleteOesStore(arg1 OesStore) {
	_swig_wrap_delete_OesStore(arg1.Swigcptr())
}

type OesStore interface {
	Swigcptr() uintptr
	SwigIsOesStore()
}

type SwigcptrOesNet uintptr

func (p SwigcptrOesNet) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesNet) SwigIsOesNet() {
}

func _swig_wrap_new_OesNet(uintptr, bool, string, string) SwigcptrOesNet

func NewOesNet(arg1 OesDispatcher, arg2 bool, arg3 string, arg4 string) OesNet {
	return _swig_wrap_new_OesNet(arg1.Swigcptr(), arg2, arg3, arg4)
}

func _swig_wrap_delete_OesNet(uintptr)

func DeleteOesNet(arg1 OesNet) {
	_swig_wrap_delete_OesNet(arg1.Swigcptr())
}

func _swig_wrap_OesNet_setName(SwigcptrOesNet, string)

func (arg1 SwigcptrOesNet) SetName(arg2 string) {
	_swig_wrap_OesNet_setName(arg1, arg2)
}

func _swig_wrap_OesNet_getName(SwigcptrOesNet) string

func (arg1 SwigcptrOesNet) GetName() string {
	return _swig_wrap_OesNet_getName(arg1)
}

type OesNet interface {
	Swigcptr() uintptr
	SwigIsOesNet()
	SetName(arg2 string)
	GetName() string
}

type SwigcptrOesLoginModule uintptr

func (p SwigcptrOesLoginModule) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesLoginModule) SwigIsOesLoginModule() {
}

func _swig_wrap_delete_OesLoginModule(uintptr)

func DeleteOesLoginModule(arg1 OesLoginModule) {
	_swig_wrap_delete_OesLoginModule(arg1.Swigcptr())
}

func _swig_wrap_new_OesLoginModule() SwigcptrOesLoginModule

func NewOesLoginModule() OesLoginModule {
	return _swig_wrap_new_OesLoginModule()
}

type OesLoginModule interface {
	Swigcptr() uintptr
	SwigIsOesLoginModule()
}

type SwigcptrOesBuiltInLoginModule uintptr

func (p SwigcptrOesBuiltInLoginModule) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesBuiltInLoginModule) SwigIsOesBuiltInLoginModule() {
}

func _swig_wrap_new_OesBuiltInLoginModule() SwigcptrOesBuiltInLoginModule

func NewOesBuiltInLoginModule() OesBuiltInLoginModule {
	return _swig_wrap_new_OesBuiltInLoginModule()
}

func _swig_wrap_delete_OesBuiltInLoginModule(uintptr)

func DeleteOesBuiltInLoginModule(arg1 OesBuiltInLoginModule) {
	_swig_wrap_delete_OesBuiltInLoginModule(arg1.Swigcptr())
}

func _swig_wrap_OesBuiltInLoginModule_addAccount(SwigcptrOesBuiltInLoginModule, string, string, string) int

func (arg1 SwigcptrOesBuiltInLoginModule) AddAccount(arg2 string, arg3 string, arg4 string) int {
	return _swig_wrap_OesBuiltInLoginModule_addAccount(arg1, arg2, arg3, arg4)
}

func _swig_wrap_OesBuiltInLoginModule_addPrivilege(SwigcptrOesBuiltInLoginModule, string, string, string) int

func (arg1 SwigcptrOesBuiltInLoginModule) AddPrivilege(arg2 string, arg3 string, arg4 string) int {
	return _swig_wrap_OesBuiltInLoginModule_addPrivilege(arg1, arg2, arg3, arg4)
}

func _swig_wrap_OesBuiltInLoginModule_getModule(SwigcptrOesBuiltInLoginModule) SwigcptrOesLoginModule

func (arg1 SwigcptrOesBuiltInLoginModule) GetModule() OesLoginModule {
	return _swig_wrap_OesBuiltInLoginModule_getModule(arg1)
}

type OesBuiltInLoginModule interface {
	Swigcptr() uintptr
	SwigIsOesBuiltInLoginModule()
	AddAccount(arg2 string, arg3 string, arg4 string) int
	AddPrivilege(arg2 string, arg3 string, arg4 string) int
	GetModule() OesLoginModule
}

type SwigcptrOesPamLoginModule uintptr

func (p SwigcptrOesPamLoginModule) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesPamLoginModule) SwigIsOesPamLoginModule() {
}

func _swig_wrap_new_OesPamLoginModule(string, string) SwigcptrOesPamLoginModule

func NewOesPamLoginModule(arg1 string, arg2 string) OesPamLoginModule {
	return _swig_wrap_new_OesPamLoginModule(arg1, arg2)
}

func _swig_wrap_delete_OesPamLoginModule(uintptr)

func DeleteOesPamLoginModule(arg1 OesPamLoginModule) {
	_swig_wrap_delete_OesPamLoginModule(arg1.Swigcptr())
}

func _swig_wrap_OesPamLoginModule_addPrivilege(SwigcptrOesPamLoginModule, string, string, string) int

func (arg1 SwigcptrOesPamLoginModule) AddPrivilege(arg2 string, arg3 string, arg4 string) int {
	return _swig_wrap_OesPamLoginModule_addPrivilege(arg1, arg2, arg3, arg4)
}

func _swig_wrap_OesPamLoginModule_getModule(SwigcptrOesPamLoginModule) SwigcptrOesLoginModule

func (arg1 SwigcptrOesPamLoginModule) GetModule() OesLoginModule {
	return _swig_wrap_OesPamLoginModule_getModule(arg1)
}

type OesPamLoginModule interface {
	Swigcptr() uintptr
	SwigIsOesPamLoginModule()
	AddPrivilege(arg2 string, arg3 string, arg4 string) int
	GetModule() OesLoginModule
}

type SwigcptrOesServer uintptr

func (p SwigcptrOesServer) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesServer) SwigIsOesServer() {
}

func _swig_wrap_new_OesServer(uintptr, string, uintptr, uintptr) SwigcptrOesServer

func NewOesServer(arg1 OesDispatcher, arg2 string, arg3 OesNet, arg4 OesStore) OesServer {
	return _swig_wrap_new_OesServer(arg1.Swigcptr(), arg2, arg3.Swigcptr(), arg4.Swigcptr())
}

func _swig_wrap_delete_OesServer(uintptr)

func DeleteOesServer(arg1 OesServer) {
	_swig_wrap_delete_OesServer(arg1.Swigcptr())
}

func _swig_wrap_OesServer_addLoginModule(SwigcptrOesServer, uintptr)

func (arg1 SwigcptrOesServer) AddLoginModule(arg2 OesLoginModule) {
	_swig_wrap_OesServer_addLoginModule(arg1, arg2.Swigcptr())
}

func _swig_wrap_OesServer_addKernel(SwigcptrOesServer, string, uintptr)

func (arg1 SwigcptrOesServer) AddKernel(arg2 string, arg3 OesKernel) {
	_swig_wrap_OesServer_addKernel(arg1, arg2, arg3.Swigcptr())
}

type OesServer interface {
	Swigcptr() uintptr
	SwigIsOesServer()
	AddLoginModule(arg2 OesLoginModule)
	AddKernel(arg2 string, arg3 OesKernel)
}

type SwigcptrOesDataObjectList uintptr

func (p SwigcptrOesDataObjectList) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesDataObjectList) SwigIsOesDataObjectList() {
}

func _swig_wrap_new_OesDataObjectList() SwigcptrOesDataObjectList

func NewOesDataObjectList() OesDataObjectList {
	return _swig_wrap_new_OesDataObjectList()
}

func _swig_wrap_delete_OesDataObjectList(uintptr)

func DeleteOesDataObjectList(arg1 OesDataObjectList) {
	_swig_wrap_delete_OesDataObjectList(arg1.Swigcptr())
}

func _swig_wrap_OesDataObjectList_length(SwigcptrOesDataObjectList) int

func (arg1 SwigcptrOesDataObjectList) Length() int {
	return _swig_wrap_OesDataObjectList_length(arg1)
}

func _swig_wrap_OesDataObjectList_iter(SwigcptrOesDataObjectList) SwigcptrOesListIterator

func (arg1 SwigcptrOesDataObjectList) Iter() OesListIterator {
	return _swig_wrap_OesDataObjectList_iter(arg1)
}

func _swig_wrap_OesDataObjectList_newDataObject(SwigcptrOesDataObjectList) SwigcptrOesDataObject

func (arg1 SwigcptrOesDataObjectList) NewDataObject() OesDataObject {
	return _swig_wrap_OesDataObjectList_newDataObject(arg1)
}

type OesDataObjectList interface {
	Swigcptr() uintptr
	SwigIsOesDataObjectList()
	Length() int
	Iter() OesListIterator
	NewDataObject() OesDataObject
}

type SwigcptrOesIterator uintptr

func (p SwigcptrOesIterator) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesIterator) SwigIsOesIterator() {
}

func _swig_wrap_delete_OesIterator(uintptr)

func DeleteOesIterator(arg1 OesIterator) {
	_swig_wrap_delete_OesIterator(arg1.Swigcptr())
}

func _swig_wrap_OesIterator_nextItem(SwigcptrOesIterator) string

func (arg1 SwigcptrOesIterator) NextItem() string {
	return _swig_wrap_OesIterator_nextItem(arg1)
}

func _swig_wrap_OesIterator_hasMore(SwigcptrOesIterator) bool

func (arg1 SwigcptrOesIterator) HasMore() bool {
	return _swig_wrap_OesIterator_hasMore(arg1)
}

func _swig_wrap_new_OesIterator() SwigcptrOesIterator

func NewOesIterator() OesIterator {
	return _swig_wrap_new_OesIterator()
}

type OesIterator interface {
	Swigcptr() uintptr
	SwigIsOesIterator()
	NextItem() string
	HasMore() bool
}

type SwigcptrOesListIterator uintptr

func (p SwigcptrOesListIterator) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesListIterator) SwigIsOesListIterator() {
}

func _swig_wrap_delete_OesListIterator(uintptr)

func DeleteOesListIterator(arg1 OesListIterator) {
	_swig_wrap_delete_OesListIterator(arg1.Swigcptr())
}

func _swig_wrap_OesListIterator_nextItem(SwigcptrOesListIterator) SwigcptrOesDataObject

func (arg1 SwigcptrOesListIterator) NextItem() OesDataObject {
	return _swig_wrap_OesListIterator_nextItem(arg1)
}

func _swig_wrap_OesListIterator_hasMore(SwigcptrOesListIterator) bool

func (arg1 SwigcptrOesListIterator) HasMore() bool {
	return _swig_wrap_OesListIterator_hasMore(arg1)
}

func _swig_wrap_new_OesListIterator() SwigcptrOesListIterator

func NewOesListIterator() OesListIterator {
	return _swig_wrap_new_OesListIterator()
}

type OesListIterator interface {
	Swigcptr() uintptr
	SwigIsOesListIterator()
	NextItem() OesDataObject
	HasMore() bool
}

type SwigcptrOesLease uintptr

func (p SwigcptrOesLease) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesLease) SwigIsOesLease() {
}

func _swig_wrap_delete_OesLease(uintptr)

func DeleteOesLease(arg1 OesLease) {
	_swig_wrap_delete_OesLease(arg1.Swigcptr())
}

func _swig_wrap_OesLease_lid(SwigcptrOesLease) int32

func (arg1 SwigcptrOesLease) Lid() int32 {
	return _swig_wrap_OesLease_lid(arg1)
}

func _swig_wrap_OesLease_cancel(SwigcptrOesLease)

func (arg1 SwigcptrOesLease) Cancel() {
	_swig_wrap_OesLease_cancel(arg1)
}

func _swig_wrap_new_OesLease() SwigcptrOesLease

func NewOesLease() OesLease {
	return _swig_wrap_new_OesLease()
}

type OesLease interface {
	Swigcptr() uintptr
	SwigIsOesLease()
	Lid() int32
	Cancel()
}

type SwigcptrOesTxn uintptr

func (p SwigcptrOesTxn) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesTxn) SwigIsOesTxn() {
}

func _swig_wrap_delete_OesTxn(uintptr)

func DeleteOesTxn(arg1 OesTxn) {
	_swig_wrap_delete_OesTxn(arg1.Swigcptr())
}

func _swig_wrap_OesTxn_tid(SwigcptrOesTxn) int32

func (arg1 SwigcptrOesTxn) Tid() int32 {
	return _swig_wrap_OesTxn_tid(arg1)
}

func _swig_wrap_OesTxn_status(SwigcptrOesTxn) Enum_SS_OES_TXN_STATUS

func (arg1 SwigcptrOesTxn) Status() Enum_SS_OES_TXN_STATUS {
	return _swig_wrap_OesTxn_status(arg1)
}

func _swig_wrap_OesTxn_commit(SwigcptrOesTxn)

func (arg1 SwigcptrOesTxn) Commit() {
	_swig_wrap_OesTxn_commit(arg1)
}

func _swig_wrap_OesTxn_rollback(SwigcptrOesTxn)

func (arg1 SwigcptrOesTxn) Rollback() {
	_swig_wrap_OesTxn_rollback(arg1)
}

func _swig_wrap_new_OesTxn() SwigcptrOesTxn

func NewOesTxn() OesTxn {
	return _swig_wrap_new_OesTxn()
}

type OesTxn interface {
	Swigcptr() uintptr
	SwigIsOesTxn()
	Tid() int32
	Status() Enum_SS_OES_TXN_STATUS
	Commit()
	Rollback()
}

type SwigcptrOesKernel uintptr

func (p SwigcptrOesKernel) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesKernel) SwigIsOesKernel() {
}

func _swig_wrap_new_OesKernel(uintptr, uintptr, uintptr, string, uintptr, string, string) SwigcptrOesKernel

func NewOesKernel(arg1 OesDispatcher, arg2 OesThreadDispatcher, arg3 OesStore, arg4 string, arg5 OesNet, arg6 string, arg7 string) OesKernel {
	return _swig_wrap_new_OesKernel(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4, arg5.Swigcptr(), arg6, arg7)
}

func _swig_wrap_delete_OesKernel(uintptr)

func DeleteOesKernel(arg1 OesKernel) {
	_swig_wrap_delete_OesKernel(arg1.Swigcptr())
}

func _swig_wrap_OesKernel_write(SwigcptrOesKernel, uintptr, int32, bool) SwigcptrOesLease

func (arg1 SwigcptrOesKernel) Write(arg2 OesDataObject, arg3 int32, arg4 bool) OesLease {
	return _swig_wrap_OesKernel_write(arg1, arg2.Swigcptr(), arg3, arg4)
}

func _swig_wrap_OesKernel_begin(SwigcptrOesKernel, int32) SwigcptrOesTxn

func (arg1 SwigcptrOesKernel) Begin(arg2 int32) OesTxn {
	return _swig_wrap_OesKernel_begin(arg1, arg2)
}

func _swig_wrap_OesKernel_setCurrent(SwigcptrOesKernel, uintptr)

func (arg1 SwigcptrOesKernel) SetCurrent(arg2 OesTxn) {
	_swig_wrap_OesKernel_setCurrent(arg1, arg2.Swigcptr())
}

func _swig_wrap_OesKernel_read(SwigcptrOesKernel, uintptr, int32, bool, int, bool, bool) SwigcptrOesDataObjectList

func (arg1 SwigcptrOesKernel) Read(arg2 OesDataObjectList, arg3 int32, arg4 bool, arg5 int, arg6 bool, arg7 bool) OesDataObjectList {
	return _swig_wrap_OesKernel_read(arg1, arg2.Swigcptr(), arg3, arg4, arg5, arg6, arg7)
}

func _swig_wrap_OesKernel_take(SwigcptrOesKernel, uintptr, int32, bool, int, bool, bool) SwigcptrOesDataObjectList

func (arg1 SwigcptrOesKernel) Take(arg2 OesDataObjectList, arg3 int32, arg4 bool, arg5 int, arg6 bool, arg7 bool) OesDataObjectList {
	return _swig_wrap_OesKernel_take(arg1, arg2.Swigcptr(), arg3, arg4, arg5, arg6, arg7)
}

type OesKernel interface {
	Swigcptr() uintptr
	SwigIsOesKernel()
	Write(arg2 OesDataObject, arg3 int32, arg4 bool) OesLease
	Begin(arg2 int32) OesTxn
	SetCurrent(arg2 OesTxn)
	Read(arg2 OesDataObjectList, arg3 int32, arg4 bool, arg5 int, arg6 bool, arg7 bool) OesDataObjectList
	Take(arg2 OesDataObjectList, arg3 int32, arg4 bool, arg5 int, arg6 bool, arg7 bool) OesDataObjectList
}

type SwigcptrOesJsonKernel uintptr

func (p SwigcptrOesJsonKernel) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesJsonKernel) SwigIsOesJsonKernel() {
}

func _swig_wrap_new_OesJsonKernel(uintptr) SwigcptrOesJsonKernel

func NewOesJsonKernel(arg1 OesKernel) OesJsonKernel {
	return _swig_wrap_new_OesJsonKernel(arg1.Swigcptr())
}

func _swig_wrap_delete_OesJsonKernel(uintptr)

func DeleteOesJsonKernel(arg1 OesJsonKernel) {
	_swig_wrap_delete_OesJsonKernel(arg1.Swigcptr())
}

func _swig_wrap_OesJsonKernel_exec(SwigcptrOesJsonKernel, string) SwigcptrOesFuture

func (arg1 SwigcptrOesJsonKernel) Exec(arg2 string) OesFuture {
	return _swig_wrap_OesJsonKernel_exec(arg1, arg2)
}

type OesJsonKernel interface {
	Swigcptr() uintptr
	SwigIsOesJsonKernel()
	Exec(arg2 string) OesFuture
}

type SwigcptrOesFuture uintptr

func (p SwigcptrOesFuture) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOesFuture) SwigIsOesFuture() {
}

func _swig_wrap_delete_OesFuture(uintptr)

func DeleteOesFuture(arg1 OesFuture) {
	_swig_wrap_delete_OesFuture(arg1.Swigcptr())
}

func _swig_wrap_OesFuture_getString(SwigcptrOesFuture, int32) string

func (arg1 SwigcptrOesFuture) GetString(arg2 int32) string {
	return _swig_wrap_OesFuture_getString(arg1, arg2)
}

func _swig_wrap_new_OesFuture() SwigcptrOesFuture

func NewOesFuture() OesFuture {
	return _swig_wrap_new_OesFuture()
}

type OesFuture interface {
	Swigcptr() uintptr
	SwigIsOesFuture()
	GetString(arg2 int32) string
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

