/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { char *p; int n; } _gostring_;
typedef struct { void* array; unsigned int len; unsigned int cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static void *_swig_goallocate(size_t len) {
  struct {
    size_t len;
    void *ret;
  } a;
  a.len = len;
  crosscall2(_cgo_allocate, &a, (int) sizeof a);
  return a.ret;
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




static _gostring_ _swig_makegostring(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)_swig_goallocate(l + 1);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}

#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


#include <config.h>
#include <assert.h>
#include <string.h>
#include "json_msg_factory.h"
#include "DataObject.h"
#include "DataObjectList.h"
#include "SignalHandler.h"
#include "Oed_Dispatcher.h"
#include "Oe_Thread_Dispatcher.h"
#include "OeNet.h"
#include "OeNetDefaultFactory.h"
#include "OeStore.h"
#include "OeStoreDefaultFactory.h"
#include "OEKI.h"
#include "OEK.h"
#include "OepFactory.h"
#include "OepServer.h"
#include "OepClient.h"
#include "mem.h"
#include "arena.h"
#include "oe_common.h"
#include "Oec_Future.h"
#include "LoginModule.h"
#include "BuiltInLoginModule.h"
//#ifdef OE_USE_PAM
#include "PamLoginModule.h"
//#endif
#include "OeScript.h"

SWIGINTERN OesDataObject *new_OesDataObject(){
            Arena_T arena;
            arena = Arena_new();
            DataObject slist;
            slist = DataObject_new(arena);
            OesDataObject *holder;
            holder = Mem_calloc(1, sizeof(OesDataObject), "../../OeScript.i", 96);
            holder->obj = slist;
            holder->arena = arena;
            holder->free_arena = true;
            return holder;
        }
SWIGINTERN void delete_OesDataObject(OesDataObject *self){
            if (self->arena && self->free_arena) {
                Arena_dispose(&self->arena);
            }
            Mem_free(self, "../../OeScript.i", 106);
        }
SWIGINTERN int OesDataObject_get_nattrs(OesDataObject *self){
            return DataObject_get_nattrs(self->obj);
        }
SWIGINTERN void OesDataObject_add_attr(OesDataObject *self,char *entry){
            Arena_T arena;
            arena = self->arena;
            assert(arena);
            int len = strlen(entry);
            char *new_oejcl_str;
            new_oejcl_str = Arena_alloc(arena, len + 1, "../../OeScript.i", 117);
            new_oejcl_str[len] = NULL;
            strncpy(new_oejcl_str, entry, len);
            DataObject_add_attr(self->obj, (oe_scalar) new_oejcl_str);
        }
SWIGINTERN void OesDataObject_set_nbytes(OesDataObject *self,size_t nbytes){
            DataObject_set_nbytes(self->obj, nbytes);
        }
SWIGINTERN int OesDataObject_get_nbytes(OesDataObject *self){
            return DataObject_get_nbytes(self->obj);
        }
SWIGINTERN OesIterator *OesDataObject_iter(OesDataObject *self){
            assert(self->obj);
            OesIterator *holder;
            holder = Mem_alloc(sizeof *holder, "../../OeScript.i", 131);
            holder->obj = DataObject_iterator(self->obj, false);
            return holder;
        }
SWIGINTERN void OesDataObject_set_bytes(OesDataObject *self,char *bytes){
            int len =  DataObject_get_nbytes(self->obj);
            assert(len);
            Arena_T arena;
            arena = self->arena;
            char *new_oejcl_str;
            new_oejcl_str = Arena_alloc(arena, len + 1, "../../OeScript.i", 141);
            new_oejcl_str[len] = NULL;
            memcpy(new_oejcl_str, bytes, len);
            DataObject_set_bytes(self->obj, new_oejcl_str);
        }
SWIGINTERN char *OesDataObject_get_bytes(OesDataObject *self){
            //use this for target langs that don't impl cstrings.i but
            //can marshall to a null terminated char* string 
            int len = DataObject_get_nbytes(self->obj);
            char *new_oejcl_str = Mem_alloc(len + 1, "../../OeScript.i", 168);
            if (len) {
                char *entry = DataObject_get_bytes(self->obj);
                memcpy(new_oejcl_str, entry, len);
            }
            new_oejcl_str[len] = NULL;
            return new_oejcl_str;
        }
SWIGINTERN OesSigHandler *new_OesSigHandler(char const *filename,char const *appname,char const *loglvl){
            SignalHandler h;
            char *lfilename = Mem_alloc(strlen(filename) + 1, "../../OeScript.i", 187);
            memcpy(lfilename, filename, strlen(filename) + 1);
            char *lloglvl = Mem_alloc(strlen(loglvl) + 1, "../../OeScript.i", 189);
            memcpy(lloglvl, loglvl, strlen(loglvl) + 1);
            char *lappname = Mem_alloc(strlen(appname) + 1, "../../OeScript.i", 191);
            memcpy(lappname, appname, strlen(appname) + 1);
            h = SignalHandler_new(lfilename, lappname, lloglvl);
            OesSigHandler *holder;
            holder = Mem_alloc(sizeof(OesSigHandler), "../../OeScript.i", 195);
            holder->obj = h;
            return holder;
        }
SWIGINTERN void delete_OesSigHandler(OesSigHandler *self){
            SignalHandler_shutdown(self->obj);
            SignalHandler_free(&self->obj);
            Mem_free(self, "../../OeScript.i", 202);
        }
SWIGINTERN void OesSigHandler_add__SWIG_0(OesSigHandler *self,OesDispatcher *manageme){
            SignalHandler_manage(self->obj, 
                                 Oed_Dispatcher_stop, 
                                 Oed_Dispatcher_free, 
                                 Oed_Dispatcher_stats, 
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_1(OesSigHandler *self,OesThreadDispatcher *manageme){
            SignalHandler_manage(self->obj, 
                                 Oe_Thread_Dispatcher_stop,
                                 Oe_Thread_Dispatcher_free,
                                 Oe_Thread_Dispatcher_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_2(OesSigHandler *self,OesStore *manageme){
            SignalHandler_manage(self->obj, 
                                 OeStore_stop,
                                 OeStore_free,
                                 OeStore_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_3(OesSigHandler *self,OesServer *manageme){
            SignalHandler_manage(self->obj, 
                                 NULL,
                                 OepServer_free,
                                 OepServer_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_4(OesSigHandler *self,OesKernel *manageme){
            SignalHandler_manage(self->obj, 
                                 OEK_stop, 
                                 OEK_free, 
                                 OEK_stats, 
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN void OesSigHandler_add__SWIG_5(OesSigHandler *self,OesNet *manageme){
            SignalHandler_manage(self->obj, 
                                 OeNet_stop,
                                 OeNet_free,
                                 OeNet_stats,
                                 manageme->obj);
            manageme->managed = true;
        }
SWIGINTERN OesDispatcher *new_OesDispatcher(size_t nthreads,char const *name){
            OesDispatcher *holder;
            holder = Mem_calloc(1, sizeof(OesDispatcher), "../../OeScript.i", 264);
            holder->obj = Oed_Dispatcher_new(nthreads, name);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesDispatcher(OesDispatcher *self){
            if (!self->managed) {
                Oed_Dispatcher_stop(self->obj);
                Oed_Dispatcher_free(&self->obj);
            }
            Mem_free(self, "../../OeScript.i", 274);
        }
SWIGINTERN void OesDispatcher_start(OesDispatcher *self){
            Oed_Dispatcher_start(self->obj);
        }
SWIGINTERN OesThreadDispatcher *new_OesThreadDispatcher(size_t nthreads){
            OesThreadDispatcher *holder;
            holder = Mem_calloc(1, sizeof(OesThreadDispatcher), "../../OeScript.i", 286);
            holder->obj = Oe_Thread_Dispatcher_new(nthreads);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesThreadDispatcher(OesThreadDispatcher *self){
            if (!self->managed) {
                Oe_Thread_Dispatcher_stop(self->obj);
                Oe_Thread_Dispatcher_free(&self->obj);
            }
            Mem_free(self, "../../OeScript.i", 296);
        }
SWIGINTERN void OesThreadDispatcher_start(OesThreadDispatcher *self){
            Oe_Thread_Dispatcher_start(self->obj);
        }
SWIGINTERN OesStore *new_OesStore(int persist_level,char const *homedir,bool threaded){
            OesStore *holder;
            holder = Mem_calloc(1, sizeof(OesStore), "../../OeScript.i", 308);
            holder->obj = OeStoreDefaultFactory_create(persist_level,
                                                       homedir, threaded);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesStore(OesStore *self){
            if (!self->managed) {
                OeStore_stop(self->obj);
                OeStore_free(&self->obj);
            }
            Mem_free(self, "../../OeScript.i", 319);
        }
SWIGINTERN OesNet *new_OesNet(OesDispatcher *d,bool use_ssl,char *cert,char *pkey){
            OesNet *holder;
            holder = Mem_calloc(1, sizeof(OesNet), "../../OeScript.i", 328);
            if (use_ssl) {
                holder->obj = OeNetDefaultSslFactory_create(d->obj, cert, pkey);
            } else {
                holder->obj = OeNetDefaultFactory_create(d->obj);
            }
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesNet(OesNet *self){
            if (!self->managed) {
                OeNet_stop(self->obj);
                OeNet_free(&self->obj);
            }
            Mem_free(self, "../../OeScript.i", 342);
        }
SWIGINTERN void OesNet_setName(OesNet *self,char *name){
            OeNet_set_name(self->obj, (oe_scalar) name);
        }
SWIGINTERN char *OesNet_getName(OesNet *self){
            return (char *) OeNet_get_name(self->obj);
        }
SWIGINTERN void delete_OesLoginModule(OesLoginModule *self){
            if (!self->managed) {
                LoginModule_free(&self->obj);
            }
            Mem_free(self, "../../OeScript.i", 359);
        }
SWIGINTERN OesBuiltInLoginModule *new_OesBuiltInLoginModule(){
            OesBuiltInLoginModule *holder;
            holder = Mem_calloc(1, sizeof(OesBuiltInLoginModule), "../../OeScript.i", 368);
            holder->obj = BuiltInLoginModule_new();
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesBuiltInLoginModule(OesBuiltInLoginModule *self){
            //impl'll get cleaned up by LoginModule
            Mem_free(self, "../../OeScript.i", 375);
        }
SWIGINTERN int OesBuiltInLoginModule_addAccount(OesBuiltInLoginModule *self,char *groupname,char *username,char *pwd){
            BuiltInLoginModule_add_account(self->obj, groupname, username, pwd);
            return 0;
        }
SWIGINTERN int OesBuiltInLoginModule_addPrivilege(OesBuiltInLoginModule *self,char *extentname,char *groupname,char *mtemplate){
            OekMsg msg = 0;
            int rc = json_msg_create(&msg, mtemplate,
                                     BuiltInLoginModule_get_arena(self->obj));
            if (rc) {
                //throw_exception(PARSE_PRIV_ERR);
                char *big_em = oec_str_concat(NULL, 2, PARSE_PRIV_ERR, mtemplate); //leaks
                throw_exception(big_em);
                return 1;
            }
            BuiltInLoginModule_add_privilege(self->obj, extentname, groupname, msg);
            return 0;
        }
SWIGINTERN OesLoginModule *OesBuiltInLoginModule_getModule(OesBuiltInLoginModule *self){
            OesLoginModule *holder;
            holder = Mem_alloc(sizeof *holder, "../../OeScript.i", 396);
            holder->obj = BuiltInLoginModule_new_module(self->obj);
            return holder;
        }
SWIGINTERN OesPamLoginModule *new_OesPamLoginModule(char *pamdomain,char *defgroup){
            OesPamLoginModule *holder;
            holder = Mem_calloc(1, sizeof(OesPamLoginModule), "../../OeScript.i", 408);
            holder->obj = PamLoginModule_new((oe_scalar) pamdomain, (oe_scalar) defgroup);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesPamLoginModule(OesPamLoginModule *self){
            //impl'll get cleaned up by LoginModule
            Mem_free(self, "../../OeScript.i", 415);
        }
SWIGINTERN int OesPamLoginModule_addPrivilege(OesPamLoginModule *self,char *extentname,char *groupname,char *mtemplate){
            OekMsg msg = 0;
            int rc = json_msg_create(&msg, mtemplate,
                                     PamLoginModule_get_arena(self->obj));
            if (rc) {
                //throw_exception(PARSE_PRIV_PAM_ERR);
                char *big_em = oec_str_concat(NULL, 2, PARSE_PRIV_PAM_ERR, mtemplate); //leaks
                throw_exception(big_em);
                return 1;
            }
            PamLoginModule_add_privilege(self->obj, extentname, groupname, msg);
            return 0;
        }
SWIGINTERN OesLoginModule *OesPamLoginModule_getModule(OesPamLoginModule *self){
            OesLoginModule *holder;
            holder = Mem_alloc(sizeof *holder, "../../OeScript.i", 438);
            holder->obj = PamLoginModule_new_module(self->obj);
            return holder;
        }
SWIGINTERN OesServer *new_OesServer(OesDispatcher *dispatcher,char *spec,OesNet *net,OesStore *store){
            OesServer *holder;
            holder = Mem_calloc(1, sizeof(OesServer), "../../OeScript.i", 451);
            holder->obj = OepFactory_new_server(dispatcher->obj, spec, net->obj, store->obj);
            holder->managed = false;
            return holder;
        }
SWIGINTERN void delete_OesServer(OesServer *self){
            if (!self->managed) {
                OepServer_free(&self->obj);
            }
            Mem_free(self, "../../OeScript.i", 460);
        }
SWIGINTERN void OesServer_addLoginModule(OesServer *self,OesLoginModule *m){
            OepServer_add_login_module(self->obj, m->obj);
        }
SWIGINTERN void OesServer_addKernel(OesServer *self,char *extentname,OesKernel *kernel){
            OepServer_add_kernel(self->obj, extentname, kernel->obj);
        }
SWIGINTERN OesDataObjectList *new_OesDataObjectList(){
            return OesKernel_impl_createOesDataObjectList(Arena_new(), NULL, NULL);
        }
SWIGINTERN void delete_OesDataObjectList(OesDataObjectList *self){
            if (self->f) {
                Oec_Future_free(&self->f);
            }
            if (self->arena) {
                Arena_dispose(&self->arena);
            }
            Mem_free(self, "../../OeScript.i", 486);
        }
SWIGINTERN int OesDataObjectList_length(OesDataObjectList *self){
            if (self->f) {
                Oec_Future_get(self->f, OEC_FOREVER); //just to make sure it is done
            }
            return DataObjectList_length(self->obj);
        }
SWIGINTERN OesListIterator *OesDataObjectList_iter(OesDataObjectList *self){
            OesListIterator *holder;
            holder = Mem_alloc(sizeof *holder, "../../OeScript.i", 496);
            holder->l = self->obj;
            holder->f = self->f;
            holder->obj = NULL;
            return holder;
        }
SWIGINTERN OesDataObject *OesDataObjectList_newDataObject(OesDataObjectList *self){
            if (self->f) {
                Oec_Future_get(self->f, OEC_FOREVER); //just to make sure it is done
            }
            OesDataObject *holder;
            holder = Mem_calloc(1, sizeof *holder, "../../OeScript.i", 507);
            holder->obj = DataObjectList_new_data_object(self->obj);
            holder->arena = self->arena;
            return holder;
        }
SWIGINTERN void delete_OesIterator(OesIterator *self){
            Iterator_free(self->obj);
            Mem_free(self, "../../OeScript.i", 519);
        }
SWIGINTERN char *OesIterator_nextItem(OesIterator *self){
            assert(self->obj);
            char *nl = Iterator_next(self->obj);
            if (nl == NULL) {
                return NULL;
            }
            int len = strlen(nl);
            char *newattr = Mem_alloc(len + 1, "../../OeScript.i", 528);
            strncpy(newattr, nl, len);
            newattr[len] = NULL;
            return newattr;
        }
SWIGINTERN bool OesIterator_hasMore(OesIterator *self){
            assert(self->obj);
            return Iterator_hasMore(self->obj);
        }
SWIGINTERN void delete_OesListIterator(OesListIterator *self){
            if (self->obj) Iterator_free(self->obj);
            Mem_free(self, "../../OeScript.i", 544);
        }
SWIGINTERN OesDataObject *OesListIterator_nextItem(OesListIterator *self){
            assert(self->l);
            if (self->f) Oec_Future_get(self->f, OEC_FOREVER);
            if (!self->obj) self->obj = DataObjectList_iterator(self->l, false);
            DataObject nl = Iterator_next(self->obj);
            if (nl == NULL) {
                return NULL;
            }
            OesDataObject *holder;
            holder = Mem_calloc(1, sizeof(OesDataObject), "../../OeScript.i", 555);
            holder->obj = nl;
            return holder;
        }
SWIGINTERN bool OesListIterator_hasMore(OesListIterator *self){
            assert(self->l);
            if (self->f) Oec_Future_get(self->f, OEC_FOREVER);
            if (!self->obj) self->obj = DataObjectList_iterator(self->l, false);
            return Iterator_hasMore(self->obj);
        }
SWIGINTERN void delete_OesLease(OesLease *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            Oec_Future_free(&self->f);
            Mem_free(self, "../../OeScript.i", 573);
        }
SWIGINTERN long OesLease_lid(OesLease *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            return self->lid;
        }
SWIGINTERN void OesLease_cancel(OesLease *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            OesKernel_impl_upl_cancel(self);
        }
SWIGINTERN void delete_OesTxn(OesTxn *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            Oec_CountdownLatch_free(self->enlisted);
            Oec_CountdownLatch_free(self->enlisted_counter);
            Oec_Future_free(&self->f);
            Mem_free(self, "../../OeScript.i", 599);
        }
SWIGINTERN long OesTxn_tid(OesTxn *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            return self->tid;
        }
SWIGINTERN enum OES_TXN_STATUS OesTxn_status(OesTxn *self){
            Oec_Future_get(self->f, OEC_FOREVER);
            return self->status;
        }
SWIGINTERN void OesTxn_commit(OesTxn *self){
            OesKernel_impl_commit(self);
        }
SWIGINTERN void OesTxn_rollback(OesTxn *self){
            OesKernel_impl_rollback(self);
        }
SWIGINTERN OesKernel *new_OesKernel(OesDispatcher *dispatcher,OesThreadDispatcher *tdispatcher,OesStore *store,char *netspec,OesNet *net,char *username,char *pwd){

            OesKernel *holder;
            holder = Mem_calloc(1, sizeof(OesKernel), "../../OeScript.i", 631);
            if (!netspec || strlen(netspec) == 0) {
                assert(dispatcher);
                assert(tdispatcher);
                assert(store);
                holder->obj = OEK_default_factory_new(dispatcher->obj,
                                                      tdispatcher->obj, store->obj);
            } else {
                assert(dispatcher); assert(net); assert(username); assert(pwd); assert(netspec);
                OE_DLOG( NULL, "OeScript:OesKernel remote connect user %s to %s\n",
                         username, netspec); // i18n
                OepClient cl = OepFactory_new_client(netspec, 
                                                     dispatcher->obj, net->obj,
                                                     username, pwd);
                if (cl == NULL) {
                    throw_exception("can not connect"); //i18n
                    return NULL;
                }
                holder->obj = OepClient_new_kernel(cl);
            }
            return holder;
        }
SWIGINTERN void delete_OesKernel(OesKernel *self){
            if (!self->managed) {
                OEK_stop(self->obj);
                OEK_free(&self->obj);
            }
            /*
            OEK_stop(self->obj);
            if (self->shutdown_cb) {
                //the shutdown is done externally because the kernel isn't smart
                // enough to know the sequence of stopping itself and its own parts.
                // this is usually a ref to SignalHandler shutdown cmd.
                self->shutdown_cb(self->shutdown_cb_arg);
            } else {
                OEK_free(&self->obj);
            }
            */
            Mem_free(self, "../../OeScript.i", 669);
        }
SWIGINTERN OesLease *OesKernel_write(OesKernel *self,OesDataObject *slist,long dur,bool is_tuple){
            return OesKernel_impl_write(self, slist, (oe_time) dur, is_tuple);
        }
SWIGINTERN OesTxn *OesKernel_begin(OesKernel *self,long dur){
            return OesKernel_impl_begin(self, (oe_time) dur);
        }
SWIGINTERN void OesKernel_setCurrent(OesKernel *self,OesTxn *txn_holder){
            self->currentTxn = txn_holder;
        }
SWIGINTERN OesDataObjectList *OesKernel_read(OesKernel *self,OesDataObjectList *data,long timeout,bool is_tuple,int max_responses,bool return_attrs,bool return_bytes){
            return OesKernel_impl_read(self, data, (oe_time) timeout,
                                       is_tuple, max_responses,
                                       return_attrs, return_bytes);
        }
SWIGINTERN OesDataObjectList *OesKernel_take(OesKernel *self,OesDataObjectList *data,long timeout,bool is_tuple,int max_responses,bool return_attrs,bool return_bytes){
            return OesKernel_impl_take(self, data, (oe_time) timeout,
                                       is_tuple, max_responses,
                                       return_attrs, return_bytes);
        }
SWIGINTERN OesJsonKernel *new_OesJsonKernel(OesKernel *kernel){

            OesJsonKernel *holder;
            holder = Mem_calloc(1, sizeof(OesJsonKernel), "../../OeScript.i", 715);
            holder->obj = JsonKernel_new(kernel->obj);
            return holder;
        }
SWIGINTERN void delete_OesJsonKernel(OesJsonKernel *self){
            if (!self->managed) {
                JsonKernel_free(&self->obj);
            }
            Mem_free(self, "../../OeScript.i", 723);
        }
SWIGINTERN OesFuture *OesJsonKernel_exec(OesJsonKernel *self,char *json){

            Oec_Future f = Oec_Future_new();

            JsonKernel_exec(self->obj, json, OesKernel_impl_json_promise, f);

            OesFuture *folder;
            folder = Mem_calloc(1, sizeof(OesFuture), "../../OeScript.i", 733);
            folder->obj = f;
            return folder;
        }
SWIGINTERN void delete_OesFuture(OesFuture *self){
            Oec_Future_free(&self->obj);
            Mem_free(self, "../../OeScript.i", 744);
        }
SWIGINTERN char *OesFuture_getString(OesFuture *self,long timeout){

            Oec_Future f = self->obj;

            return (char *) Oec_Future_get(f, timeout);
        }
#ifdef __cplusplus
extern "C" {
#endif

void
_wrap_ACTIVE(void *swig_v)
{
  enum OES_TXN_STATUS result;
  
  struct swigargs {
    long : 0;
    enum OES_TXN_STATUS result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = ACTIVE;
    
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_ROLLEDBACK(void *swig_v)
{
  enum OES_TXN_STATUS result;
  
  struct swigargs {
    long : 0;
    enum OES_TXN_STATUS result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = ROLLEDBACK;
    
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_COMMITTED(void *swig_v)
{
  enum OES_TXN_STATUS result;
  
  struct swigargs {
    long : 0;
    enum OES_TXN_STATUS result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = COMMITTED;
    
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_new_OesDataObject(void *swig_v)
{
  OesDataObject *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesDataObject *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObject *)new_OesDataObject();
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObject **)&swig_a->result = result; 
}


void
_wrap_delete_OesDataObject(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  
  struct swigargs {
    OesDataObject *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesDataObject(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesDataObject_get_nattrs(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  int result;
  
  struct swigargs {
    OesDataObject *arg1;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesDataObject_get_nattrs(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesDataObject_add_attr(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  char *arg2 = (char *) 0 ;
  
  struct swigargs {
    OesDataObject *arg1;
    _gostring_ arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  {
    oe_scalar err;
    clear_exception();
    OesDataObject_add_attr(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesDataObject_set_nbytes(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  size_t arg2 ;
  
  struct swigargs {
    OesDataObject *arg1;
    int arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  arg2 = (size_t)swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesDataObject_set_nbytes(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesDataObject_get_nbytes(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  int result;
  
  struct swigargs {
    OesDataObject *arg1;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesDataObject_get_nbytes(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesDataObject_iter(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  OesIterator *result = 0 ;
  
  struct swigargs {
    OesDataObject *arg1;
    long : 0;
    OesIterator *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesIterator *)OesDataObject_iter(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesIterator **)&swig_a->result = result; 
}


void
_wrap_OesDataObject_set_bytes(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  char *arg2 = (char *) 0 ;
  
  struct swigargs {
    OesDataObject *arg1;
    _gostring_ arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  {
    oe_scalar err;
    clear_exception();
    OesDataObject_set_bytes(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesDataObject_get_bytes(void *swig_v)
{
  OesDataObject *arg1 = (OesDataObject *) 0 ;
  char *result = 0 ;
  
  struct swigargs {
    OesDataObject *arg1;
    long : 0;
    _gostring_ result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObject **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesDataObject_get_bytes(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = _swig_makegostring((char*)result, result ? strlen((char*)result) : 0); 
}


void
_wrap_new_OesSigHandler(void *swig_v)
{
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  OesSigHandler *result = 0 ;
  
  struct swigargs {
    _gostring_ arg1;
    _gostring_ arg2;
    _gostring_ arg3;
    long : 0;
    OesSigHandler *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (char *)swig_a->arg1.p; 
  arg2 = (char *)swig_a->arg2.p; 
  arg3 = (char *)swig_a->arg3.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesSigHandler *)new_OesSigHandler((char const *)arg1,(char const *)arg2,(char const *)arg3);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesSigHandler **)&swig_a->result = result; 
}


void
_wrap_delete_OesSigHandler(void *swig_v)
{
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  
  struct swigargs {
    OesSigHandler *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesSigHandler **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesSigHandler(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesSigHandler_add__SWIG_0(void *swig_v)
{
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesDispatcher *arg2 = (OesDispatcher *) 0 ;
  
  struct swigargs {
    OesSigHandler *arg1;
    OesDispatcher *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesSigHandler **)&swig_a->arg1; 
  arg2 = *(OesDispatcher **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_0(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesSigHandler_add__SWIG_1(void *swig_v)
{
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesThreadDispatcher *arg2 = (OesThreadDispatcher *) 0 ;
  
  struct swigargs {
    OesSigHandler *arg1;
    OesThreadDispatcher *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesSigHandler **)&swig_a->arg1; 
  arg2 = *(OesThreadDispatcher **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_1(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesSigHandler_add__SWIG_2(void *swig_v)
{
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesStore *arg2 = (OesStore *) 0 ;
  
  struct swigargs {
    OesSigHandler *arg1;
    OesStore *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesSigHandler **)&swig_a->arg1; 
  arg2 = *(OesStore **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_2(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesSigHandler_add__SWIG_3(void *swig_v)
{
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesServer *arg2 = (OesServer *) 0 ;
  
  struct swigargs {
    OesSigHandler *arg1;
    OesServer *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesSigHandler **)&swig_a->arg1; 
  arg2 = *(OesServer **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_3(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesSigHandler_add__SWIG_4(void *swig_v)
{
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesKernel *arg2 = (OesKernel *) 0 ;
  
  struct swigargs {
    OesSigHandler *arg1;
    OesKernel *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesSigHandler **)&swig_a->arg1; 
  arg2 = *(OesKernel **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_4(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesSigHandler_add__SWIG_5(void *swig_v)
{
  OesSigHandler *arg1 = (OesSigHandler *) 0 ;
  OesNet *arg2 = (OesNet *) 0 ;
  
  struct swigargs {
    OesSigHandler *arg1;
    OesNet *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesSigHandler **)&swig_a->arg1; 
  arg2 = *(OesNet **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesSigHandler_add__SWIG_5(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesDispatcher(void *swig_v)
{
  size_t arg1 ;
  char *arg2 = (char *) 0 ;
  OesDispatcher *result = 0 ;
  
  struct swigargs {
    int arg1;
    _gostring_ arg2;
    long : 0;
    OesDispatcher *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (size_t)swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesDispatcher *)new_OesDispatcher(arg1,(char const *)arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDispatcher **)&swig_a->result = result; 
}


void
_wrap_delete_OesDispatcher(void *swig_v)
{
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  
  struct swigargs {
    OesDispatcher *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDispatcher **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesDispatcher(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesDispatcher_start(void *swig_v)
{
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  
  struct swigargs {
    OesDispatcher *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDispatcher **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    OesDispatcher_start(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesThreadDispatcher(void *swig_v)
{
  size_t arg1 ;
  OesThreadDispatcher *result = 0 ;
  
  struct swigargs {
    int arg1;
    long : 0;
    OesThreadDispatcher *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (size_t)swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesThreadDispatcher *)new_OesThreadDispatcher(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesThreadDispatcher **)&swig_a->result = result; 
}


void
_wrap_delete_OesThreadDispatcher(void *swig_v)
{
  OesThreadDispatcher *arg1 = (OesThreadDispatcher *) 0 ;
  
  struct swigargs {
    OesThreadDispatcher *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesThreadDispatcher **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesThreadDispatcher(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesThreadDispatcher_start(void *swig_v)
{
  OesThreadDispatcher *arg1 = (OesThreadDispatcher *) 0 ;
  
  struct swigargs {
    OesThreadDispatcher *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesThreadDispatcher **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    OesThreadDispatcher_start(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesStore(void *swig_v)
{
  int arg1 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  OesStore *result = 0 ;
  
  struct swigargs {
    int arg1;
    _gostring_ arg2;
    bool arg3;
    long : 0;
    OesStore *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (int)swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  arg3 = (bool)swig_a->arg3; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesStore *)new_OesStore(arg1,(char const *)arg2,arg3);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesStore **)&swig_a->result = result; 
}


void
_wrap_delete_OesStore(void *swig_v)
{
  OesStore *arg1 = (OesStore *) 0 ;
  
  struct swigargs {
    OesStore *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesStore **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesStore(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesNet(void *swig_v)
{
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  bool arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  OesNet *result = 0 ;
  
  struct swigargs {
    OesDispatcher *arg1;
    bool arg2;
    _gostring_ arg3;
    _gostring_ arg4;
    long : 0;
    OesNet *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDispatcher **)&swig_a->arg1; 
  arg2 = (bool)swig_a->arg2; 
  arg3 = (char *)swig_a->arg3.p; 
  arg4 = (char *)swig_a->arg4.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesNet *)new_OesNet(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesNet **)&swig_a->result = result; 
}


void
_wrap_delete_OesNet(void *swig_v)
{
  OesNet *arg1 = (OesNet *) 0 ;
  
  struct swigargs {
    OesNet *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesNet **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesNet(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesNet_setName(void *swig_v)
{
  OesNet *arg1 = (OesNet *) 0 ;
  char *arg2 = (char *) 0 ;
  
  struct swigargs {
    OesNet *arg1;
    _gostring_ arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesNet **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  {
    oe_scalar err;
    clear_exception();
    OesNet_setName(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesNet_getName(void *swig_v)
{
  OesNet *arg1 = (OesNet *) 0 ;
  char *result = 0 ;
  
  struct swigargs {
    OesNet *arg1;
    long : 0;
    _gostring_ result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesNet **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesNet_getName(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = _swig_makegostring((char*)result, result ? strlen((char*)result) : 0); 
}


void
_wrap_delete_OesLoginModule(void *swig_v)
{
  OesLoginModule *arg1 = (OesLoginModule *) 0 ;
  
  struct swigargs {
    OesLoginModule *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesLoginModule **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesLoginModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesLoginModule(void *swig_v)
{
  OesLoginModule *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesLoginModule *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesLoginModule *)calloc(1, sizeof(OesLoginModule));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLoginModule **)&swig_a->result = result; 
}


void
_wrap_new_OesBuiltInLoginModule(void *swig_v)
{
  OesBuiltInLoginModule *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesBuiltInLoginModule *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesBuiltInLoginModule *)new_OesBuiltInLoginModule();
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesBuiltInLoginModule **)&swig_a->result = result; 
}


void
_wrap_delete_OesBuiltInLoginModule(void *swig_v)
{
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  
  struct swigargs {
    OesBuiltInLoginModule *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesBuiltInLoginModule **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesBuiltInLoginModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesBuiltInLoginModule_addAccount(void *swig_v)
{
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int result;
  
  struct swigargs {
    OesBuiltInLoginModule *arg1;
    _gostring_ arg2;
    _gostring_ arg3;
    _gostring_ arg4;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesBuiltInLoginModule **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  arg3 = (char *)swig_a->arg3.p; 
  arg4 = (char *)swig_a->arg4.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesBuiltInLoginModule_addAccount(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesBuiltInLoginModule_addPrivilege(void *swig_v)
{
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int result;
  
  struct swigargs {
    OesBuiltInLoginModule *arg1;
    _gostring_ arg2;
    _gostring_ arg3;
    _gostring_ arg4;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesBuiltInLoginModule **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  arg3 = (char *)swig_a->arg3.p; 
  arg4 = (char *)swig_a->arg4.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesBuiltInLoginModule_addPrivilege(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesBuiltInLoginModule_getModule(void *swig_v)
{
  OesBuiltInLoginModule *arg1 = (OesBuiltInLoginModule *) 0 ;
  OesLoginModule *result = 0 ;
  
  struct swigargs {
    OesBuiltInLoginModule *arg1;
    long : 0;
    OesLoginModule *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesBuiltInLoginModule **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesLoginModule *)OesBuiltInLoginModule_getModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLoginModule **)&swig_a->result = result; 
}


void
_wrap_new_OesPamLoginModule(void *swig_v)
{
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  OesPamLoginModule *result = 0 ;
  
  struct swigargs {
    _gostring_ arg1;
    _gostring_ arg2;
    long : 0;
    OesPamLoginModule *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = (char *)swig_a->arg1.p; 
  arg2 = (char *)swig_a->arg2.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesPamLoginModule *)new_OesPamLoginModule(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesPamLoginModule **)&swig_a->result = result; 
}


void
_wrap_delete_OesPamLoginModule(void *swig_v)
{
  OesPamLoginModule *arg1 = (OesPamLoginModule *) 0 ;
  
  struct swigargs {
    OesPamLoginModule *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesPamLoginModule **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesPamLoginModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesPamLoginModule_addPrivilege(void *swig_v)
{
  OesPamLoginModule *arg1 = (OesPamLoginModule *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int result;
  
  struct swigargs {
    OesPamLoginModule *arg1;
    _gostring_ arg2;
    _gostring_ arg3;
    _gostring_ arg4;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesPamLoginModule **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  arg3 = (char *)swig_a->arg3.p; 
  arg4 = (char *)swig_a->arg4.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesPamLoginModule_addPrivilege(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesPamLoginModule_getModule(void *swig_v)
{
  OesPamLoginModule *arg1 = (OesPamLoginModule *) 0 ;
  OesLoginModule *result = 0 ;
  
  struct swigargs {
    OesPamLoginModule *arg1;
    long : 0;
    OesLoginModule *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesPamLoginModule **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesLoginModule *)OesPamLoginModule_getModule(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLoginModule **)&swig_a->result = result; 
}


void
_wrap_new_OesServer(void *swig_v)
{
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  char *arg2 = (char *) 0 ;
  OesNet *arg3 = (OesNet *) 0 ;
  OesStore *arg4 = (OesStore *) 0 ;
  OesServer *result = 0 ;
  
  struct swigargs {
    OesDispatcher *arg1;
    _gostring_ arg2;
    OesNet *arg3;
    OesStore *arg4;
    long : 0;
    OesServer *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDispatcher **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  arg3 = *(OesNet **)&swig_a->arg3; 
  arg4 = *(OesStore **)&swig_a->arg4; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesServer *)new_OesServer(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesServer **)&swig_a->result = result; 
}


void
_wrap_delete_OesServer(void *swig_v)
{
  OesServer *arg1 = (OesServer *) 0 ;
  
  struct swigargs {
    OesServer *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesServer **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesServer(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesServer_addLoginModule(void *swig_v)
{
  OesServer *arg1 = (OesServer *) 0 ;
  OesLoginModule *arg2 = (OesLoginModule *) 0 ;
  
  struct swigargs {
    OesServer *arg1;
    OesLoginModule *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesServer **)&swig_a->arg1; 
  arg2 = *(OesLoginModule **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesServer_addLoginModule(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesServer_addKernel(void *swig_v)
{
  OesServer *arg1 = (OesServer *) 0 ;
  char *arg2 = (char *) 0 ;
  OesKernel *arg3 = (OesKernel *) 0 ;
  
  struct swigargs {
    OesServer *arg1;
    _gostring_ arg2;
    OesKernel *arg3;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesServer **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  arg3 = *(OesKernel **)&swig_a->arg3; 
  
  {
    oe_scalar err;
    clear_exception();
    OesServer_addKernel(arg1,arg2,arg3);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesDataObjectList(void *swig_v)
{
  OesDataObjectList *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesDataObjectList *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObjectList *)new_OesDataObjectList();
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObjectList **)&swig_a->result = result; 
}


void
_wrap_delete_OesDataObjectList(void *swig_v)
{
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  
  struct swigargs {
    OesDataObjectList *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObjectList **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesDataObjectList(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesDataObjectList_length(void *swig_v)
{
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  int result;
  
  struct swigargs {
    OesDataObjectList *arg1;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObjectList **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (int)OesDataObjectList_length(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesDataObjectList_iter(void *swig_v)
{
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  OesListIterator *result = 0 ;
  
  struct swigargs {
    OesDataObjectList *arg1;
    long : 0;
    OesListIterator *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObjectList **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesListIterator *)OesDataObjectList_iter(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesListIterator **)&swig_a->result = result; 
}


void
_wrap_OesDataObjectList_newDataObject(void *swig_v)
{
  OesDataObjectList *arg1 = (OesDataObjectList *) 0 ;
  OesDataObject *result = 0 ;
  
  struct swigargs {
    OesDataObjectList *arg1;
    long : 0;
    OesDataObject *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDataObjectList **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObject *)OesDataObjectList_newDataObject(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObject **)&swig_a->result = result; 
}


void
_wrap_delete_OesIterator(void *swig_v)
{
  OesIterator *arg1 = (OesIterator *) 0 ;
  
  struct swigargs {
    OesIterator *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesIterator **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesIterator(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesIterator_nextItem(void *swig_v)
{
  OesIterator *arg1 = (OesIterator *) 0 ;
  char *result = 0 ;
  
  struct swigargs {
    OesIterator *arg1;
    long : 0;
    _gostring_ result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesIterator **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesIterator_nextItem(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = _swig_makegostring((char*)result, result ? strlen((char*)result) : 0); 
}


void
_wrap_OesIterator_hasMore(void *swig_v)
{
  OesIterator *arg1 = (OesIterator *) 0 ;
  bool result;
  
  struct swigargs {
    OesIterator *arg1;
    long : 0;
    bool result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesIterator **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (bool)OesIterator_hasMore(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_new_OesIterator(void *swig_v)
{
  OesIterator *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesIterator *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesIterator *)calloc(1, sizeof(OesIterator));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesIterator **)&swig_a->result = result; 
}


void
_wrap_delete_OesListIterator(void *swig_v)
{
  OesListIterator *arg1 = (OesListIterator *) 0 ;
  
  struct swigargs {
    OesListIterator *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesListIterator **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesListIterator(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesListIterator_nextItem(void *swig_v)
{
  OesListIterator *arg1 = (OesListIterator *) 0 ;
  OesDataObject *result = 0 ;
  
  struct swigargs {
    OesListIterator *arg1;
    long : 0;
    OesDataObject *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesListIterator **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObject *)OesListIterator_nextItem(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObject **)&swig_a->result = result; 
}


void
_wrap_OesListIterator_hasMore(void *swig_v)
{
  OesListIterator *arg1 = (OesListIterator *) 0 ;
  bool result;
  
  struct swigargs {
    OesListIterator *arg1;
    long : 0;
    bool result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesListIterator **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (bool)OesListIterator_hasMore(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_new_OesListIterator(void *swig_v)
{
  OesListIterator *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesListIterator *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesListIterator *)calloc(1, sizeof(OesListIterator));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesListIterator **)&swig_a->result = result; 
}


void
_wrap_delete_OesLease(void *swig_v)
{
  OesLease *arg1 = (OesLease *) 0 ;
  
  struct swigargs {
    OesLease *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesLease **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesLease(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesLease_lid(void *swig_v)
{
  OesLease *arg1 = (OesLease *) 0 ;
  long result;
  
  struct swigargs {
    OesLease *arg1;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesLease **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (long)OesLease_lid(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesLease_cancel(void *swig_v)
{
  OesLease *arg1 = (OesLease *) 0 ;
  
  struct swigargs {
    OesLease *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesLease **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    OesLease_cancel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesLease(void *swig_v)
{
  OesLease *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesLease *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesLease *)calloc(1, sizeof(OesLease));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLease **)&swig_a->result = result; 
}


void
_wrap_delete_OesTxn(void *swig_v)
{
  OesTxn *arg1 = (OesTxn *) 0 ;
  
  struct swigargs {
    OesTxn *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesTxn **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesTxn(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesTxn_tid(void *swig_v)
{
  OesTxn *arg1 = (OesTxn *) 0 ;
  long result;
  
  struct swigargs {
    OesTxn *arg1;
    long : 0;
    int result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesTxn **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (long)OesTxn_tid(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesTxn_status(void *swig_v)
{
  OesTxn *arg1 = (OesTxn *) 0 ;
  enum OES_TXN_STATUS result;
  
  struct swigargs {
    OesTxn *arg1;
    long : 0;
    enum OES_TXN_STATUS result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesTxn **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (enum OES_TXN_STATUS)OesTxn_status(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = result; 
}


void
_wrap_OesTxn_commit(void *swig_v)
{
  OesTxn *arg1 = (OesTxn *) 0 ;
  
  struct swigargs {
    OesTxn *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesTxn **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    OesTxn_commit(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesTxn_rollback(void *swig_v)
{
  OesTxn *arg1 = (OesTxn *) 0 ;
  
  struct swigargs {
    OesTxn *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesTxn **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    OesTxn_rollback(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_new_OesTxn(void *swig_v)
{
  OesTxn *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesTxn *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesTxn *)calloc(1, sizeof(OesTxn));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesTxn **)&swig_a->result = result; 
}


void
_wrap_new_OesKernel(void *swig_v)
{
  OesDispatcher *arg1 = (OesDispatcher *) 0 ;
  OesThreadDispatcher *arg2 = (OesThreadDispatcher *) 0 ;
  OesStore *arg3 = (OesStore *) 0 ;
  char *arg4 = (char *) 0 ;
  OesNet *arg5 = (OesNet *) 0 ;
  char *arg6 = (char *) 0 ;
  char *arg7 = (char *) 0 ;
  OesKernel *result = 0 ;
  
  struct swigargs {
    OesDispatcher *arg1;
    OesThreadDispatcher *arg2;
    OesStore *arg3;
    _gostring_ arg4;
    OesNet *arg5;
    _gostring_ arg6;
    _gostring_ arg7;
    long : 0;
    OesKernel *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesDispatcher **)&swig_a->arg1; 
  arg2 = *(OesThreadDispatcher **)&swig_a->arg2; 
  arg3 = *(OesStore **)&swig_a->arg3; 
  arg4 = (char *)swig_a->arg4.p; 
  arg5 = *(OesNet **)&swig_a->arg5; 
  arg6 = (char *)swig_a->arg6.p; 
  arg7 = (char *)swig_a->arg7.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesKernel *)new_OesKernel(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesKernel **)&swig_a->result = result; 
}


void
_wrap_delete_OesKernel(void *swig_v)
{
  OesKernel *arg1 = (OesKernel *) 0 ;
  
  struct swigargs {
    OesKernel *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesKernel **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesKernel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesKernel_write(void *swig_v)
{
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesDataObject *arg2 = (OesDataObject *) 0 ;
  long arg3 ;
  bool arg4 ;
  OesLease *result = 0 ;
  
  struct swigargs {
    OesKernel *arg1;
    OesDataObject *arg2;
    int arg3;
    bool arg4;
    long : 0;
    OesLease *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesKernel **)&swig_a->arg1; 
  arg2 = *(OesDataObject **)&swig_a->arg2; 
  arg3 = (long)swig_a->arg3; 
  arg4 = (bool)swig_a->arg4; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesLease *)OesKernel_write(arg1,arg2,arg3,arg4);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesLease **)&swig_a->result = result; 
}


void
_wrap_OesKernel_begin(void *swig_v)
{
  OesKernel *arg1 = (OesKernel *) 0 ;
  long arg2 ;
  OesTxn *result = 0 ;
  
  struct swigargs {
    OesKernel *arg1;
    int arg2;
    long : 0;
    OesTxn *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesKernel **)&swig_a->arg1; 
  arg2 = (long)swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesTxn *)OesKernel_begin(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesTxn **)&swig_a->result = result; 
}


void
_wrap_OesKernel_setCurrent(void *swig_v)
{
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesTxn *arg2 = (OesTxn *) 0 ;
  
  struct swigargs {
    OesKernel *arg1;
    OesTxn *arg2;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesKernel **)&swig_a->arg1; 
  arg2 = *(OesTxn **)&swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    OesKernel_setCurrent(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesKernel_read(void *swig_v)
{
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesDataObjectList *arg2 = (OesDataObjectList *) 0 ;
  long arg3 ;
  bool arg4 ;
  int arg5 ;
  bool arg6 ;
  bool arg7 ;
  OesDataObjectList *result = 0 ;
  
  struct swigargs {
    OesKernel *arg1;
    OesDataObjectList *arg2;
    int arg3;
    bool arg4;
    int arg5;
    bool arg6;
    bool arg7;
    long : 0;
    OesDataObjectList *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesKernel **)&swig_a->arg1; 
  arg2 = *(OesDataObjectList **)&swig_a->arg2; 
  arg3 = (long)swig_a->arg3; 
  arg4 = (bool)swig_a->arg4; 
  arg5 = (int)swig_a->arg5; 
  arg6 = (bool)swig_a->arg6; 
  arg7 = (bool)swig_a->arg7; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObjectList *)OesKernel_read(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObjectList **)&swig_a->result = result; 
}


void
_wrap_OesKernel_take(void *swig_v)
{
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesDataObjectList *arg2 = (OesDataObjectList *) 0 ;
  long arg3 ;
  bool arg4 ;
  int arg5 ;
  bool arg6 ;
  bool arg7 ;
  OesDataObjectList *result = 0 ;
  
  struct swigargs {
    OesKernel *arg1;
    OesDataObjectList *arg2;
    int arg3;
    bool arg4;
    int arg5;
    bool arg6;
    bool arg7;
    long : 0;
    OesDataObjectList *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesKernel **)&swig_a->arg1; 
  arg2 = *(OesDataObjectList **)&swig_a->arg2; 
  arg3 = (long)swig_a->arg3; 
  arg4 = (bool)swig_a->arg4; 
  arg5 = (int)swig_a->arg5; 
  arg6 = (bool)swig_a->arg6; 
  arg7 = (bool)swig_a->arg7; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesDataObjectList *)OesKernel_take(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesDataObjectList **)&swig_a->result = result; 
}


void
_wrap_new_OesJsonKernel(void *swig_v)
{
  OesKernel *arg1 = (OesKernel *) 0 ;
  OesJsonKernel *result = 0 ;
  
  struct swigargs {
    OesKernel *arg1;
    long : 0;
    OesJsonKernel *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesKernel **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesJsonKernel *)new_OesJsonKernel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesJsonKernel **)&swig_a->result = result; 
}


void
_wrap_delete_OesJsonKernel(void *swig_v)
{
  OesJsonKernel *arg1 = (OesJsonKernel *) 0 ;
  
  struct swigargs {
    OesJsonKernel *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesJsonKernel **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesJsonKernel(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesJsonKernel_exec(void *swig_v)
{
  OesJsonKernel *arg1 = (OesJsonKernel *) 0 ;
  char *arg2 = (char *) 0 ;
  OesFuture *result = 0 ;
  
  struct swigargs {
    OesJsonKernel *arg1;
    _gostring_ arg2;
    long : 0;
    OesFuture *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesJsonKernel **)&swig_a->arg1; 
  arg2 = (char *)swig_a->arg2.p; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesFuture *)OesJsonKernel_exec(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesFuture **)&swig_a->result = result; 
}


void
_wrap_delete_OesFuture(void *swig_v)
{
  OesFuture *arg1 = (OesFuture *) 0 ;
  
  struct swigargs {
    OesFuture *arg1;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesFuture **)&swig_a->arg1; 
  
  {
    oe_scalar err;
    clear_exception();
    delete_OesFuture(arg1);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  
}


void
_wrap_OesFuture_getString(void *swig_v)
{
  OesFuture *arg1 = (OesFuture *) 0 ;
  long arg2 ;
  char *result = 0 ;
  
  struct swigargs {
    OesFuture *arg1;
    int arg2;
    long : 0;
    _gostring_ result;
  } *swig_a = (struct swigargs *) swig_v;
  
  arg1 = *(OesFuture **)&swig_a->arg1; 
  arg2 = (long)swig_a->arg2; 
  
  {
    oe_scalar err;
    clear_exception();
    result = (char *)OesFuture_getString(arg1,arg2);
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  swig_a->result = _swig_makegostring((char*)result, result ? strlen((char*)result) : 0); 
}


void
_wrap_new_OesFuture(void *swig_v)
{
  OesFuture *result = 0 ;
  
  struct swigargs {
    long : 0;
    OesFuture *result;
  } *swig_a = (struct swigargs *) swig_v;
  
  
  {
    oe_scalar err;
    clear_exception();
    result = (OesFuture *)calloc(1, sizeof(OesFuture));
    if ((err = check_exception())) {
      OE_ERR( NULL, "... swig exception: %s\n", err)
      assert(false);
      return err;
      
    }
  }
  *(OesFuture **)&swig_a->result = result; 
}


#ifdef __cplusplus
}
#endif

