# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_oescriptimpl', [dirname(__file__)])
        except ImportError:
            import _oescriptimpl
            return _oescriptimpl
        if fp is not None:
            try:
                _mod = imp.load_module('_oescriptimpl', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _oescriptimpl = swig_import_helper()
    del swig_import_helper
else:
    import _oescriptimpl
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


CSTRING_I_SUPPORTED = _oescriptimpl.CSTRING_I_SUPPORTED
ACTIVE = _oescriptimpl.ACTIVE
ROLLEDBACK = _oescriptimpl.ROLLEDBACK
COMMITTED = _oescriptimpl.COMMITTED
class OesDataObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesDataObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesDataObject, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _oescriptimpl.new_OesDataObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesDataObject
    __del__ = lambda self : None;
    def get_nattrs(self): return _oescriptimpl.OesDataObject_get_nattrs(self)
    def add_attr(self, *args): return _oescriptimpl.OesDataObject_add_attr(self, *args)
    def set_nbytes(self, *args): return _oescriptimpl.OesDataObject_set_nbytes(self, *args)
    def get_nbytes(self): return _oescriptimpl.OesDataObject_get_nbytes(self)
    def iter(self): return _oescriptimpl.OesDataObject_iter(self)
    def set_bytes(self, *args): return _oescriptimpl.OesDataObject_set_bytes(self, *args)
    def get_bytes(self): return _oescriptimpl.OesDataObject_get_bytes(self)
OesDataObject_swigregister = _oescriptimpl.OesDataObject_swigregister
OesDataObject_swigregister(OesDataObject)

class OesSigHandler(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesSigHandler, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesSigHandler, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesSigHandler(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesSigHandler
    __del__ = lambda self : None;
    def add(self, *args): return _oescriptimpl.OesSigHandler_add(self, *args)
OesSigHandler_swigregister = _oescriptimpl.OesSigHandler_swigregister
OesSigHandler_swigregister(OesSigHandler)

class OesDispatcher(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesDispatcher, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesDispatcher, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesDispatcher(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesDispatcher
    __del__ = lambda self : None;
    def start(self): return _oescriptimpl.OesDispatcher_start(self)
OesDispatcher_swigregister = _oescriptimpl.OesDispatcher_swigregister
OesDispatcher_swigregister(OesDispatcher)

class OesThreadDispatcher(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesThreadDispatcher, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesThreadDispatcher, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesThreadDispatcher(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesThreadDispatcher
    __del__ = lambda self : None;
    def start(self): return _oescriptimpl.OesThreadDispatcher_start(self)
OesThreadDispatcher_swigregister = _oescriptimpl.OesThreadDispatcher_swigregister
OesThreadDispatcher_swigregister(OesThreadDispatcher)

class OesStore(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesStore, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesStore, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesStore(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesStore
    __del__ = lambda self : None;
OesStore_swigregister = _oescriptimpl.OesStore_swigregister
OesStore_swigregister(OesStore)

class OesNet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesNet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesNet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesNet(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesNet
    __del__ = lambda self : None;
    def setName(self, *args): return _oescriptimpl.OesNet_setName(self, *args)
    def getName(self): return _oescriptimpl.OesNet_getName(self)
OesNet_swigregister = _oescriptimpl.OesNet_swigregister
OesNet_swigregister(OesNet)

class OesLoginModule(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesLoginModule, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesLoginModule, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oescriptimpl.delete_OesLoginModule
    __del__ = lambda self : None;
    def __init__(self): 
        this = _oescriptimpl.new_OesLoginModule()
        try: self.this.append(this)
        except: self.this = this
OesLoginModule_swigregister = _oescriptimpl.OesLoginModule_swigregister
OesLoginModule_swigregister(OesLoginModule)

class OesBuiltInLoginModule(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesBuiltInLoginModule, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesBuiltInLoginModule, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _oescriptimpl.new_OesBuiltInLoginModule()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesBuiltInLoginModule
    __del__ = lambda self : None;
    def addAccount(self, *args): return _oescriptimpl.OesBuiltInLoginModule_addAccount(self, *args)
    def addPrivilege(self, *args): return _oescriptimpl.OesBuiltInLoginModule_addPrivilege(self, *args)
    def getModule(self): return _oescriptimpl.OesBuiltInLoginModule_getModule(self)
OesBuiltInLoginModule_swigregister = _oescriptimpl.OesBuiltInLoginModule_swigregister
OesBuiltInLoginModule_swigregister(OesBuiltInLoginModule)

class OesPamLoginModule(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesPamLoginModule, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesPamLoginModule, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesPamLoginModule(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesPamLoginModule
    __del__ = lambda self : None;
    def addPrivilege(self, *args): return _oescriptimpl.OesPamLoginModule_addPrivilege(self, *args)
    def getModule(self): return _oescriptimpl.OesPamLoginModule_getModule(self)
OesPamLoginModule_swigregister = _oescriptimpl.OesPamLoginModule_swigregister
OesPamLoginModule_swigregister(OesPamLoginModule)

class OesServer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesServer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesServer, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesServer(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesServer
    __del__ = lambda self : None;
    def addLoginModule(self, *args): return _oescriptimpl.OesServer_addLoginModule(self, *args)
    def addKernel(self, *args): return _oescriptimpl.OesServer_addKernel(self, *args)
OesServer_swigregister = _oescriptimpl.OesServer_swigregister
OesServer_swigregister(OesServer)

class OesDataObjectList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesDataObjectList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesDataObjectList, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _oescriptimpl.new_OesDataObjectList()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesDataObjectList
    __del__ = lambda self : None;
    def length(self): return _oescriptimpl.OesDataObjectList_length(self)
    def iter(self): return _oescriptimpl.OesDataObjectList_iter(self)
    def newDataObject(self): return _oescriptimpl.OesDataObjectList_newDataObject(self)
OesDataObjectList_swigregister = _oescriptimpl.OesDataObjectList_swigregister
OesDataObjectList_swigregister(OesDataObjectList)

class OesIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesIterator, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oescriptimpl.delete_OesIterator
    __del__ = lambda self : None;
    def nextItem(self): return _oescriptimpl.OesIterator_nextItem(self)
    def hasMore(self): return _oescriptimpl.OesIterator_hasMore(self)
    def __init__(self): 
        this = _oescriptimpl.new_OesIterator()
        try: self.this.append(this)
        except: self.this = this
OesIterator_swigregister = _oescriptimpl.OesIterator_swigregister
OesIterator_swigregister(OesIterator)

class OesListIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesListIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesListIterator, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oescriptimpl.delete_OesListIterator
    __del__ = lambda self : None;
    def nextItem(self): return _oescriptimpl.OesListIterator_nextItem(self)
    def hasMore(self): return _oescriptimpl.OesListIterator_hasMore(self)
    def __init__(self): 
        this = _oescriptimpl.new_OesListIterator()
        try: self.this.append(this)
        except: self.this = this
OesListIterator_swigregister = _oescriptimpl.OesListIterator_swigregister
OesListIterator_swigregister(OesListIterator)

class OesLease(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesLease, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesLease, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oescriptimpl.delete_OesLease
    __del__ = lambda self : None;
    def lid(self): return _oescriptimpl.OesLease_lid(self)
    def cancel(self): return _oescriptimpl.OesLease_cancel(self)
    def __init__(self): 
        this = _oescriptimpl.new_OesLease()
        try: self.this.append(this)
        except: self.this = this
OesLease_swigregister = _oescriptimpl.OesLease_swigregister
OesLease_swigregister(OesLease)

class OesTxn(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesTxn, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesTxn, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oescriptimpl.delete_OesTxn
    __del__ = lambda self : None;
    def tid(self): return _oescriptimpl.OesTxn_tid(self)
    def status(self): return _oescriptimpl.OesTxn_status(self)
    def commit(self): return _oescriptimpl.OesTxn_commit(self)
    def rollback(self): return _oescriptimpl.OesTxn_rollback(self)
    def __init__(self): 
        this = _oescriptimpl.new_OesTxn()
        try: self.this.append(this)
        except: self.this = this
OesTxn_swigregister = _oescriptimpl.OesTxn_swigregister
OesTxn_swigregister(OesTxn)

class OesKernel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesKernel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesKernel, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesKernel(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesKernel
    __del__ = lambda self : None;
    def write(self, *args): return _oescriptimpl.OesKernel_write(self, *args)
    def begin(self, *args): return _oescriptimpl.OesKernel_begin(self, *args)
    def setCurrent(self, *args): return _oescriptimpl.OesKernel_setCurrent(self, *args)
    def read(self, *args): return _oescriptimpl.OesKernel_read(self, *args)
    def take(self, *args): return _oescriptimpl.OesKernel_take(self, *args)
OesKernel_swigregister = _oescriptimpl.OesKernel_swigregister
OesKernel_swigregister(OesKernel)

class OesJsonKernel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesJsonKernel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesJsonKernel, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _oescriptimpl.new_OesJsonKernel(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _oescriptimpl.delete_OesJsonKernel
    __del__ = lambda self : None;
    def _exec(self, *args): return _oescriptimpl.OesJsonKernel__exec(self, *args)
OesJsonKernel_swigregister = _oescriptimpl.OesJsonKernel_swigregister
OesJsonKernel_swigregister(OesJsonKernel)

class OesFuture(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OesFuture, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OesFuture, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oescriptimpl.delete_OesFuture
    __del__ = lambda self : None;
    def getString(self, *args): return _oescriptimpl.OesFuture_getString(self, *args)
    def __init__(self): 
        this = _oescriptimpl.new_OesFuture()
        try: self.this.append(this)
        except: self.this = this
OesFuture_swigregister = _oescriptimpl.OesFuture_swigregister
OesFuture_swigregister(OesFuture)

# This file is compatible with both classic and new-style classes.


