/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public final class OES_TXN_STATUS {
  public final static OES_TXN_STATUS ACTIVE = new OES_TXN_STATUS("ACTIVE");
  public final static OES_TXN_STATUS ROLLEDBACK = new OES_TXN_STATUS("ROLLEDBACK");
  public final static OES_TXN_STATUS COMMITTED = new OES_TXN_STATUS("COMMITTED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OES_TXN_STATUS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OES_TXN_STATUS.class + " with value " + swigValue);
  }

  private OES_TXN_STATUS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OES_TXN_STATUS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OES_TXN_STATUS(String swigName, OES_TXN_STATUS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OES_TXN_STATUS[] swigValues = { ACTIVE, ROLLEDBACK, COMMITTED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

