/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesBuiltInLoginModule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesBuiltInLoginModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesBuiltInLoginModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesBuiltInLoginModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OesBuiltInLoginModule() {
    this(oescriptimplJNI.new_OesBuiltInLoginModule(), true);
  }

  public int addAccount(String groupname, String username, String pwd) {
    return oescriptimplJNI.OesBuiltInLoginModule_addAccount(swigCPtr, this, groupname, username, pwd);
  }

  public int addPrivilege(String extentname, String groupname, String mtemplate) {
    return oescriptimplJNI.OesBuiltInLoginModule_addPrivilege(swigCPtr, this, extentname, groupname, mtemplate);
  }

  public OesLoginModule getModule() {
    long cPtr = oescriptimplJNI.OesBuiltInLoginModule_getModule(swigCPtr, this);
    return (cPtr == 0) ? null : new OesLoginModule(cPtr, false);
  }

}
