/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesDataObject {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesDataObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesDataObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesDataObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OesDataObject() {
    this(oescriptimplJNI.new_OesDataObject(), true);
  }

  public int get_nattrs() {
    return oescriptimplJNI.OesDataObject_get_nattrs(swigCPtr, this);
  }

  public void add_attr(String entry) {
    oescriptimplJNI.OesDataObject_add_attr(swigCPtr, this, entry);
  }

  public void set_nbytes(long nbytes) {
    oescriptimplJNI.OesDataObject_set_nbytes(swigCPtr, this, nbytes);
  }

  public int get_nbytes() {
    return oescriptimplJNI.OesDataObject_get_nbytes(swigCPtr, this);
  }

  public OesIterator iter() {
    long cPtr = oescriptimplJNI.OesDataObject_iter(swigCPtr, this);
    return (cPtr == 0) ? null : new OesIterator(cPtr, false);
  }

  public void set_bytes(String bytes) {
    oescriptimplJNI.OesDataObject_set_bytes(swigCPtr, this, bytes);
  }

  public String get_bytes() {
    return oescriptimplJNI.OesDataObject_get_bytes(swigCPtr, this);
  }

}
