/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesDispatcher {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesDispatcher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesDispatcher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesDispatcher(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OesDispatcher(long nthreads, String name) {
    this(oescriptimplJNI.new_OesDispatcher(nthreads, name), true);
  }

  public void start() {
    oescriptimplJNI.OesDispatcher_start(swigCPtr, this);
  }

}
