/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesFuture {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesFuture(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesFuture obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesFuture(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getString(int timeout) {
    return oescriptimplJNI.OesFuture_getString(swigCPtr, this, timeout);
  }

  public OesFuture() {
    this(oescriptimplJNI.new_OesFuture(), true);
  }

}
