/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String nextItem() {
    return oescriptimplJNI.OesIterator_nextItem(swigCPtr, this);
  }

  public boolean hasMore() {
    return oescriptimplJNI.OesIterator_hasMore(swigCPtr, this);
  }

  public OesIterator() {
    this(oescriptimplJNI.new_OesIterator(), true);
  }

}
