/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesJsonKernel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesJsonKernel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesJsonKernel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesJsonKernel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OesJsonKernel(OesKernel kernel) {
    this(oescriptimplJNI.new_OesJsonKernel(OesKernel.getCPtr(kernel), kernel), true);
  }

  public OesFuture exec(String json) {
    long cPtr = oescriptimplJNI.OesJsonKernel_exec(swigCPtr, this, json);
    return (cPtr == 0) ? null : new OesFuture(cPtr, false);
  }

}
