/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesKernel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesKernel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesKernel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesKernel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OesKernel(OesDispatcher dispatcher, OesThreadDispatcher tdispatcher, OesStore store, String netspec, OesNet net, String username, String pwd) {
    this(oescriptimplJNI.new_OesKernel(OesDispatcher.getCPtr(dispatcher), dispatcher, OesThreadDispatcher.getCPtr(tdispatcher), tdispatcher, OesStore.getCPtr(store), store, netspec, OesNet.getCPtr(net), net, username, pwd), true);
  }

  public OesLease write(OesDataObject slist, int dur, boolean is_tuple) {
    long cPtr = oescriptimplJNI.OesKernel_write(swigCPtr, this, OesDataObject.getCPtr(slist), slist, dur, is_tuple);
    return (cPtr == 0) ? null : new OesLease(cPtr, false);
  }

  public OesTxn begin(int dur) {
    long cPtr = oescriptimplJNI.OesKernel_begin(swigCPtr, this, dur);
    return (cPtr == 0) ? null : new OesTxn(cPtr, false);
  }

  public void setCurrent(OesTxn txn_holder) {
    oescriptimplJNI.OesKernel_setCurrent(swigCPtr, this, OesTxn.getCPtr(txn_holder), txn_holder);
  }

  public OesDataObjectList read(OesDataObjectList data, int timeout, boolean is_tuple, int max_responses, boolean return_attrs, boolean return_bytes) {
    long cPtr = oescriptimplJNI.OesKernel_read(swigCPtr, this, OesDataObjectList.getCPtr(data), data, timeout, is_tuple, max_responses, return_attrs, return_bytes);
    return (cPtr == 0) ? null : new OesDataObjectList(cPtr, false);
  }

  public OesDataObjectList take(OesDataObjectList data, int timeout, boolean is_tuple, int max_responses, boolean return_attrs, boolean return_bytes) {
    long cPtr = oescriptimplJNI.OesKernel_take(swigCPtr, this, OesDataObjectList.getCPtr(data), data, timeout, is_tuple, max_responses, return_attrs, return_bytes);
    return (cPtr == 0) ? null : new OesDataObjectList(cPtr, false);
  }

}
