/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesLease {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesLease(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesLease obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesLease(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int lid() {
    return oescriptimplJNI.OesLease_lid(swigCPtr, this);
  }

  public void cancel() {
    oescriptimplJNI.OesLease_cancel(swigCPtr, this);
  }

  public OesLease() {
    this(oescriptimplJNI.new_OesLease(), true);
  }

}
