/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesNet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesNet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesNet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesNet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OesNet(OesDispatcher d, boolean use_ssl, String cert, String pkey) {
    this(oescriptimplJNI.new_OesNet(OesDispatcher.getCPtr(d), d, use_ssl, cert, pkey), true);
  }

  public void setName(String name) {
    oescriptimplJNI.OesNet_setName(swigCPtr, this, name);
  }

  public String getName() {
    return oescriptimplJNI.OesNet_getName(swigCPtr, this);
  }

}
