/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.oescript.java.swig;

public class OesTxn {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OesTxn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OesTxn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        oescriptimplJNI.delete_OesTxn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int tid() {
    return oescriptimplJNI.OesTxn_tid(swigCPtr, this);
  }

  public OES_TXN_STATUS status() {
    return OES_TXN_STATUS.swigToEnum(oescriptimplJNI.OesTxn_status(swigCPtr, this));
  }

  public void commit() {
    oescriptimplJNI.OesTxn_commit(swigCPtr, this);
  }

  public void rollback() {
    oescriptimplJNI.OesTxn_rollback(swigCPtr, this);
  }

  public OesTxn() {
    this(oescriptimplJNI.new_OesTxn(), true);
  }

}
