---
abstract: 'The great new oescriptimpl!'
author:
  - 'OnExtent, LLC <info@onextent.com>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: oescriptimpl
provides:
  oescriptimpl:
    file: lib/oescriptimpl.pm
    version: 0.01
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: 0.01
